#!/usr/bin/env python3
"""
chiral_vs_symmetric_entropy.py
==============================

Executable comparison of two Z3 generation walks:

1. Chiral walk:
   0 -> 1 -> 2 -> 0
   represented by the pure shift matrix S_bar.

2. Symmetric mixing walk:
   each channel mixes equally into its two neighbors,
   represented by the nearest-neighbor circulant matrix
   T_sym = 0.5 * (S_bar + S_bar^2).

This is not a proof of the God Equation. It is a sandbox demonstration of a
clean physical intuition:

  chirality preserves generation identity,
  symmetric mixing destroys it.

Diagnostics:
- Shannon entropy H[p_t] for an initially localized generation state
- Return probability to the initial generation
- Purity sum_i p_i^2
- Mutual information I(X_0 ; X_t) for a uniform ensemble of initial channels

Run:
    python sandbox/chiral_vs_symmetric_entropy.py
"""

from __future__ import annotations

import csv
import math
from pathlib import Path

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np


SCRIPT_DIR = Path(__file__).parent
PLOT_PATH = SCRIPT_DIR / "chiral_vs_symmetric_entropy.png"
SCAN_PLOT_PATH = SCRIPT_DIR / "chiral_vs_symmetric_phase_scan.png"
SCAN_CSV_PATH = SCRIPT_DIR / "chiral_vs_symmetric_phase_scan.csv"


def s_bar_matrix() -> np.ndarray:
    """
    Cyclic shift on Z3:
        |0> -> |1>, |1> -> |2>, |2> -> |0>
    Matrix acts on column vectors.
    """
    return np.array(
        [
            [0.0, 0.0, 1.0],
            [1.0, 0.0, 0.0],
            [0.0, 1.0, 0.0],
        ]
    )


def chirality_family(eta: float) -> np.ndarray:
    """
    One-parameter family interpolating between:
      eta = 1.0  -> pure chiral shift S_bar
      eta = 0.0  -> symmetric nearest-neighbor mixing

    The family remains row-stochastic and circulant:
      T_eta = p_fwd S_bar + p_bwd S_bar^2
      p_fwd = (1 + eta) / 2
      p_bwd = (1 - eta) / 2
    """
    if not 0.0 <= eta <= 1.0:
        raise ValueError("eta must lie in [0, 1]")

    sbar = s_bar_matrix()
    sbar2 = np.linalg.matrix_power(sbar, 2)
    p_fwd = 0.5 * (1.0 + eta)
    p_bwd = 0.5 * (1.0 - eta)
    return p_fwd * sbar + p_bwd * sbar2


def shannon_entropy_bits(prob: np.ndarray) -> float:
    prob = np.asarray(prob, dtype=float)
    mask = prob > 0.0
    return float(-np.sum(prob[mask] * np.log2(prob[mask])))


def mutual_information_bits(transition: np.ndarray) -> float:
    """
    Mutual information I(X0 ; Xt) when X0 is uniform on {0,1,2} and Xt is
    generated by the transition matrix.
    """
    n = transition.shape[0]
    px = np.full(n, 1.0 / n)
    joint = px[:, None] * transition
    py = np.sum(joint, axis=0)
    info = 0.0
    for i in range(n):
        for j in range(n):
            if joint[i, j] > 0.0:
                info += joint[i, j] * math.log2(joint[i, j] / (px[i] * py[j]))
    return float(info)


def evolve_distribution(step_matrix: np.ndarray, p0: np.ndarray, steps: int) -> list[np.ndarray]:
    distributions = [p0.copy()]
    current = p0.copy()
    for _ in range(steps):
        current = step_matrix @ current
        distributions.append(current.copy())
    return distributions


def analyze_walk(step_matrix: np.ndarray, steps: int, label: str) -> dict[str, np.ndarray]:
    localized = np.array([1.0, 0.0, 0.0])
    dist_list = evolve_distribution(step_matrix, localized, steps)

    entropy = np.array([shannon_entropy_bits(p) for p in dist_list])
    return_prob = np.array([p[0] for p in dist_list])
    purity = np.array([float(np.sum(p**2)) for p in dist_list])
    mi = []
    for t in range(steps + 1):
        transition_t = np.linalg.matrix_power(step_matrix, t)
        mi.append(mutual_information_bits(transition_t))

    return {
        "label": label,
        "distributions": np.array(dist_list),
        "entropy": entropy,
        "return_prob": return_prob,
        "purity": np.array(purity),
        "mutual_info": np.array(mi),
    }


def scan_chirality_family(etas: np.ndarray, cycle_step: int, long_step: int) -> list[dict[str, float]]:
    max_info = math.log2(3.0)
    rows: list[dict[str, float]] = []
    for eta in etas:
        step_matrix = chirality_family(float(eta))
        cycle_matrix = np.linalg.matrix_power(step_matrix, cycle_step)
        long_matrix = np.linalg.matrix_power(step_matrix, long_step)
        evals = np.linalg.eigvals(step_matrix)
        subdominant = max(abs(ev) for ev in evals if abs(ev - 1.0) > 1e-10)

        cycle_from_zero = cycle_matrix[:, 0]
        long_from_zero = long_matrix[:, 0]
        cycle_info = mutual_information_bits(cycle_matrix)
        long_info = mutual_information_bits(long_matrix)

        rows.append(
            {
                "eta": float(eta),
                "p_forward": 0.5 * (1.0 + float(eta)),
                "p_backward": 0.5 * (1.0 - float(eta)),
                "entropy_t3": shannon_entropy_bits(cycle_from_zero),
                "return_t3": float(cycle_from_zero[0]),
                "purity_t3": float(np.sum(cycle_from_zero**2)),
                "mi_t3": cycle_info,
                "mi_t3_frac": cycle_info / max_info,
                "entropy_t18": shannon_entropy_bits(long_from_zero),
                "return_t18": float(long_from_zero[0]),
                "purity_t18": float(np.sum(long_from_zero**2)),
                "mi_t18": long_info,
                "mi_t18_frac": long_info / max_info,
                "subdominant_eval_abs": float(subdominant),
                "spectral_gap": float(1.0 - subdominant),
            }
        )

    return rows


def first_eta_at_or_above(rows: list[dict[str, float]], key: str, target: float) -> float | None:
    for row in rows:
        if row[key] >= target:
            return row["eta"]
    return None


def save_scan_csv(rows: list[dict[str, float]]) -> None:
    fieldnames = list(rows[0].keys())
    with SCAN_CSV_PATH.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def make_scan_plot(rows: list[dict[str, float]]) -> None:
    bg = "#0a0a14"
    fg = "#dddddd"
    c_chiral = "#00e0b8"
    c_mix = "#ff6b6b"
    c_gold = "#ffd166"
    c_blue = "#6ab7ff"

    eta = np.array([row["eta"] for row in rows])
    mi3 = np.array([row["mi_t3_frac"] for row in rows])
    mi18 = np.array([row["mi_t18_frac"] for row in rows])
    ret3 = np.array([row["return_t3"] for row in rows])
    ent3 = np.array([row["entropy_t3"] for row in rows])
    gap = np.array([row["spectral_gap"] for row in rows])

    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    fig.patch.set_facecolor(bg)
    for ax in axes.flat:
        ax.set_facecolor(bg)
        ax.tick_params(colors=fg, labelsize=9)
        for spine in ax.spines.values():
            spine.set_edgecolor("#333333")
        ax.grid(True, color="#222233", lw=0.5, alpha=0.7)

    ax = axes[0, 0]
    ax.set_title("Information Retention vs Chirality", color="white", fontsize=11, fontweight="bold")
    ax.plot(eta, mi3, color=c_chiral, lw=2.4, label="Cycle retention I(t=3) / log2(3)")
    ax.plot(eta, mi18, color=c_mix, lw=2.4, label="Long-horizon retention I(t=18) / log2(3)")
    ax.axhline(0.5, color=c_gold, ls="--", lw=1.6, label="50% retention")
    ax.set_xlabel("Chirality parameter η", color=fg)
    ax.set_ylabel("Retained identity fraction", color=fg)
    ax.legend(facecolor="#111122", labelcolor=fg, fontsize=8)

    ax = axes[0, 1]
    ax.set_title("One-Cycle Closure Quality", color="white", fontsize=11, fontweight="bold")
    ax.plot(eta, ret3, color=c_blue, lw=2.4, label="Return probability at t=3")
    ax.plot(eta, ent3 / math.log2(3.0), color=c_mix, lw=2.4, label="Entropy fraction at t=3")
    ax.axhline(1.0 / 3.0, color=c_gold, ls="--", lw=1.6, label="Uniform return = 1/3")
    ax.set_xlabel("Chirality parameter η", color=fg)
    ax.set_ylabel("Cycle metric", color=fg)
    ax.legend(facecolor="#111122", labelcolor=fg, fontsize=8)

    ax = axes[1, 0]
    ax.set_title("Mixing Rate", color="white", fontsize=11, fontweight="bold")
    ax.plot(eta, gap, color=c_gold, lw=2.4, label="Spectral gap 1 - |λ₂|")
    ax.set_xlabel("Chirality parameter η", color=fg)
    ax.set_ylabel("Spectral gap", color=fg)
    ax.legend(facecolor="#111122", labelcolor=fg, fontsize=8)

    ax = axes[1, 1]
    ax.set_title("Family Definition", color="white", fontsize=11, fontweight="bold")
    ax.axis("off")
    ax.text(0.04, 0.85, "Tη = pfwd S̄ + pbwd S̄²", color="white", fontsize=14, transform=ax.transAxes)
    ax.text(0.04, 0.67, "pfwd = (1 + η)/2", color=c_chiral, fontsize=12, transform=ax.transAxes)
    ax.text(0.04, 0.57, "pbwd = (1 - η)/2", color=c_mix, fontsize=12, transform=ax.transAxes)
    ax.text(0.04, 0.39, "η = 1  -> pure chiral shift", color=fg, fontsize=11, transform=ax.transAxes)
    ax.text(0.04, 0.30, "η = 0  -> symmetric nearest-neighbor mixing", color=fg, fontsize=11, transform=ax.transAxes)
    ax.text(0.04, 0.12, "Any η < 1 still mixes at long times; the scan quantifies\nhow much cycle-by-cycle identity survives before thermalization.",
            color=c_gold, fontsize=10, transform=ax.transAxes)

    fig.suptitle(
        "Chirality-to-Mixing Phase Scan — Z₃ Generation Walk",
        color="white", fontsize=13, y=0.98
    )
    plt.tight_layout(rect=(0, 0, 1, 0.96))
    plt.savefig(SCAN_PLOT_PATH, dpi=160, bbox_inches="tight", facecolor=bg)


def make_plot(times: np.ndarray,
              chiral: dict[str, np.ndarray],
              symmetric: dict[str, np.ndarray],
              sbar: np.ndarray,
              tsym: np.ndarray) -> None:
    bg = "#0a0a14"
    fg = "#dddddd"
    c_chiral = "#00e0b8"
    c_mix = "#ff6b6b"
    c_gold = "#ffd166"

    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    fig.patch.set_facecolor(bg)
    for ax in axes.flat:
        ax.set_facecolor(bg)
        ax.tick_params(colors=fg, labelsize=9)
        for spine in ax.spines.values():
            spine.set_edgecolor("#333333")
        ax.grid(True, color="#222233", lw=0.5, alpha=0.7)

    # Panel 1: matrices
    ax = axes[0, 0]
    ax.set_title("Step Operators", color="white", fontsize=11, fontweight="bold")
    ax.axis("off")
    ax.text(0.08, 0.82, "Chiral", color=c_chiral, fontsize=12, fontweight="bold", transform=ax.transAxes)
    ax.text(0.58, 0.82, "Symmetric Mixing", color=c_mix, fontsize=12, fontweight="bold", transform=ax.transAxes)
    ax.text(0.04, 0.48, np.array2string(sbar, precision=1, suppress_small=True),
            family="monospace", fontsize=12, color=fg, transform=ax.transAxes)
    ax.text(0.55, 0.48, np.array2string(tsym, precision=2, suppress_small=True),
            family="monospace", fontsize=12, color=fg, transform=ax.transAxes)
    ax.text(0.08, 0.18, r"$S_{\bar{}}^3 = I$", color=c_gold, fontsize=11, transform=ax.transAxes)
    ax.text(0.51, 0.18, r"$T_{\rm sym} = \frac{1}{2}(S_{\bar{}} + S_{\bar{}}^2)$",
            color=c_gold, fontsize=11, transform=ax.transAxes)

    # Panel 2: entropy
    ax = axes[0, 1]
    ax.set_title("Localized Generation State: Shannon Entropy", color="white", fontsize=11, fontweight="bold")
    ax.plot(times, chiral["entropy"], color=c_chiral, lw=2.5, label="Chiral walk")
    ax.plot(times, symmetric["entropy"], color=c_mix, lw=2.5, label="Symmetric walk")
    ax.axhline(math.log2(3.0), color=c_gold, ls="--", lw=1.8, label=r"Max entropy $\log_2 3$")
    ax.set_xlabel("Step", color=fg)
    ax.set_ylabel("Entropy (bits)", color=fg)
    ax.legend(facecolor="#111122", labelcolor=fg, fontsize=9)

    # Panel 3: return probability and purity
    ax = axes[1, 0]
    ax.set_title("Identity Preservation", color="white", fontsize=11, fontweight="bold")
    ax.plot(times, chiral["return_prob"], color=c_chiral, lw=2.2, label="Return prob (chiral)")
    ax.plot(times, symmetric["return_prob"], color=c_mix, lw=2.2, label="Return prob (symmetric)")
    ax.plot(times, chiral["purity"], color=c_chiral, lw=1.6, ls="--", alpha=0.85, label="Purity (chiral)")
    ax.plot(times, symmetric["purity"], color=c_mix, lw=1.6, ls="--", alpha=0.85, label="Purity (symmetric)")
    ax.set_xlabel("Step", color=fg)
    ax.set_ylabel("Probability / Purity", color=fg)
    ax.legend(facecolor="#111122", labelcolor=fg, fontsize=8)

    # Panel 4: mutual information
    ax = axes[1, 1]
    ax.set_title("Uniform Ensemble: Mutual Information", color="white", fontsize=11, fontweight="bold")
    ax.plot(times, chiral["mutual_info"], color=c_chiral, lw=2.5, label="Chiral walk")
    ax.plot(times, symmetric["mutual_info"], color=c_mix, lw=2.5, label="Symmetric walk")
    ax.axhline(math.log2(3.0), color=c_gold, ls="--", lw=1.8, label=r"Perfect identity $\log_2 3$")
    ax.set_xlabel("Step", color=fg)
    ax.set_ylabel("I(X₀ ; Xₜ)  [bits]", color=fg)
    ax.legend(facecolor="#111122", labelcolor=fg, fontsize=9)

    fig.suptitle(
        "Chirality vs Mixing — Z₃ Generation Walk\n"
        "Propagation Framework Sandbox: identity-preserving shift versus entropy-producing mixing",
        color="white", fontsize=13, y=0.98
    )
    plt.tight_layout(rect=(0, 0, 1, 0.96))
    plt.savefig(PLOT_PATH, dpi=160, bbox_inches="tight", facecolor=bg)


def main() -> None:
    sbar = s_bar_matrix()
    tsym = 0.5 * (sbar + np.linalg.matrix_power(sbar, 2))
    steps = 18
    times = np.arange(steps + 1)

    chiral = analyze_walk(sbar, steps, "chiral")
    symmetric = analyze_walk(tsym, steps, "symmetric")

    print("=" * 78)
    print("CHIRAL VS SYMMETRIC ENTROPY")
    print("=" * 78)
    print("Step operators:")
    print("Chiral S_bar =")
    print(sbar)
    print()
    print("Symmetric T_sym = 0.5 * (S_bar + S_bar^2) =")
    print(tsym)
    print()
    print(f"Max generation entropy = log2(3) = {math.log2(3.0):.6f} bits")
    print()

    for step in [0, 1, 2, 3, 6, 9, 18]:
        ce = chiral["entropy"][step]
        se = symmetric["entropy"][step]
        cr = chiral["return_prob"][step]
        sr = symmetric["return_prob"][step]
        cmi = chiral["mutual_info"][step]
        smi = symmetric["mutual_info"][step]
        print(f"Step {step:>2}:")
        print(f"  chiral    H={ce:.6f}  return={cr:.6f}  I(X0;Xt)={cmi:.6f}")
        print(f"  symmetric H={se:.6f}  return={sr:.6f}  I(X0;Xt)={smi:.6f}")

    print()
    print("Interpretation:")
    print("- The chiral walk is a permutation: no diffusion in generation space, zero")
    print("  entropy for a localized state, perfect information preservation.")
    print("- The symmetric walk mixes neighboring generations and drives the localized")
    print("  state toward the maximally mixed Z3 distribution.")
    print("- This does not prove chirality from the PF axioms, but it makes the")
    print("  stability-versus-mixing tradeoff executable.")

    make_plot(times, chiral, symmetric, sbar, tsym)
    etas = np.linspace(0.0, 1.0, 101)
    rows = scan_chirality_family(etas, cycle_step=3, long_step=18)
    save_scan_csv(rows)
    make_scan_plot(rows)

    eta_cycle_50 = first_eta_at_or_above(rows, "mi_t3_frac", 0.5)
    eta_cycle_90 = first_eta_at_or_above(rows, "mi_t3_frac", 0.9)
    eta_return_90 = first_eta_at_or_above(rows, "return_t3", 0.9)

    print()
    print(f"Plot saved: {PLOT_PATH}")
    print(f"Phase scan CSV saved: {SCAN_CSV_PATH}")
    print(f"Phase scan plot saved: {SCAN_PLOT_PATH}")
    print()
    print("Chirality scan summary:")
    print(f"- 50% cycle information retention reached at eta ≈ {eta_cycle_50:.2f}")
    print(f"- 90% cycle information retention reached at eta ≈ {eta_cycle_90:.2f}")
    print(f"- 90% three-step return probability reached at eta ≈ {eta_return_90:.2f}")
    print("- Long-horizon retention I(t=18) / log2(3) drops to zero for every eta < 1 in this family.")


if __name__ == "__main__":
    main()
