#!/usr/bin/env python3
"""
pf_toy_world_model.py
=====================

Phase 1 toy scaffold for a PF-style world model on a 3-channel Z3 latent.

This file is intentionally modest. It does NOT claim to derive the Axiom 3
selector, close H_prod, or identify the correct PF probability law.

What it does:
- parameterize a local row-stochastic circulant transition on three channels
- learn to predict synthetic next-step trajectories generated by a teacher walk
- expose a simple recurrence-based stability metric as a placeholder coherence
  diagnostic
- keep the observation head separate from the latent dynamics

This is a pressure-test harness for architecture ideas from PF_FOUNDATION_MODEL.md,
not an evidentiary artifact.

Usage:
  pip install torch
  python3 sandbox/pf_toy_world_model.py
"""

from __future__ import annotations

import math
import sys

try:
    import torch
    import torch.nn as nn
    import torch.optim as optim
    import torch.nn.functional as F
except ModuleNotFoundError:
    print("pf_toy_world_model.py requires PyTorch.")
    print("Install with: pip install torch")
    sys.exit(1)


def dirichlet_simplex(batch_size: int, dim: int, alpha: float = 1.0) -> torch.Tensor:
    """Sample normalized non-negative latent states on the simplex."""
    concentration = torch.full((dim,), alpha)
    return torch.distributions.Dirichlet(concentration).sample((batch_size,))


class PFToyWorldModel(nn.Module):
    def __init__(self, obs_dim: int = 2):
        super().__init__()

        # Z3 shift operators acting on column vectors.
        self.register_buffer(
            "S",
            torch.tensor(
                [
                    [0.0, 0.0, 1.0],
                    [1.0, 0.0, 0.0],
                    [0.0, 1.0, 0.0],
                ]
            ),
        )
        self.register_buffer(
            "S_T",
            torch.tensor(
                [
                    [0.0, 1.0, 0.0],
                    [0.0, 0.0, 1.0],
                    [1.0, 0.0, 0.0],
                ]
            ),
        )
        self.register_buffer("I", torch.eye(3))

        # A general local Z3 walk uses only stay / forward / backward weights.
        # This bakes locality in directly rather than penalizing it indirectly.
        self.transition_logits = nn.Parameter(torch.tensor([-2.0, 0.4, 0.4]))

        # Observation head is deliberately separate from the latent dynamics.
        self.obs_head = nn.Linear(3, obs_dim)

    def transition_matrix(self) -> tuple[torch.Tensor, torch.Tensor]:
        """
        Build a row-stochastic circulant transition:
          T = t0 * I + t1 * S + t2 * S^2
        where (t0, t1, t2) are learned via softmax.
        """
        probs = torch.softmax(self.transition_logits, dim=0)
        T = probs[0] * self.I + probs[1] * self.S + probs[2] * self.S_T
        return T, probs

    def propagate(self, x_t: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        """
        One-step latent update on the simplex.
        x_t is stored as a row vector batch, while T acts on column vectors, so
        the batch update is x_t @ T^T.
        """
        T, probs = self.transition_matrix()
        x_next = torch.matmul(x_t, T.T)
        x_next = x_next / x_next.sum(dim=-1, keepdim=True).clamp_min(1e-8)
        return x_next, probs

    def coherence(self, x_t: torch.Tensor, x_next: torch.Tensor) -> torch.Tensor:
        """
        Placeholder coherence diagnostic: one-step recurrence / self-similarity.

        This is intentionally weaker than a selector principle. High score means
        the propagation pattern remains self-consistent across one step; it does
        NOT mean the state is the symmetric k=0 mode or that a PF selection rule
        has been derived.
        """
        return F.cosine_similarity(x_t, x_next, dim=-1, eps=1e-8).unsqueeze(-1)

    def observe(self, x_t: torch.Tensor) -> torch.Tensor:
        return self.obs_head(x_t)

    def forward(self, x_t: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
        x_next, probs = self.propagate(x_t)
        c_score = self.coherence(x_t, x_next)
        y_next = self.observe(x_next)
        return x_next, c_score, y_next, probs


def build_teacher_transition(
    stay: float = 0.0, forward: float = 0.5, backward: float = 0.5
) -> torch.Tensor:
    """Synthetic teacher walk used to generate trajectories for the toy task."""
    if min(stay, forward, backward) < 0.0:
        raise ValueError("teacher transition weights must be non-negative")
    total = stay + forward + backward
    if not math.isclose(total, 1.0, rel_tol=1e-9, abs_tol=1e-9):
        raise ValueError("teacher transition weights must sum to 1")

    I = torch.eye(3)
    S = torch.tensor(
        [
            [0.0, 0.0, 1.0],
            [1.0, 0.0, 0.0],
            [0.0, 1.0, 0.0],
        ]
    )
    S_T = torch.tensor(
        [
            [0.0, 1.0, 0.0],
            [0.0, 0.0, 1.0],
            [1.0, 0.0, 0.0],
        ]
    )
    return stay * I + forward * S + backward * S_T


def loss_function(
    x_pred: torch.Tensor,
    x_target: torch.Tensor,
    y_pred: torch.Tensor,
    y_target: torch.Tensor,
    c_score: torch.Tensor,
    min_coherence: float = 0.90,
    lambda_latent: float = 1.0,
    lambda_obs: float = 0.25,
    lambda_coh: float = 0.05,
) -> tuple[torch.Tensor, dict[str, float]]:
    """
    The coherence term acts as a floor, not a selector:
    punish dispersive updates below a threshold, but do not hard-code a unique
    "best" mode.
    """
    l_latent = F.mse_loss(x_pred, x_target)
    l_obs = F.mse_loss(y_pred, y_target)
    l_coh = torch.relu(torch.tensor(min_coherence, device=c_score.device) - c_score).mean()
    total = lambda_latent * l_latent + lambda_obs * l_obs + lambda_coh * l_coh
    parts = {
        "latent": float(l_latent.detach()),
        "obs": float(l_obs.detach()),
        "coh": float(l_coh.detach()),
    }
    return total, parts


def probe_h_prod(T_matrix: torch.Tensor, label: str = "") -> dict:
    """
    Empirical H_prod probe: does T^3 have the structure required by factorization?

    H_prod requires: P(X^(0), X^(1), X^(2)) = prod_j P(X^(j))
    where X^(j) = 1 if a walk starting in channel j returns to channel j after 3 steps.

    The minimal necessary condition (from h_prod_markovian_walk_proof.md §5) is that
    T^3 is diagonal. This is NOT sufficient for H_prod (zero covariance ≠ independence),
    but it is necessary. A non-diagonal T^3 immediately kills the one-hot factorization.

    We also compute the mutual information I(channel; 3-step outcome) numerically,
    which the Fisher/trajectory analysis showed equals I(C; X_1) — no extra leverage
    beyond first-step position for the absolute-label observable.
    """
    T3 = T_matrix @ T_matrix @ T_matrix
    T3_d = T3.detach()

    # Diagonal elements: return probabilities per channel
    diag = T3_d.diag()

    # Off-diagonal norm: how far T^3 is from diagonal
    off_diag_sq = T3_d.pow(2).sum() - diag.pow(2).sum()
    off_diag_norm = float(off_diag_sq.clamp_min(0).sqrt())
    frobenius = float(T3_d.pow(2).sum().sqrt())

    # Mutual information I(channel j; 3-step outcome k) under uniform prior
    # P(j, k) = (1/3) * T3[j, k]
    p_joint = T3_d / 3.0                              # shape [3, 3]
    p_j = p_joint.sum(dim=1, keepdim=True)            # marginal over starting channel
    p_k = p_joint.sum(dim=0, keepdim=True)            # marginal over ending channel
    eps = 1e-15
    mi = float(
        (p_joint * (p_joint / (p_j * p_k + eps) + eps).log()).sum().item() / math.log(2)
    )

    # KL: D_KL(P_joint || P_product) — quantifies factorization failure
    p_prod = p_j * p_k
    kl = float(
        (p_joint * ((p_joint + eps) / (p_prod + eps)).log()).sum().item() / math.log(2)
    )

    # Diagonal dominance ratio: are diagonal entries > off-diagonal average?
    off_diag_mean = float((T3_d - T3_d.diag().diag()).abs().mean())
    diag_mean = float(diag.mean())

    result = {
        "label": label,
        "T3_diag": [round(float(x), 6) for x in diag],
        "off_diag_norm": round(off_diag_norm, 8),
        "frobenius": round(frobenius, 6),
        "off_diag_fraction": round(off_diag_norm / (frobenius + 1e-12), 6),
        "MI_bits": round(mi, 6),
        "KL_product_bits": round(kl, 6),
        "diag_mean": round(diag_mean, 6),
        "off_diag_mean": round(off_diag_mean, 6),
        "T3_diagonal": off_diag_norm < 1e-8,
    }

    tag = "DIAGONAL (H_prod necessary condition met)" if result["T3_diagonal"] else "NON-DIAGONAL"
    print(f"\n{'='*60}")
    print(f" H_PROD PROBE: {label}")
    print(f"{'='*60}")
    print(f"  T^3 structure:      {tag}")
    print(f"  T^3 diagonal:       {result['T3_diag']}")
    print(f"  Off-diag norm:      {off_diag_norm:.4e}")
    print(f"  Off-diag fraction:  {result['off_diag_fraction']:.4f}")
    print(f"  MI(channel; end):   {mi:.4f} bits")
    print(f"  KL(joint||product): {kl:.4f} bits  [0 = factorized]")
    print(f"  Diagonal dominant:  {diag_mean:.4f}  vs off-diag avg {off_diag_mean:.4f}")
    if not result["T3_diagonal"]:
        print(f"\n  >> H_prod FAILS the necessary diagonal condition for this T.")
        print(f"     One-hot channel factorization is broken by off-diagonal mixing.")
    return result


def run_h_prod_survey() -> None:
    """
    Survey H_prod across four physically relevant teacher walks.
    Maps directly onto the 'parameter sets' from fisher_3step_numerical.md.
    """
    print("\n" + "=" * 60)
    print(" H_PROD SURVEY — FOUR TEACHER WALKS")
    print("=" * 60)
    configs = [
        ("uniform",           1/3, 1/3, 1/3),
        ("symmetric_biased",  0.6, 0.2, 0.2),
        ("directed_weak",     0.5, 0.3, 0.2),
        ("directed_strong",   0.5, 0.4, 0.1),
    ]
    results = []
    for label, t0, t1, t2 in configs:
        T = build_teacher_transition(stay=t0, forward=t1, backward=t2)
        r = probe_h_prod(T, label=f"{label} (t0={t0:.2f}, t1={t1:.2f}, t2={t2:.2f})")
        results.append(r)

    print("\n\nSUMMARY TABLE")
    print(f"{'Label':<26} {'T^3 diag?':<12} {'KL(bits)':<12} {'MI(bits)':<12}")
    print("-" * 62)
    for r in results:
        diag_str = "YES" if r["T3_diagonal"] else "NO"
        print(f"{r['label'][:25]:<26} {diag_str:<12} {r['KL_product_bits']:<12.4f} {r['MI_bits']:<12.4f}")

    print("\nNote: T^3 diagonal is a necessary but not sufficient condition for H_prod.")
    print("KL(joint||product) = 0 iff factorization holds exactly.")
    print("Route audit (h_prod_model_routes_audit): even diagonal T^3 does not close H_prod")
    print("because the closure events X^(j) still require an explicit joint probability model.")


def run_toy_training() -> None:
    print("=======================================================")
    print(" PF TOY WORLD MODEL — PHASE 1 SCAFFOLD")
    print("=======================================================\n")
    print("Training on synthetic Z3 trajectories from a teacher walk.")
    print("This pressure-tests the architecture; it does not derive PF claims.\n")

    torch.manual_seed(42)

    model = PFToyWorldModel(obs_dim=2)
    optimizer = optim.Adam(model.parameters(), lr=0.03)

    # Teacher: physical symmetric nearest-neighbor closure operator T_sym.
    teacher_T = build_teacher_transition(stay=0.0, forward=0.5, backward=0.5)
    teacher_proj = torch.tensor(
        [
            [1.0, -0.5, 0.0],
            [0.0, 0.75, -1.0],
        ]
    )

    batch_size = 64
    unroll_steps = 8
    epochs = 80

    print("Teacher transition weights: stay=0.0, forward=0.5, backward=0.5")
    print("Learning row-stochastic circulant dynamics + observation head...\n")

    for epoch in range(epochs + 1):
        optimizer.zero_grad()
        x_true = dirichlet_simplex(batch_size=batch_size, dim=3, alpha=1.0)
        x_model = x_true.clone()

        total_loss = 0.0
        running = {"latent": 0.0, "obs": 0.0, "coh": 0.0}

        for _ in range(unroll_steps):
            # Teacher dynamics for synthetic supervision.
            x_true_next = torch.matmul(x_true, teacher_T.T)
            y_target = torch.matmul(x_true_next, teacher_proj.T)

            # Model prediction from the same current latent.
            x_pred, c_score, y_pred, probs = model(x_model)
            loss, parts = loss_function(x_pred, x_true_next, y_pred, y_target, c_score)
            total_loss = total_loss + loss

            for key, value in parts.items():
                running[key] += value

            # Teacher forcing on the latent trajectory keeps the task identifiable.
            x_true = x_true_next
            x_model = x_true_next.detach()

        total_loss.backward()
        optimizer.step()

        if epoch % 10 == 0:
            T_learned, probs = model.transition_matrix()
            print(
                f"Epoch {epoch:02d} | loss={total_loss.item():.6f} | "
                f"latent={running['latent'] / unroll_steps:.6f} | "
                f"obs={running['obs'] / unroll_steps:.6f} | "
                f"coh={running['coh'] / unroll_steps:.6f}"
            )
            print(
                "  learned probs: "
                f"stay={probs[0].item():.4f}, "
                f"forward={probs[1].item():.4f}, "
                f"backward={probs[2].item():.4f}"
            )
            print(f"  learned T:\n{T_learned.detach().numpy()}\n")

    print("Training complete.")
    print("Use this to pressure-test latent dynamics, observation mapping, and")
    print("candidate stability metrics before claiming any PF selector closure.")


if __name__ == "__main__":
    run_h_prod_survey()
    run_toy_training()
