"""
Counterexample search for the Family C no-go theorem.

Task: Try to build a real operator-native counterexample to the canonical
Family C no-go without using channel projectors or a basis split in the
degenerate Q sector.

The no-go claims: every real symmetric matrix built from canonical operator
data {I, S_bar, S_bar^2, T_sym, T_sym^2, T_sym^3, P0, Q} lies in
span{P0, Q} = span{I, M}, hence commutes with S_bar, hence any
C3-covariant triple collapses to K0 = K1 = K2.

This script:
1. Enumerates the real symmetric canonical algebra and confirms it is 2D
2. Tests the K_{r+1} = S K_r S^T collapse
3. Tries every candidate construction the author could think of
4. Reports verdict
"""

import numpy as np
from itertools import product as iterproduct

# Tolerance for numerical checks
TOL = 1e-12

# ============================================================
# 1. Core operator definitions
# ============================================================

S_bar = np.array([
    [0, 0, 1],
    [1, 0, 0],
    [0, 1, 0]
], dtype=float)

S_bar_sq = S_bar @ S_bar  # = S_bar^2

I3 = np.eye(3)

T_sym = 0.5 * (S_bar + S_bar_sq)

M = S_bar + S_bar_sq  # coupling matrix

P0 = np.ones((3, 3)) / 3.0
Q = I3 - P0

# Verify basics
assert np.allclose(S_bar @ S_bar @ S_bar, I3), "S_bar^3 != I"
assert np.allclose(T_sym, 0.5 * M), "T_sym != 0.5 * M"
assert np.allclose(P0 @ P0, P0), "P0 not idempotent"
assert np.allclose(Q @ Q, Q), "Q not idempotent"
assert np.allclose(P0 @ Q, np.zeros((3,3))), "P0 Q != 0"
assert np.allclose(P0 + Q, I3), "P0 + Q != I"

print("=== Core operator checks passed ===")
print()

# ============================================================
# 2. Enumerate the real symmetric canonical algebra
# ============================================================

# The canonical operator data set is:
# {I, S_bar, S_bar^2, T_sym, T_sym^2, T_sym^3, P0, Q}
# Plus any polynomial combinations thereof.

# First: list all generators
generators = {
    'I': I3,
    'S_bar': S_bar,
    'S_bar_sq': S_bar_sq,
    'T_sym': T_sym,
    'T_sym_sq': np.linalg.matrix_power(T_sym, 2),
    'T_sym_cu': np.linalg.matrix_power(T_sym, 3),
    'P0': P0,
    'Q': Q,
    'M': M,
}

# The full algebra generated by S_bar over R is span{I, S_bar, S_bar^2}
# since S_bar^3 = I. This is 3-dimensional.
# The REAL SYMMETRIC subspace consists of matrices A with A = A^T.

print("=== Symmetry check of generators ===")
for name, mat in generators.items():
    is_sym = np.allclose(mat, mat.T)
    print(f"  {name:12s}: symmetric = {is_sym}")
print()

# Collect all symmetric generators
sym_generators = {}
for name, mat in generators.items():
    if np.allclose(mat, mat.T):
        sym_generators[name] = mat

print(f"Symmetric generators: {list(sym_generators.keys())}")
print()

# Now check: what is the dimension of span of all symmetric generators?
# Vectorize each 3x3 symmetric matrix into its 6 independent entries
def sym_vec(A):
    """Extract upper triangle of symmetric matrix as 6-vector."""
    return np.array([A[0,0], A[0,1], A[0,2], A[1,1], A[1,2], A[2,2]])

sym_vecs = []
sym_names = []
for name, mat in sym_generators.items():
    sym_vecs.append(sym_vec(mat))
    sym_names.append(name)

sym_matrix = np.array(sym_vecs)  # shape (n_generators, 6)
rank = np.linalg.matrix_rank(sym_matrix, tol=TOL)

print(f"Number of symmetric generators: {len(sym_vecs)}")
print(f"Rank of symmetric generator matrix: {rank}")
print(f"=> Real symmetric canonical algebra is {rank}-dimensional")
print()

# Verify it's exactly span{P0, Q} = span{I, M}
basis_vecs = np.array([sym_vec(P0), sym_vec(Q)])
basis_rank = np.linalg.matrix_rank(basis_vecs, tol=TOL)
print(f"Rank of {{P0, Q}} basis: {basis_rank}")

# Check that every symmetric generator lies in span{P0, Q}
combined = np.vstack([basis_vecs, sym_matrix])
combined_rank = np.linalg.matrix_rank(combined, tol=TOL)
print(f"Rank of {{P0, Q}} + all symmetric generators: {combined_rank}")
if combined_rank == basis_rank:
    print("=> CONFIRMED: all symmetric generators lie in span{P0, Q}")
else:
    print("=> WARNING: some symmetric generator is NOT in span{P0, Q}!")
print()

# ============================================================
# 3. Products and higher constructions
# ============================================================

print("=== Testing products of canonical operators ===")

# Generate all pairwise products and check if any new symmetric matrix appears
all_ops = [I3, S_bar, S_bar_sq, T_sym, 
           np.linalg.matrix_power(T_sym, 2),
           np.linalg.matrix_power(T_sym, 3),
           P0, Q, M]
op_names = ['I', 'S', 'S^2', 'T', 'T^2', 'T^3', 'P0', 'Q', 'M']

new_symmetric = []
for i, (A, nA) in enumerate(zip(all_ops, op_names)):
    for j, (B, nB) in enumerate(zip(all_ops, op_names)):
        AB = A @ B
        if np.allclose(AB, AB.T):
            v = sym_vec(AB)
            test = np.vstack([basis_vecs, [v]])
            if np.linalg.matrix_rank(test, tol=TOL) > basis_rank:
                new_symmetric.append(f"{nA} @ {nB}")
                print(f"  NEW symmetric product outside span{{P0,Q}}: {nA} @ {nB}")

        # Also test symmetrized product (AB + BA)/2
        sym_prod = 0.5 * (AB + AB.T)
        v = sym_vec(sym_prod)
        test = np.vstack([basis_vecs, [v]])
        if np.linalg.matrix_rank(test, tol=TOL) > basis_rank:
            new_symmetric.append(f"sym({nA} @ {nB})")
            print(f"  NEW symmetrized product outside span{{P0,Q}}: sym({nA} @ {nB})")

if not new_symmetric:
    print("  No new symmetric matrices found from pairwise products.")
print()

# ============================================================
# 4. Antisymmetric part and derived constructions
# ============================================================

print("=== Testing antisymmetric-derived constructions ===")

A_anti = S_bar - S_bar_sq  # antisymmetric part of S_bar
assert np.allclose(A_anti, -A_anti.T), "A_anti not antisymmetric"

# A^2 should be symmetric
A_sq = A_anti @ A_anti
assert np.allclose(A_sq, A_sq.T), "A^2 not symmetric"
v = sym_vec(A_sq)
test = np.vstack([basis_vecs, [v]])
r = np.linalg.matrix_rank(test, tol=TOL)
print(f"  A^2 = (S-S^2)^2: in span{{P0,Q}}? {r == basis_rank}")
# Verify: A^2 = M - 2I
assert np.allclose(A_sq, M - 2*I3), "A^2 != M - 2I"
print(f"  Confirmed: A^2 = M - 2I (in span{{I, M}})")

# A B A for B in span{P0, Q}
for name, B in [('P0', P0), ('Q', Q), ('I', I3), ('M', M)]:
    ABA = A_anti @ B @ A_anti
    assert np.allclose(ABA, ABA.T), f"ABA not symmetric for B={name}"
    v = sym_vec(ABA)
    test = np.vstack([basis_vecs, [v]])
    r = np.linalg.matrix_rank(test, tol=TOL)
    print(f"  A @ {name} @ A: in span{{P0,Q}}? {r == basis_rank}")
print()

# ============================================================
# 5. Conjugation by S_bar
# ============================================================

print("=== Testing S_bar conjugation on span{P0, Q} ===")

for name, K in [('P0', P0), ('Q', Q), ('I', I3), ('M', M), ('T_sym', T_sym)]:
    conj = S_bar @ K @ S_bar.T
    diff = np.max(np.abs(conj - K))
    print(f"  S @ {name:5s} @ S^T - {name:5s} = {diff:.2e}  (commutes: {diff < TOL})")
print()

# ============================================================
# 6. The collapse theorem: K_{r+1} = S K_r S^T => K0=K1=K2
# ============================================================

print("=== Collapse theorem verification ===")

# For any K in span{P0, Q}, show S K S^T = K
# This means K_{r+1} = S K_r S^T = K_r for all r
# Hence K0 = K1 = K2

# Test with general element a*P0 + b*Q
for a, b in [(1.0, 0.0), (0.0, 1.0), (0.5, 0.3), (-1.0, 2.7), (np.pi, np.e)]:
    K = a * P0 + b * Q
    K_conj = S_bar @ K @ S_bar.T
    diff = np.max(np.abs(K_conj - K))
    assert diff < TOL, f"Collapse fails for a={a}, b={b}"

print("  For all tested a*P0 + b*Q: S @ K @ S^T = K  (collapse confirmed)")
print()

# ============================================================
# 7. Candidate counterexample attempts
# ============================================================

print("=== Candidate counterexample attempts ===")
print()

# Attempt 1: Use matrix functions of T_sym
print("Attempt 1: Matrix functions of T_sym")
# T_sym has eigenvalues 1 and -1/2 (degenerate)
# Any function f(T_sym) = f(1)*P0 + f(-1/2)*Q
# Still in span{P0, Q}
evals_T = np.linalg.eigvalsh(T_sym)
print(f"  T_sym eigenvalues: {sorted(evals_T)}")
print(f"  Any f(T_sym) = f(1)*P0 + f(-1/2)*Q => still in span{{P0,Q}}")
print(f"  VERDICT: No escape")
print()

# Attempt 2: Commutator-based constructions
print("Attempt 2: Commutator [S_bar, X] for various X")
for name, X in generators.items():
    comm = S_bar @ X - X @ S_bar
    is_zero = np.allclose(comm, np.zeros((3,3)))
    if not is_zero:
        is_sym = np.allclose(comm, comm.T)
        print(f"  [S_bar, {name}]: zero={is_zero}, symmetric={is_sym}")
        if is_sym:
            v = sym_vec(comm)
            test = np.vstack([basis_vecs, [v]])
            r = np.linalg.matrix_rank(test, tol=TOL)
            print(f"    In span{{P0,Q}}? {r == basis_rank}")
    else:
        print(f"  [S_bar, {name}]: zero (commutes)")
print()

# Attempt 3: Hadamard (entrywise) products
print("Attempt 3: Hadamard products of canonical symmetric matrices")
sym_mats = [('P0', P0), ('Q', Q), ('I', I3), ('M', M), ('T_sym', T_sym)]
for i, (nA, A) in enumerate(sym_mats):
    for j, (nB, B) in enumerate(sym_mats):
        if j >= i:
            H = A * B  # Hadamard product
            if np.allclose(H, H.T):
                v = sym_vec(H)
                test = np.vstack([basis_vecs, [v]])
                r = np.linalg.matrix_rank(test, tol=TOL)
                if r > basis_rank:
                    print(f"  {nA} ⊙ {nB}: NEW! Outside span{{P0,Q}}")
                else:
                    pass  # still in span
print("  All Hadamard products of canonical symmetric matrices stay in span{P0,Q}")
print()

# Attempt 4: Kronecker/tensor constructions (would leave R^3)
print("Attempt 4: Kronecker constructions")
print("  These leave R^3 and go to R^9 — changes the observable model")
print("  Not admissible under the single-medium quadratic observable spec")
print("  VERDICT: Not applicable")
print()

# Attempt 5: Square root of T_sym
print("Attempt 5: Matrix square root of |T_sym|")
# |T_sym| has eigenvalues 1 and 1/2
abs_T = 1.0 * P0 + 0.5 * Q
sqrt_abs_T = 1.0 * P0 + np.sqrt(0.5) * Q
print(f"  sqrt(|T_sym|) = 1*P0 + sqrt(1/2)*Q => in span{{P0,Q}}")
print(f"  VERDICT: No escape")
print()

# Attempt 6: Try to use the ASYMMETRIC S_bar to define K_r = S^r B (S^T)^r
print("Attempt 6: K_r = S^r B (S^T)^r for symmetric B")
B_test = 0.3 * P0 + 0.7 * Q  # arbitrary symmetric B in span{P0,Q}
for r in range(3):
    Sr = np.linalg.matrix_power(S_bar, r)
    K_r = Sr @ B_test @ Sr.T
    diff = np.max(np.abs(K_r - B_test))
    print(f"  r={r}: ||K_r - B|| = {diff:.2e}")
print("  All collapse to B (since B commutes with S_bar)")
print("  VERDICT: No escape")
print()

# Attempt 7: Use a NON-symmetric B and symmetrize
print("Attempt 7: K_r = sym(S^r B (S^T)^r) for non-symmetric B")
# If B is NOT in the canonical algebra, this is a basis choice
# If B IS in the canonical algebra but not symmetric...
# The non-symmetric elements of the S_bar algebra are:
# span{I, S_bar, S_bar^2} minus span{I, M}
# = elements with unequal S_bar and S_bar^2 coefficients
# Example: S_bar itself, or S_bar - S_bar^2

B_nonsym = S_bar  # a canonical but non-symmetric operator
for r in range(3):
    Sr = np.linalg.matrix_power(S_bar, r)
    raw = Sr @ B_nonsym @ Sr.T
    K_r = 0.5 * (raw + raw.T)  # symmetrize
    print(f"  r={r}: K_r =")
    print(f"    {K_r}")
    v = sym_vec(K_r)
    test = np.vstack([basis_vecs, [v]])
    rank_test = np.linalg.matrix_rank(test, tol=TOL)
    print(f"    In span{{P0,Q}}? {rank_test == basis_rank}")

# Check if K_0 = K_1 = K_2
K_list = []
for r in range(3):
    Sr = np.linalg.matrix_power(S_bar, r)
    raw = Sr @ B_nonsym @ Sr.T
    K_list.append(0.5 * (raw + raw.T))

all_equal = all(np.allclose(K_list[0], K_list[r]) for r in range(3))
print(f"  K_0 = K_1 = K_2? {all_equal}")
if not all_equal:
    print("  *** POTENTIAL COUNTEREXAMPLE! ***")
    # But check: are these in span{P0, Q}?
    for r in range(3):
        v = sym_vec(K_list[r])
        test = np.vstack([basis_vecs, [v]])
        rank_test = np.linalg.matrix_rank(test, tol=TOL)
        print(f"  K_{r} in span{{P0,Q}}? {rank_test == basis_rank}")
print()

# Attempt 8: Use S_bar^2 as the non-symmetric seed
print("Attempt 8: K_r = sym(S^r S^2 (S^T)^r)")
B_nonsym2 = S_bar_sq
K_list2 = []
for r in range(3):
    Sr = np.linalg.matrix_power(S_bar, r)
    raw = Sr @ B_nonsym2 @ Sr.T
    K_list2.append(0.5 * (raw + raw.T))

all_equal2 = all(np.allclose(K_list2[0], K_list2[r]) for r in range(3))
print(f"  K_0 = K_1 = K_2? {all_equal2}")
if not all_equal2:
    print("  *** POTENTIAL COUNTEREXAMPLE! ***")
print()

# Attempt 9: Direct enumeration of ALL 3x3 real symmetric C3-circulant matrices
print("Attempt 9: Enumerate all C3-circulant real symmetric matrices")
print("  A C3-circulant symmetric matrix has form: diag=a, off-diag=b")
print("  i.e., a*I + b*(M) = a*I + b*(S+S^2)")
print("  This is exactly span{I, M} = span{P0, Q}")
print("  VERDICT: The C3-circulant symmetric matrices ARE span{P0, Q}")
print()

# ============================================================
# 8. The deeper question: can we escape using non-polynomial
#    but still "operator-native" constructions?
# ============================================================

print("=== Deeper analysis: non-polynomial operator constructions ===")
print()

# The algebra generated by S_bar is C[S_bar]/(S_bar^3 - I)
# As a real algebra: R[S_bar]/(S_bar^3 - I) = span_R{I, S_bar, S_bar^2}
# This is 3-dimensional over R.
# Its real symmetric subspace is 2-dimensional: span{I, M}.

# Any "operator-native" construction that:
# (a) starts from S_bar (or equivalently T_sym = (1/2)(S_bar + S_bar^2))
# (b) uses only real algebra operations (addition, scalar mult, matrix mult)
# (c) possibly uses matrix functions (exp, sqrt, log, etc.)
# (d) requires the result to be real symmetric
#
# will land in span{P0, Q} because:
# - matrix functions of T_sym are functions of its eigenvalues applied to
#   its eigenprojectors, which are P0 and Q
# - products of elements of the algebra stay in the algebra
# - the symmetric subspace of the algebra is span{P0, Q}

print("The real symmetric canonical operator algebra is EXACTLY 2-dimensional.")
print("It equals span{P0, Q} = span{I, M}.")
print()
print("Every element commutes with S_bar.")
print("Therefore every C3-covariant triple K_{r+1} = S K_r S^T collapses to K0=K1=K2.")
print()
print("No operator-native counterexample exists.")
print()

# ============================================================
# 9. Final verification: the only escape is a basis choice
# ============================================================

print("=== The only escape: explicit basis choice in Q-sector ===")
print()

# Q is a rank-2 projector onto the degenerate eigenspace of T_sym.
# To get three DISTINCT symmetric kernels, one must split Q into
# one-dimensional projectors. But Q's eigenspace is 2D with no
# canonical basis — any split requires choosing a direction.

# Example of a basis-fixed split (NOT operator-native):
# Pick the standard basis e0, e1, e2 and define channel projectors
# P_j = |e_j><e_j| - P0  (projected into Q-sector)
# These are NOT in span{P0, Q} — they require the channel basis.

e0 = np.array([1, 0, 0])
e1 = np.array([0, 1, 0])
e2 = np.array([0, 0, 1])

# Channel projectors in Q-sector
Q_proj = []
for ej in [e0, e1, e2]:
    proj = Q @ np.outer(ej, ej) @ Q
    Q_proj.append(proj)
    v = sym_vec(proj)
    test = np.vstack([basis_vecs, [v]])
    r = np.linalg.matrix_rank(test, tol=TOL)
    in_span = (r == basis_rank)
    print(f"  Q|e><e|Q for e={ej}: in span{{P0,Q}}? {in_span}")

print()
print("  These channel-projected kernels are NOT in span{P0, Q}.")
print("  They require the standard basis — an extra hypothesis.")
print("  This is the noncanonical basis-fixed route that the no-go leaves open.")
print()

# ============================================================
# 10. Summary
# ============================================================

print("=" * 60)
print("VERDICT: NO COUNTEREXAMPLE FOUND")
print("=" * 60)
print()
print("The Family C no-go survives the counterexample search.")
print()
print("Reason: The real symmetric canonical operator algebra of the")
print("actual Z3 closure route is exactly span{P0, Q}, which is")
print("2-dimensional and fully C3-invariant. Every element commutes")
print("with S_bar, so any C3-covariant triple collapses to K0=K1=K2.")
print()
print("No operator-native construction (polynomial, matrix function,")
print("product, commutator, anticommutator, Hadamard product, or")
print("conjugation) escapes this 2D subspace.")
print()
print("The only escape requires an explicit basis choice inside the")
print("degenerate Q-sector, which is a noncanonical extra hypothesis.")
