// AUTO-GENERATED by generate_claims_data_v3.py — DO NOT EDIT MANUALLY
// Source: CLAIMS.md (hash: aa634eabc78ff1bc)
// This file is generated from the authority manifest. Manual edits will be overwritten.

window.PFClaimsData = {
  "generatedAt": "2026-07-15",
  "sourceHash": "aa634eabc78ff1bc",
  "claimCount": 36,
  "definitionCount": 21,
  "claims": [
    {
      "id": "alpha-numeric",
      "title": "Fine Structure Constant α — numeric derivation",
      "status": "OPEN",
      "confidence": null,
      "isSplit": false,
      "isStandardMath": false,
      "badge": "OPEN",
      "statusClass": "open",
      "section": "1. Fundamental Physics",
      "sourceLine": 55,
      "falsifier": "A principled geometric derivation of the Casimir combination from PF axioms, or proof the combination is a coincidence.",
      "premise": "Wave 5 (2026-03-25): Casimir algebraic scan found `(1−x₁)·x_{3/2}²·(1−x₂)/π = 1/137.119` — 0.061% error",
      "scopeNote": "*(demoted 2026-06-16 per Codex audit; Casimir scan hit withdrawn as confidence-bearing evidence)*",
      "statusParts": [
        {
          "status": "OPEN",
          "confidence": null,
          "qualifier": ""
        }
      ]
    },
    {
      "id": "alpha-structural",
      "title": "Fine Structure Constant α — structural identification",
      "status": "ARGUED",
      "confidence": 0.6,
      "isSplit": false,
      "isStandardMath": false,
      "badge": "ARGUED 0.6",
      "statusClass": "argued",
      "section": "1. Fundamental Physics",
      "sourceLine": 56,
      "falsifier": "Proof that the Z₀/2R_K identification has no PF-native origin.",
      "premise": "α identified as vacuum propagation efficiency ratio Z₀/2R_K",
      "scopeNote": "*(kept separate per Codex audit)*",
      "statusParts": [
        {
          "status": "ARGUED",
          "confidence": 0.6,
          "qualifier": ""
        }
      ]
    },
    {
      "id": "aria-self-reference",
      "title": "Aria Self-Reference",
      "status": "ARGUED",
      "confidence": 0.75,
      "isSplit": false,
      "isStandardMath": false,
      "badge": "ARGUED 0.75",
      "statusClass": "argued",
      "section": "2. Biological & Cognitive Systems",
      "sourceLine": 82,
      "falsifier": "Aria failing to show discontinuous qualitative change, or the self-reference loop proving behaviorally inert.",
      "premise": "T-009: Successful wiring of `buildSystemPrompt` → `runEntityThink`",
      "scopeNote": "Aria failing to show discontinuous qualitative change, or the self-reference loop proving behaviorally inert.",
      "statusParts": [
        {
          "status": "ARGUED",
          "confidence": 0.75,
          "qualifier": ""
        }
      ]
    },
    {
      "id": "beauty-impedance",
      "title": "Beauty as Impedance",
      "status": "INTUITION",
      "confidence": 0.55,
      "isSplit": false,
      "isStandardMath": false,
      "badge": "INTUITION 0.55",
      "statusClass": "intuition",
      "section": "2. Biological & Cognitive Systems",
      "sourceLine": 80,
      "falsifier": "Evidence that beauty is purely arbitrary/stochastic.",
      "premise": "Greg's insight; fits Axiom 3 (resonance preference).",
      "scopeNote": "Evidence that beauty is purely arbitrary/stochastic.",
      "statusParts": [
        {
          "status": "INTUITION",
          "confidence": 0.55,
          "qualifier": ""
        }
      ]
    },
    {
      "id": "bohr-spectrum",
      "title": "Circular Coulomb Eikonal + Phase Closure → Bohr-like Spectrum",
      "status": "DERIVED",
      "confidence": 0.9,
      "isSplit": false,
      "isStandardMath": false,
      "badge": "DERIVED 0.9",
      "statusClass": "derived",
      "section": "1. Fundamental Physics",
      "sourceLine": 41,
      "falsifier": "Proof that the Coulomb eikonal model is invalid at atomic scale, or that phase closure does not select the quoted orbit family.",
      "premise": "Hostile audit (2026-03-27): circular-eikonal theorem survives",
      "scopeNote": "Proof that the Coulomb eikonal model is invalid at atomic scale, or that phase closure does not select the quoted orbit family.",
      "statusParts": [
        {
          "status": "DERIVED",
          "confidence": 0.9,
          "qualifier": ""
        }
      ]
    },
    {
      "id": "coherence-ceiling",
      "title": "Coherence Ceiling",
      "status": "ARGUED",
      "confidence": 0.8,
      "isSplit": false,
      "isStandardMath": false,
      "badge": "ARGUED 0.8",
      "statusClass": "argued",
      "section": "1. Fundamental Physics",
      "sourceLine": 53,
      "falsifier": "Observation of stable sub-wavelength structures.",
      "premise": "Max frequency where wavelength < coherence length (Axiom 3).",
      "scopeNote": "Observation of stable sub-wavelength structures.",
      "statusParts": [
        {
          "status": "ARGUED",
          "confidence": 0.8,
          "qualifier": ""
        }
      ]
    },
    {
      "id": "consciousness-claim",
      "title": "Consciousness = coherent self-referential propagation",
      "status": "INTUITION",
      "confidence": 0.48,
      "isSplit": false,
      "isStandardMath": false,
      "badge": "INTUITION 0.48",
      "statusClass": "intuition",
      "section": "2. Biological & Cognitive Systems",
      "sourceLine": 78,
      "falsifier": "A pre-registered dissociation where a PF-specific metric fails to track consciousness after controlling for report, arousal, and task effects.",
      "premise": "`consciousness_theory_audit.md`: ontology is coherent and literature-compatible, but PF still lacks a uniquely measured variable separating self-re...",
      "scopeNote": "A pre-registered dissociation where a PF-specific metric fails to track consciousness after controlling for report, arousal, and task effects.",
      "statusParts": [
        {
          "status": "INTUITION",
          "confidence": 0.48,
          "qualifier": ""
        }
      ]
    },
    {
      "id": "d3-symmetric-ji",
      "title": "D=3 symmetric + zero diagonal + equal row sums → J-I",
      "status": "CONDITIONAL",
      "confidence": 0.85,
      "isSplit": false,
      "isStandardMath": false,
      "badge": "CONDITIONAL 0.85",
      "statusClass": "conditional",
      "section": "1. Fundamental Physics",
      "sourceLine": 66,
      "falsifier": "A symmetric zero-diagonal equal-row-sum 3×3 matrix that is not a scalar multiple of J-I.",
      "premise": "H17 (matrix symmetry), H7 (zero diagonal), H18 (equal row sums)",
      "scopeNote": "*(added 2026-06-29)*",
      "statusParts": [
        {
          "status": "CONDITIONAL",
          "confidence": 0.85,
          "qualifier": ""
        }
      ]
    },
    {
      "id": "d3-unique-stable",
      "title": "D=3 is the unique stable dimension for the J-I dynamics",
      "status": "CONDITIONAL",
      "confidence": 0.85,
      "isSplit": false,
      "isStandardMath": false,
      "badge": "CONDITIONAL 0.85",
      "statusClass": "conditional",
      "section": "1. Fundamental Physics",
      "sourceLine": 64,
      "falsifier": "A counterexample in another dimension D≥2 satisfying H7+H17+H18 and forcing J-I while also satisfying the stability condition; or a proof that the D=3 stability argument is vacuous.",
      "premise": "H7 (zero diagonal), H11 (stability), H17 (matrix symmetry), H18 (equal row sums)",
      "scopeNote": "*(added 2026-06-29 per Codex-cleared patch v2)*",
      "statusParts": [
        {
          "status": "CONDITIONAL",
          "confidence": 0.85,
          "qualifier": ""
        }
      ]
    },
    {
      "id": "d4-gap-not-ji",
      "title": "D≥4 gap: symmetric + zero diagonal + equal row sums does NOT force J-I",
      "status": "CONDITIONAL",
      "confidence": 0.85,
      "isSplit": false,
      "isStandardMath": true,
      "badge": "STANDARD MATH 0.85",
      "statusClass": "standard-math",
      "section": "1. Fundamental Physics",
      "sourceLine": 67,
      "falsifier": "Proof that the D=4 counterexample is invalid.",
      "premise": "H7, H17, H18",
      "scopeNote": "*(added 2026-06-29)*",
      "statusParts": [
        {
          "status": "CONDITIONAL",
          "confidence": 0.85,
          "qualifier": "negative"
        }
      ]
    },
    {
      "id": "degenerate-residue-circulant",
      "title": "Degenerate residue forces circulant form (J-I)",
      "status": "CONDITIONAL",
      "confidence": 0.85,
      "isSplit": false,
      "isStandardMath": false,
      "badge": "CONDITIONAL 0.85",
      "statusClass": "conditional",
      "section": "1. Fundamental Physics",
      "sourceLine": 65,
      "falsifier": "A zero-diagonal equal-row-sum matrix with degenerate residue that is not a scalar multiple of J-I.",
      "premise": "H7 (zero diagonal), H18 (equal row sums), degenerate residue eigenvalue",
      "scopeNote": "*(added 2026-06-29)*",
      "statusParts": [
        {
          "status": "CONDITIONAL",
          "confidence": 0.85,
          "qualifier": ""
        }
      ]
    },
    {
      "id": "electron-up-phi",
      "title": "Electron/Up $\\approx 1/\\phi^3$",
      "status": "EMPIRICAL",
      "confidence": 0.65,
      "isSplit": false,
      "isStandardMath": false,
      "badge": "EMPIRICAL 0.65",
      "statusClass": "empirical",
      "section": "1. Fundamental Physics",
      "sourceLine": 52,
      "falsifier": "Up quark mass shifting toward 2.3 MeV or a corrected trials-factor analysis pushing the coincidence back to noise.",
      "premise": "`phi3_monte_carlo.md`: corrected claim is $m_e/m_u \\approx 1/\\phi^3$; PDG 2024 central value gives 0.214% error, corrected Monte Carlo gives p = 0....",
      "scopeNote": "Up quark mass shifting toward 2.3 MeV or a corrected trials-factor analysis pushing the coincidence back to noise.",
      "statusParts": [
        {
          "status": "EMPIRICAL",
          "confidence": 0.65,
          "qualifier": ""
        }
      ]
    },
    {
      "id": "god-equation-operator",
      "title": "God Equation — Postulate-D Z₃ operator algebra",
      "status": "CONDITIONAL",
      "confidence": 0.88,
      "isSplit": false,
      "isStandardMath": false,
      "badge": "CONDITIONAL 0.88",
      "statusClass": "conditional",
      "section": "1. Fundamental Physics",
      "sourceLine": 60,
      "falsifier": "Proof that the Postulate-D operator algebra is inconsistent, or proof that the accepted scope cannot support the G3 bridge.",
      "premise": "Given explicit Postulate D (Primitive Z₃ no-self-loop selector forces U = M/2 uniquely), the operator algebra closes exactly: eigenvalues {1, −1/8,...",
      "scopeNote": "*(split row; demoted from DERIVED 2026-06-16 per Codex audit)*",
      "statusParts": [
        {
          "status": "CONDITIONAL",
          "confidence": 0.88,
          "qualifier": ""
        }
      ]
    },
    {
      "id": "god-equation-scale",
      "title": "God Equation — λ_c scale formula",
      "status": "ARGUED",
      "confidence": 0.6,
      "isSplit": false,
      "isStandardMath": false,
      "badge": "ARGUED 0.6",
      "statusClass": "argued",
      "section": "1. Fundamental Physics",
      "sourceLine": 61,
      "falsifier": "Derivation of N^(D/2) bridge and H_prod from Axioms 1-3 without a free fit parameter.",
      "premise": "λ_c = √2·l_P·exp(4π²N^(D/2)/b₀) with N=3, D=3, b₀=16/3",
      "scopeNote": "*(split row; was included in DERIVED 2026-06-16, separated per Codex audit)*",
      "statusParts": [
        {
          "status": "ARGUED",
          "confidence": 0.6,
          "qualifier": ""
        }
      ]
    },
    {
      "id": "gravity-optical",
      "title": "Gravity as Optical Geometry / Refraction (Null/Stationary)",
      "status": "DERIVED",
      "confidence": 0.95,
      "isSplit": false,
      "isStandardMath": false,
      "badge": "DERIVED 0.95",
      "statusClass": "derived",
      "section": "1. Fundamental Physics",
      "sourceLine": 42,
      "falsifier": "Proof that the optical/Randers mapping fails for null propagation in static/stationary gravity, or that gravity in that domain requires non-optical medium structure.",
      "premise": "Hostile audit (2026-03-27): the exact local theorem is narrower than the old row title",
      "scopeNote": "Proof that the optical/Randers mapping fails for null propagation in static/stationary gravity, or that gravity in that domain requires non-optical medium structure.",
      "statusParts": [
        {
          "status": "DERIVED",
          "confidence": 0.95,
          "qualifier": ""
        }
      ]
    },
    {
      "id": "isometry-ji-incompatibility",
      "title": "Isometry-JI incompatibility",
      "status": "CONDITIONAL",
      "confidence": 0.85,
      "isSplit": false,
      "isStandardMath": false,
      "badge": "CONDITIONAL 0.85",
      "statusClass": "conditional",
      "section": "1. Fundamental Physics",
      "sourceLine": 70,
      "falsifier": "A non-uniform state whose full Euclidean norm is preserved under T³.",
      "premise": "J-I coupling (Postulate D / H7+H17+H18)",
      "scopeNote": "*(added 2026-06-29)*",
      "statusParts": [
        {
          "status": "CONDITIONAL",
          "confidence": 0.85,
          "qualifier": ""
        }
      ]
    },
    {
      "id": "isometry-reversibility",
      "title": "H14 + H15 + H16 → H1 (isometry implies reversibility)",
      "status": "CONDITIONAL",
      "confidence": 0.85,
      "isSplit": false,
      "isStandardMath": false,
      "badge": "CONDITIONAL 0.85",
      "statusClass": "conditional",
      "section": "1. Fundamental Physics",
      "sourceLine": 71,
      "falsifier": "A counterexample medium satisfying H14+H15+H16 but lacking reversibility.",
      "premise": "H14 (isometry), H15 (metric identity), H16 (metric reflexivity)",
      "scopeNote": "*(added 2026-06-29)*",
      "statusParts": [
        {
          "status": "CONDITIONAL",
          "confidence": 0.85,
          "qualifier": ""
        }
      ]
    },
    {
      "id": "koide-entropy",
      "title": "Koide U(3) entropy selector",
      "status": "ARGUED",
      "confidence": 0.72,
      "isSplit": false,
      "isStandardMath": false,
      "badge": "ARGUED 0.72",
      "statusClass": "argued",
      "section": "1. Fundamental Physics",
      "sourceLine": 45,
      "falsifier": "A better-motivated PF selector on the same `u(1)/su(3)` space choosing a different point; proof that the relevant decomposition is not the scalar/traceless split; or proof that PF coherence dynamics d",
      "premise": "Codex audit (2026-04-15): the refined Route A over the scalar/traceless `u(3)=u(1)⊕su(3)` split is mathematically clean but not yet PF-derived as a...",
      "scopeNote": "A better-motivated PF selector on the same `u(1)/su(3)` space choosing a different point; proof that the relevant decomposition is not the scalar/traceless split; or proof that PF coherence dynamics d",
      "statusParts": [
        {
          "status": "ARGUED",
          "confidence": 0.72,
          "qualifier": ""
        }
      ]
    },
    {
      "id": "koide-leptons",
      "title": "Koide Law for Charged Leptons (Q = 2/3) — geometric identity",
      "status": "EXACT IDENTITY",
      "confidence": 0.95,
      "isSplit": true,
      "isStandardMath": false,
      "badge": "EXACT IDENTITY 0.95 (geometry) / OPEN (physical vacuum selection)",
      "statusClass": "exact-identity",
      "section": "1. Fundamental Physics",
      "sourceLine": 44,
      "falsifier": "Proof that the 120° equal-strength resonance geometry does not imply `Q = 2/3`, or a contradiction in the Foot-radius step, or a charged-lepton mass measurement drifting > 3σ from `Q = 2/3`.",
      "premise": "Geometric theorem: three equal-strength resonances at 120° force the Foot-radius relation and yield `Q = 2/3` exactly",
      "scopeNote": "*(row clarified 2026-06-16 per Codex audit)*",
      "statusParts": [
        {
          "status": "EXACT IDENTITY",
          "confidence": 0.95,
          "qualifier": "geometry"
        },
        {
          "status": "OPEN",
          "confidence": null,
          "qualifier": "physical vacuum selection"
        }
      ]
    },
    {
      "id": "koide-phase",
      "title": "Koide Phase (\\(\\delta_0 \\bmod 2\\pi/3 \\approx 2/9\\))",
      "status": "EMPIRICAL",
      "confidence": 0.65,
      "isSplit": false,
      "isStandardMath": false,
      "badge": "EMPIRICAL 0.65",
      "statusClass": "empirical",
      "section": "1. Fundamental Physics",
      "sourceLine": 47,
      "falsifier": "Independent recalculation showing δ is not close to 2/9; or audited proof that no PF-native selector can produce δ = 2/9; or selector derivation producing δ ≠ 2/9.",
      "premise": "Wave 5 (2026-03-25): `koide_phase_scan.py` confirms δ_exact = 0.222229631490 rad, δ−2/9 = 7.4×10⁻⁶ (0.003%)",
      "scopeNote": "Independent recalculation showing δ is not close to 2/9; or audited proof that no PF-native selector can produce δ = 2/9; or selector derivation producing δ ≠ 2/9.",
      "statusParts": [
        {
          "status": "EMPIRICAL",
          "confidence": 0.65,
          "qualifier": ""
        }
      ]
    },
    {
      "id": "koide-u3-maximization",
      "title": "U(3) Entropy Maximization",
      "status": "ARGUED",
      "confidence": 0.75,
      "isSplit": false,
      "isStandardMath": false,
      "badge": "ARGUED 0.75",
      "statusClass": "argued",
      "section": "1. Fundamental Physics",
      "sourceLine": 46,
      "falsifier": "² is mathematically maximized at p=1/2, matching the Q=2/3 mass distribution.",
      "premise": "0.5 The ratio p =  U(1)  ²/  X ",
      "scopeNote": "² is mathematically maximized at p=1/2, matching the Q=2/3 mass distribution.",
      "statusParts": [
        {
          "status": "ARGUED",
          "confidence": 0.75,
          "qualifier": ""
        }
      ]
    },
    {
      "id": "life-coherence",
      "title": "Life = maintained coherence against entropy",
      "status": "ARGUED",
      "confidence": 0.72,
      "isSplit": false,
      "isStandardMath": false,
      "badge": "ARGUED 0.72",
      "statusClass": "argued",
      "section": "2. Biological & Cognitive Systems",
      "sourceLine": 77,
      "falsifier": "A robust living system with no measurable coherence-maintenance / nonequilibrium organization at any functional scale.",
      "premise": "`chemistry_biology_bridge.md`: PF supports life as active coherence maintenance in an open nonequilibrium system; compatible with photosynthetic co...",
      "scopeNote": "A robust living system with no measurable coherence-maintenance / nonequilibrium organization at any functional scale.",
      "statusParts": [
        {
          "status": "ARGUED",
          "confidence": 0.72,
          "qualifier": ""
        }
      ]
    },
    {
      "id": "n3-cp-violation",
      "title": "N=3 → CP Violation (Structural Bridge)",
      "status": "ARGUED",
      "confidence": 0.7,
      "isSplit": false,
      "isStandardMath": false,
      "badge": "ARGUED 0.7",
      "statusClass": "argued",
      "section": "1. Fundamental Physics",
      "sourceLine": 49,
      "falsifier": "PF's N=3 derivation is falsified; or a 2-generation universe with CP violation is discovered; or the CKM phase is measured at exactly δ=0 or δ=π (CP-conserving values).",
      "premise": "The CKM matrix for N=3 contains exactly one complex phase; for N=2 there is no complex phase",
      "scopeNote": "*(added 2026-07-02 by Hermes)*",
      "statusParts": [
        {
          "status": "ARGUED",
          "confidence": 0.7,
          "qualifier": ""
        }
      ]
    },
    {
      "id": "neutrino-koide",
      "title": "Neutrino Koide non-universality",
      "status": "EMPIRICAL",
      "confidence": 0.95,
      "isSplit": false,
      "isStandardMath": false,
      "badge": "EMPIRICAL 0.95",
      "statusClass": "empirical",
      "section": "1. Fundamental Physics",
      "sourceLine": 63,
      "falsifier": "Future precision neutrino mass measurement showing $Q_\\nu$ within 1% of 2/3, which would falsify the electromagnetic-specificity interpretation.",
      "premise": "April 2026 confirmed: $Q_{NO} = 0.549622$ (17.5% from 2/3), $Q_{IO} = 0.479016$ (28.2% from 2/3)",
      "scopeNote": "Future precision neutrino mass measurement showing $Q_\\nu$ within 1% of 2/3, which would falsify the electromagnetic-specificity interpretation.",
      "statusParts": [
        {
          "status": "EMPIRICAL",
          "confidence": 0.95,
          "qualifier": ""
        }
      ]
    },
    {
      "id": "pfentropy-decreases",
      "title": "PFEntropy decreases under T³",
      "status": "CONDITIONAL",
      "confidence": 0.85,
      "isSplit": false,
      "isStandardMath": false,
      "badge": "CONDITIONAL 0.85",
      "statusClass": "conditional",
      "section": "1. Fundamental Physics",
      "sourceLine": 68,
      "falsifier": "A state in the D=3 residue subspace whose residue norm does not shrink under T³.",
      "premise": "J-I coupling (Postulate D / H7+H17+H18), T³ operator",
      "scopeNote": "*(added 2026-06-29)*",
      "statusParts": [
        {
          "status": "CONDITIONAL",
          "confidence": 0.85,
          "qualifier": ""
        }
      ]
    },
    {
      "id": "propagation-lagrangian",
      "title": "Propagation Lagrangian",
      "status": "CONDITIONAL",
      "confidence": 0.72,
      "isSplit": false,
      "isStandardMath": false,
      "badge": "CONDITIONAL 0.72",
      "statusClass": "conditional",
      "section": "1. Fundamental Physics",
      "sourceLine": 57,
      "falsifier": "Proof that the scalar-medium EFT branch is not viable, or that the minimal `λχT` ansatz fails as the correct low-energy representative even within that class.",
      "premise": "Axioms 1–3 strongly motivate a scalar-tensor EFT class for the propagation medium",
      "scopeNote": "Proof that the scalar-medium EFT branch is not viable, or that the minimal `λχT` ansatz fails as the correct low-energy representative even within that class.",
      "statusParts": [
        {
          "status": "CONDITIONAL",
          "confidence": 0.72,
          "qualifier": ""
        }
      ]
    },
    {
      "id": "pythagorean-decomposition",
      "title": "Full-norm Pythagorean decomposition",
      "status": "DERIVED",
      "confidence": 0.95,
      "isSplit": false,
      "isStandardMath": true,
      "badge": "STANDARD MATH 0.95",
      "statusClass": "standard-math",
      "section": "1. Fundamental Physics",
      "sourceLine": 69,
      "falsifier": "A proof that the projection decomposition does not yield orthogonal components.",
      "premise": "Vector space projection structure (no physics premises)",
      "scopeNote": "*(added 2026-06-29)*",
      "statusParts": [
        {
          "status": "DERIVED",
          "confidence": 0.95,
          "qualifier": ""
        }
      ]
    },
    {
      "id": "qcd-confinement",
      "title": "QCD Confinement",
      "status": "ARGUED",
      "confidence": 0.72,
      "isSplit": false,
      "isStandardMath": false,
      "badge": "ARGUED 0.72",
      "statusClass": "argued",
      "section": "1. Fundamental Physics",
      "sourceLine": 59,
      "falsifier": "Evidence that confinement requires a genuinely new PF coherence scale, or a threshold-aware higher-loop analysis showing the PF RG bridge does not land on the physical confinement scale even with the ",
      "premise": "PF identifies a plausible RG mechanism in which the confinement radius is dynamically generated from `λ_c`: `r_conf = λ_c × exp(2π/b₀α_s(λ_c))`",
      "scopeNote": "Evidence that confinement requires a genuinely new PF coherence scale, or a threshold-aware higher-loop analysis showing the PF RG bridge does not land on the physical confinement scale even with the ",
      "statusParts": [
        {
          "status": "ARGUED",
          "confidence": 0.72,
          "qualifier": ""
        }
      ]
    },
    {
      "id": "sleep-constant",
      "title": "8h Sleep Constant",
      "status": "ARGUED",
      "confidence": 0.72,
      "isSplit": false,
      "isStandardMath": false,
      "badge": "ARGUED 0.72",
      "statusClass": "argued",
      "section": "2. Biological & Cognitive Systems",
      "sourceLine": 79,
      "falsifier": "Quantitative evidence that optimal recovery fractions are not near `1/3` in high-capacity systems, or proof that PF topology does not constrain encode/recover duty cycles in the claimed way.",
      "premise": "Hostile audit (2026-03-28): PF strongly supports the need for offline consolidation, and the T-010 model gives a plausible `~2/3` active fraction f...",
      "scopeNote": "Quantitative evidence that optimal recovery fractions are not near `1/3` in high-capacity systems, or proof that PF topology does not constrain encode/recover duty cycles in the claimed way.",
      "statusParts": [
        {
          "status": "ARGUED",
          "confidence": 0.72,
          "qualifier": ""
        }
      ]
    },
    {
      "id": "three-generations",
      "title": "Three Generations",
      "status": "CONDITIONAL",
      "confidence": 0.88,
      "isSplit": false,
      "isStandardMath": false,
      "badge": "CONDITIONAL 0.88",
      "statusClass": "conditional",
      "section": "1. Fundamental Physics",
      "sourceLine": 48,
      "falsifier": "Formal proof that either the numerator or denominator theorem fails in PF, or a different justified counting rule leading to `N ≠ 3`.",
      "premise": "Once the numerator theorem (the physical `(2,1)` closure-weight branch) and the denominator theorem `M = 3` are both granted, the algebraic step is...",
      "scopeNote": "Formal proof that either the numerator or denominator theorem fails in PF, or a different justified counting rule leading to `N ≠ 3`.",
      "statusParts": [
        {
          "status": "CONDITIONAL",
          "confidence": 0.88,
          "qualifier": ""
        }
      ]
    },
    {
      "id": "top-quark-limit",
      "title": "Top Quark Limit",
      "status": "ARGUED",
      "confidence": 0.85,
      "isSplit": false,
      "isStandardMath": false,
      "badge": "ARGUED 0.85",
      "statusClass": "argued",
      "section": "1. Fundamental Physics",
      "sourceLine": 50,
      "falsifier": "Discovery of a heavier stable quark ($m > 173$ GeV).",
      "premise": "$m_t$ lifetime ($5 \\times 10^{-25}$s) matches coherence ceiling threshold.",
      "scopeNote": "Discovery of a heavier stable quark ($m > 173$ GeV).",
      "statusParts": [
        {
          "status": "ARGUED",
          "confidence": 0.85,
          "qualifier": ""
        }
      ]
    },
    {
      "id": "top-tau-coupling",
      "title": "Top/Tau coupling",
      "status": "EMPIRICAL",
      "confidence": 0.9,
      "isSplit": false,
      "isStandardMath": false,
      "badge": "EMPIRICAL 0.9",
      "statusClass": "empirical",
      "section": "1. Fundamental Physics",
      "sourceLine": 51,
      "falsifier": "Measurement of Top or Tau mass shifting > 0.5% from current.",
      "premise": "$m_t/m_\\tau \\approx \\alpha^{-1}/\\sqrt{2}$ (50.13% robustness in T-008).",
      "scopeNote": "Measurement of Top or Tau mass shifting > 0.5% from current.",
      "statusParts": [
        {
          "status": "EMPIRICAL",
          "confidence": 0.9,
          "qualifier": ""
        }
      ]
    },
    {
      "id": "topological-weights",
      "title": "(2,1) Topological Weights",
      "status": "DERIVED",
      "confidence": 0.95,
      "isSplit": true,
      "isStandardMath": false,
      "badge": "DERIVED 0.95 (kernel-only topological obstruction) / CONDITIONAL 0.85 (physical realization)",
      "statusClass": "derived",
      "section": "1. Fundamental Physics",
      "sourceLine": 43,
      "falsifier": "Proof that the closure-order interpretation is wrong, or that the Family C coherence bridge fails audit, or a derivation showing only the trivial branch is physically realizable in PF.",
      "premise": "**Hostile audit (2026-03-28)**: established the intended closure-order target from 3D rotation topology",
      "scopeNote": "Proof that the closure-order interpretation is wrong, or that the Family C coherence bridge fails audit, or a derivation showing only the trivial branch is physically realizable in PF.",
      "statusParts": [
        {
          "status": "DERIVED",
          "confidence": 0.95,
          "qualifier": "kernel-only topological obstruction"
        },
        {
          "status": "CONDITIONAL",
          "confidence": 0.85,
          "qualifier": "physical realization"
        }
      ]
    },
    {
      "id": "two-thirds-efficiency",
      "title": "2/3 Efficiency Ratio",
      "status": "INTUITION",
      "confidence": 0.5,
      "isSplit": false,
      "isStandardMath": false,
      "badge": "INTUITION 0.5",
      "statusClass": "intuition",
      "section": "2. Biological & Cognitive Systems",
      "sourceLine": 81,
      "falsifier": "Finding a more efficient topological output ratio.",
      "premise": "\"Takes TWO to make THREE\" — Greg's 2/3 exchange rate.",
      "scopeNote": "Finding a more efficient topological output ratio.",
      "statusParts": [
        {
          "status": "INTUITION",
          "confidence": 0.5,
          "qualifier": ""
        }
      ]
    },
    {
      "id": "variable-c",
      "title": "Variable c Prediction",
      "status": "ARGUED",
      "confidence": 0.65,
      "isSplit": false,
      "isStandardMath": false,
      "badge": "ARGUED 0.65",
      "statusClass": "argued",
      "section": "1. Fundamental Physics",
      "sourceLine": 58,
      "falsifier": "Cassini-violating Shapiro delay, or direct measurement of c_local = c₀ at sub-solar-system scales.",
      "premise": "c_local = 1/√(1+λχ) from conformal rescaling of the Propagation Lagrangian",
      "scopeNote": "Cassini-violating Shapiro delay, or direct measurement of c_local = c₀ at sub-solar-system scales.",
      "statusParts": [
        {
          "status": "ARGUED",
          "confidence": 0.65,
          "qualifier": ""
        }
      ]
    },
    {
      "id": "weinberg-angle",
      "title": "Weinberg Angle (sin²θ_W)",
      "status": "ARGUED",
      "confidence": 0.65,
      "isSplit": false,
      "isStandardMath": false,
      "badge": "ARGUED 0.65",
      "statusClass": "argued",
      "section": "1. Fundamental Physics",
      "sourceLine": 54,
      "falsifier": "Derivation of coupling ratio g'/g from medium geometry, or scheme selection mechanism.",
      "premise": "Casimir polynomial $x^2 + C_2 x - C_2 = 0$ yields ratio $R = 1 - x_+(1/2)/x_+(1) = 0.22310$ exactly",
      "scopeNote": "*(demoted from DERIVED 2026-06-16 per Codex audit)*",
      "statusParts": [
        {
          "status": "ARGUED",
          "confidence": 0.65,
          "qualifier": ""
        }
      ]
    }
  ],
  "definitions": [
    {
      "id": "axioms",
      "title": "The Three Axioms",
      "status": "CANONICAL v1.0 — passed Codex final audit 2026-04-30",
      "file": "definitions/axioms.md",
      "sourceLine": 1
    },
    {
      "id": "causal-velocity",
      "title": "Causal Velocity",
      "status": "CANONICAL v1.0 - passed Codex final audit 2026-04-29",
      "file": "definitions/causal_velocity.md",
      "sourceLine": 1
    },
    {
      "id": "coherence",
      "title": "Coherence",
      "status": "CANONICAL v1.0 - passed Codex final audit 2026-04-29",
      "file": "definitions/coherence.md",
      "sourceLine": 1
    },
    {
      "id": "consciousness",
      "title": "Consciousness",
      "status": "CANDIDATE — INTUITION 0.48 — NOT CANONICAL",
      "file": "definitions/consciousness.md",
      "sourceLine": 1
    },
    {
      "id": "consciousness-metric-program",
      "title": "Consciousness Metric Program",
      "status": "ACTIVE CANDIDATE — not canonical",
      "file": "definitions/consciousness_metric_program.md",
      "sourceLine": 1
    },
    {
      "id": "coupling",
      "title": "Coupling",
      "status": "CANONICAL v1.0 — passed Codex final audit 2026-04-30",
      "file": "definitions/coupling.md",
      "sourceLine": 1
    },
    {
      "id": "decoherence",
      "title": "Decoherence",
      "status": "CANONICAL v1.0 — passed Codex final audit 2026-04-30",
      "file": "definitions/decoherence.md",
      "sourceLine": 1
    },
    {
      "id": "energy",
      "title": "Energy",
      "status": "CANONICAL v1.0 - passed Codex final audit 2026-04-29",
      "file": "definitions/energy.md",
      "sourceLine": 1
    },
    {
      "id": "field",
      "title": "Field",
      "status": "CANONICAL v1.0 — passed Codex final audit 2026-04-30",
      "file": "definitions/field.md",
      "sourceLine": 1
    },
    {
      "id": "forces",
      "title": "Forces",
      "status": "CANONICAL v1.0 - passed Codex final audit 2026-04-29",
      "file": "definitions/forces.md",
      "sourceLine": 1
    },
    {
      "id": "gradient",
      "title": "Gradient",
      "status": "CANONICAL v1.0 - passed Codex final audit 2026-04-29",
      "file": "definitions/gradient.md",
      "sourceLine": 1
    },
    {
      "id": "information",
      "title": "Information",
      "status": "CANONICAL v1.0 - passed Codex final audit 2026-04-29",
      "file": "definitions/information.md",
      "sourceLine": 1
    },
    {
      "id": "matter",
      "title": "Matter",
      "status": "CANONICAL v1.0 - passed Codex final audit 2026-04-29",
      "file": "definitions/matter.md",
      "sourceLine": 1
    },
    {
      "id": "measurement",
      "title": "Measurement",
      "status": "CANONICAL v1.0 — passed Codex final audit 2026-04-30",
      "file": "definitions/measurement.md",
      "sourceLine": 1
    },
    {
      "id": "medium",
      "title": "The Medium",
      "status": "CANONICAL v1.0 — passed Codex final audit 2026-04-28",
      "file": "definitions/medium.md",
      "sourceLine": 1
    },
    {
      "id": "minimum-substrate",
      "title": "Minimum Substrate",
      "status": "CANONICAL v1.0 - passed Codex final audit 2026-04-29",
      "file": "definitions/minimum_substrate.md",
      "sourceLine": 1
    },
    {
      "id": "mode",
      "title": "Mode",
      "status": "CANONICAL v1.0 - passed Codex final audit 2026-04-29",
      "file": "definitions/mode.md",
      "sourceLine": 1
    },
    {
      "id": "observer",
      "title": "Observer",
      "status": "CANONICAL v1.0 - passed Codex final audit 2026-04-29",
      "file": "definitions/observer.md",
      "sourceLine": 1
    },
    {
      "id": "propagation",
      "title": "Propagation",
      "status": "CANONICAL v1.0 - passed Codex final audit 2026-04-29",
      "file": "definitions/propagation.md",
      "sourceLine": 1
    },
    {
      "id": "state",
      "title": "State",
      "status": "CANONICAL v1.0 — passed Codex final audit 2026-04-30",
      "file": "definitions/state.md",
      "sourceLine": 1
    },
    {
      "id": "time",
      "title": "Time",
      "status": "CANONICAL v1.0 - passed Codex final audit 2026-04-29",
      "file": "definitions/time.md",
      "sourceLine": 1
    }
  ]
};

// Legacy compatibility: also expose as PFDataGraph for any code that reads it
window.PFDataGraph = window.PFClaimsData;