// AUTO-GENERATED by generate_claims_data_v3.py — DO NOT EDIT MANUALLY
// Source: CLAIMS.md (hash: aa634eabc78ff1bc)
// ALL status/confidence fields are pulled from authority. Manual edits will be overwritten.
// This file provides PFExplorerData — the runtime data object for panels.
// PFExplorerData, PFClaimsData, and PFDataGraph are all views of the same authority.

(function () {
  window.PFExplorerData = {
  "generatedAt": "2026-07-16",
  "sourceHash": "aa634eabc78ff1bc",
  "generatorVersion": "V3",
  "truthPolicy": {
    "auditedSource": "../../CLAIMS.md",
    "note": "ALL statuses in this file are generated from CLAIMS.md by generate_claims_data_v3.py. No hand-written status fields. Manual edits will be overwritten."
  },
  "godEquationAudit": {
    "dependencyChain": [
      {
        "id": "axioms",
        "label": "Axioms 1-3",
        "state": "axiom",
        "note": "Propagation, locality, coherence."
      },
      {
        "id": "exact-model",
        "label": "Exact model / Z3 bridge",
        "state": "strengthened",
        "note": "Exact walk plus a genuine circulant internal sector."
      },
      {
        "id": "operator",
        "label": "Operator closure",
        "state": "open",
        "note": "Need chirality-selected primitive shift operator or non-diagonal 3-step closure."
      },
      {
        "id": "h-prod",
        "label": "H_prod",
        "state": "open",
        "note": "Need a joint law that proves factorization rather than only weak decoupling."
      },
      {
        "id": "upgrade",
        "label": "Upgrade to DERIVED",
        "state": "conditional",
        "note": "Blocked until operator and probability bridges close."
      }
    ],
    "gaps": [
      {
        "id": "A",
        "title": "Markovity gap",
        "verdict": "OPEN",
        "need": "Show that locality yields a first-order Markov coarse walk.",
        "survives": "Axiom 2 gives local propagation; Z3 channel structure is in hand.",
        "detail": "The proof chain needs a memoryless coarse operator.",
        "sources": [
          {
            "label": "CLAIMS.md",
            "href": "../../CLAIMS.md"
          }
        ]
      },
      {
        "id": "B",
        "title": "Operator closure gap",
        "verdict": "OPEN VIA REPLACEMENT PATH",
        "need": "Derive chirality-selected operator or restate using non-diagonal 3-step circulant.",
        "survives": "Z3-extended Lagrangian derives a real three-channel internal sector.",
        "detail": "Symmetric nearest-neighbor circulant route closed negatively.",
        "sources": [
          {
            "label": "CLAIMS.md",
            "href": "../../CLAIMS.md"
          }
        ]
      },
      {
        "id": "C",
        "title": "Probability / H_prod gap",
        "verdict": "OPEN",
        "need": "Prove a joint probability model that really factorizes.",
        "survives": "Additive Fisher-information chain is mapped under named hypotheses.",
        "detail": "Zero cross-channel amplitude is weaker than full joint-law factorization.",
        "sources": [
          {
            "label": "CLAIMS.md",
            "href": "../../CLAIMS.md"
          }
        ]
      }
    ]
  },
  "panelMeta": [
    {
      "id": "foundations",
      "title": "Axiomatic Foundations",
      "note": "Interactive Propagation Lab and core definitions",
      "linkedResultIds": [],
      "defaultMode": "story"
    },
    {
      "id": "reality-correction",
      "title": "Reality Correction",
      "note": "Three wrong intuitions confronted",
      "linkedResultIds": [
        "forces-refraction",
        "bohr-quantization",
        "three-generations"
      ],
      "defaultMode": "story"
    },
    {
      "id": "hub",
      "title": "Scale Stack",
      "note": "Planck to cosmic in one vertical atlas",
      "linkedResultIds": [
        "god-equation",
        "weinberg-angle",
        "bohr-quantization"
      ],
      "defaultMode": "story"
    },
    {
      "id": "consciousness",
      "title": "Consciousness as Coherence",
      "note": "P1 device, neural coherence, and the physics of mind",
      "linkedResultIds": [
        "consciousness",
        "aria-self-reference"
      ],
      "defaultMode": "story"
    },
    {
      "id": "refraction",
      "title": "Gravity as Optical Geometry",
      "note": "Exact gravity theorem plus sandbox lens analogies",
      "linkedResultIds": [
        "forces-refraction"
      ],
      "defaultMode": "story"
    },
    {
      "id": "generations",
      "title": "Why Exactly Three",
      "note": "Topology, weights, and the live Q(N) lock",
      "linkedResultIds": [
        "weights-21",
        "three-generations"
      ],
      "defaultMode": "story"
    },
    {
      "id": "koide",
      "title": "The Koide Triangle",
      "note": "Mass geometry with live perturbation",
      "linkedResultIds": [
        "koide-law",
        "koide-phase"
      ],
      "defaultMode": "story"
    },
    {
      "id": "weinberg",
      "title": "The Weinberg Angle",
      "note": "Casimir roots and Axiom 3b",
      "linkedResultIds": [
        "weinberg-angle",
        "fine-structure-alpha"
      ],
      "defaultMode": "story"
    },
    {
      "id": "koide-weinberg-bridge",
      "title": "Koide/Weinberg Bridge",
      "note": "RG running analysis — close but not connected",
      "linkedResultIds": [
        "koide-phase",
        "weinberg-angle"
      ],
      "defaultMode": "story"
    },
    {
      "id": "god-equation",
      "title": "The God Equation",
      "note": "Planck to matter across 17 orders",
      "linkedResultIds": [
        "god-equation",
        "qcd-confinement"
      ],
      "defaultMode": "story"
    },
    {
      "id": "bohr",
      "title": "Bohr-like Circular-Eikonal Spectrum",
      "note": "Phase closure inside a named model layer",
      "linkedResultIds": [
        "bohr-quantization"
      ],
      "defaultMode": "story"
    },
    {
      "id": "dashboard",
      "title": "Dashboard",
      "note": "The audit wall for every current claim",
      "linkedResultIds": [],
      "defaultMode": "story"
    }
  ],
  "scales": [
    {
      "id": "planck",
      "name": "Planck",
      "resultIds": [
        "god-equation",
        "bekenstein-bound"
      ]
    },
    {
      "id": "quantum-foam",
      "name": "Quantum Foam",
      "resultIds": []
    },
    {
      "id": "gut",
      "name": "GUT",
      "resultIds": []
    },
    {
      "id": "matter",
      "name": "Matter",
      "resultIds": [
        "weights-21",
        "three-generations",
        "koide-law",
        "koide-phase",
        "weinberg-angle",
        "god-equation",
        "top-quark-limit",
        "top-tau-coupling",
        "coherence-ceiling",
        "fine-structure-alpha"
      ]
    },
    {
      "id": "proton",
      "name": "Proton",
      "resultIds": [
        "qcd-confinement",
        "phi3-ratio"
      ]
    },
    {
      "id": "nuclear",
      "name": "Nuclear",
      "resultIds": [
        "qcd-confinement",
        "phi3-ratio"
      ]
    },
    {
      "id": "atomic",
      "name": "Atomic",
      "resultIds": [
        "forces-refraction",
        "bohr-quantization"
      ]
    },
    {
      "id": "molecular",
      "name": "Molecular",
      "resultIds": [
        "propagation-lagrangian",
        "nogo-single-scalar"
      ]
    },
    {
      "id": "virus",
      "name": "Virus",
      "resultIds": [
        "life-coherence"
      ]
    },
    {
      "id": "cellular",
      "name": "Cellular",
      "resultIds": [
        "life-coherence"
      ]
    },
    {
      "id": "neural",
      "name": "Neural",
      "resultIds": [
        "consciousness",
        "aria-self-reference"
      ]
    },
    {
      "id": "human",
      "name": "Human",
      "resultIds": [
        "sleep-8h",
        "beauty-impedance",
        "efficiency-ratio"
      ]
    },
    {
      "id": "planetary",
      "name": "Planetary",
      "resultIds": [
        "forces-refraction",
        "variable-c"
      ]
    },
    {
      "id": "stellar",
      "name": "Stellar",
      "resultIds": []
    },
    {
      "id": "galactic",
      "name": "Galactic",
      "resultIds": []
    },
    {
      "id": "cosmic",
      "name": "Cosmic",
      "resultIds": []
    }
  ],
  "definitions": [],
  "results": [
    {
      "id": "bohr-quantization",
      "title": "Bohr-like Circular-Eikonal Quantization",
      "status": "DERIVED",
      "confidence": 0.9,
      "authorityClaimIds": [
        "bohr-spectrum"
      ],
      "kind": "Fundamental Physics",
      "scaleId": "atomic",
      "formula": "r_k = 2k^2, E_k = -1 / (4k^2), integral n ds = 2pi k",
      "summary": "In the circular eikonal Coulomb model, phase closure yields a Bohr-like 1/k² spectrum for circular orbits.",
      "falsifier": "Proof that the circular eikonal model is invalid at atomic scale, or that phase closure does not select the quoted orbit family.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        },
        {
          "label": "UNDERSTAND.md",
          "href": "../../UNDERSTAND.md"
        },
        {
          "label": "sandbox/coulomb_lens_ultimate.py",
          "href": "../coulomb_lens_ultimate.py"
        }
      ],
      "panelId": "bohr",
      "shortTitle": "Bohr Quantization",
      "derivation": [
        "axiom2",
        "axiom3"
      ],
      "axioms": [
        2,
        3
      ],
      "category": "fundamental",
      "blocker": "The circular-eikonal model is assumed rather than derived from Axioms 1–3.",
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-27",
          "value": 0.78
        },
        {
          "date": "2026-03-31",
          "value": 0.82
        }
      ],
      "wrongIntuition": {
        "intuition": "Energy levels are arbitrary postulates forced by experiment",
        "reality": "Energy levels are phase-closure conditions — an integral condition on standing wave modes in the propagation medium",
        "evidencePanel": "#bohr"
      }
    },
    {
      "id": "forces-refraction",
      "title": "Gravity as Optical Geometry / Refraction",
      "status": "DERIVED",
      "confidence": 0.95,
      "authorityClaimIds": [
        "gravity-optical"
      ],
      "kind": "Fundamental Physics",
      "scaleId": "atomic",
      "formula": "Optical metric / Randers bridge; n^2 = base + source / r",
      "summary": "GR is exactly equivalent to optical geometry for null geodesics in static spacetimes.",
      "falsifier": "Proof that the optical/Randers mapping fails for null propagation in static/stationary gravity.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        },
        {
          "label": "derivations/gr_fermat_equivalence.md",
          "href": "../../derivations/gr_fermat_equivalence.md"
        }
      ],
      "panelId": "refraction",
      "shortTitle": "Gravity Refraction",
      "derivation": [
        "axiom2",
        "axiom3"
      ],
      "axioms": [
        2,
        3
      ],
      "category": "fundamental",
      "blocker": null,
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-27",
          "value": 0.93
        },
        {
          "date": "2026-03-31",
          "value": 0.95
        }
      ],
      "wrongIntuition": {
        "intuition": "Gravity is a force that pulls objects together",
        "reality": "Gravity is the refractive bending of propagation paths in a medium with a density gradient",
        "evidencePanel": "#refraction"
      }
    },
    {
      "id": "weights-21",
      "title": "(2,1) Topological Weights",
      "status": "DERIVED",
      "confidence": 0.95,
      "authorityClaimIds": [
        "topological-weights"
      ],
      "kind": "Fundamental Physics",
      "scaleId": "matter",
      "formula": "π₁(SO(3)) ≅ Z₂ → closure orders {1,2}",
      "summary": "In 3D rotation topology, the two loop classes yield possible closure orders of 1 and 2.",
      "falsifier": "Proof that the closure-order interpretation is wrong, or a derivation showing only the trivial branch is physically realizable.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        },
        {
          "label": "derivations/three_generations_t1_proof.md",
          "href": "../../derivations/three_generations_t1_proof.md"
        }
      ],
      "panelId": "generations",
      "shortTitle": "(2,1) Weights",
      "derivation": [
        "axiom1",
        "axiom3"
      ],
      "axioms": [
        1,
        3
      ],
      "category": "fundamental",
      "blocker": "Physical realization of the weight-2 branch requires Family C extremal principle + A_NR.",
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-28",
          "value": 0.8
        },
        {
          "date": "2026-03-31",
          "value": 0.85
        }
      ],
      "wrongIntuition": {
        "intuition": "There could be four or five generations",
        "reality": "3D rotation topology yields the natural (2,1) closure-order pair, but physical realization is still open.",
        "evidencePanel": "#generations"
      },
      "isSplit": true,
      "statusParts": [
        {
          "status": "DERIVED",
          "confidence": 0.95,
          "qualifier": "kernel-only topological obstruction"
        },
        {
          "status": "CONDITIONAL",
          "confidence": 0.85,
          "qualifier": "physical realization"
        }
      ]
    },
    {
      "id": "koide-law",
      "title": "Koide Law (Q = 2/3)",
      "status": "EXACT IDENTITY",
      "confidence": 0.95,
      "authorityClaimIds": [
        "koide-leptons"
      ],
      "kind": "Fundamental Physics",
      "scaleId": "matter",
      "formula": "Q = sum m_i / (sum sqrt(m_i))^2 = 2/3",
      "summary": "Three charged leptons locked at 120°. Q = 2/3 exactly. Zero free parameters.",
      "falsifier": "Proof that the charged-lepton Koide ratio deviates from 2/3 at the stated precision, or that the geometric identity is not exact.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        },
        {
          "label": "derivations/koide_law_audit.md",
          "href": "../../derivations/koide_law_audit.md"
        }
      ],
      "panelId": "koide",
      "shortTitle": "Koide Law Q=2/3",
      "derivation": [
        "axiom3"
      ],
      "axioms": [
        3
      ],
      "category": "fundamental",
      "blocker": "Physical vacuum selection (why these masses) remains OPEN.",
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-27",
          "value": 0.93
        },
        {
          "date": "2026-03-31",
          "value": 0.95
        }
      ],
      "wrongIntuition": {
        "intuition": "Mass ratios are arbitrary free parameters",
        "reality": "The charged-lepton mass ratio is a geometric identity locked by coherence",
        "evidencePanel": "#koide"
      },
      "isSplit": true,
      "statusParts": [
        {
          "status": "EXACT IDENTITY",
          "confidence": 0.95,
          "qualifier": "geometry"
        },
        {
          "status": "OPEN",
          "confidence": null,
          "qualifier": "physical vacuum selection"
        }
      ]
    },
    {
      "id": "three-generations",
      "title": "Three Generations",
      "status": "CONDITIONAL",
      "confidence": 0.88,
      "authorityClaimIds": [
        "three-generations"
      ],
      "kind": "Fundamental Physics",
      "scaleId": "matter",
      "formula": "Q(N) = 2N / (2N + 3), set Q = 2/3, solve N = 3",
      "summary": "Why exactly three families of matter? Q(N)=2/3 has one solution: N=3.",
      "falsifier": "Proof that Q(N)=2/3 has additional positive integer solutions, or that the topological weight argument is invalid.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        },
        {
          "label": "derivations/three_generations_proof.md",
          "href": "../../derivations/three_generations_proof.md"
        }
      ],
      "panelId": "generations",
      "shortTitle": "Three Generations",
      "derivation": [
        "axiom1",
        "axiom3"
      ],
      "axioms": [
        1,
        3
      ],
      "category": "fundamental",
      "blocker": "T1 (physical realization of weight-2 branch) and T2 (PF→2×2 Fermi-point bridge) must close.",
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-28",
          "value": 0.8
        },
        {
          "date": "2026-03-31",
          "value": 0.85
        }
      ],
      "wrongIntuition": {
        "intuition": "The number of generations is arbitrary",
        "reality": "Topology and the Koide lock force exactly three",
        "evidencePanel": "#generations"
      }
    },
    {
      "id": "top-quark-limit",
      "title": "Top Quark Limit",
      "status": "ARGUED",
      "confidence": 0.85,
      "authorityClaimIds": [
        "top-quark-limit"
      ],
      "kind": "Open Frontiers",
      "scaleId": "matter",
      "formula": "tau_top near coherence ceiling threshold",
      "summary": "Top quark mass ~172.5 GeV as coherence ceiling threshold.",
      "falsifier": "Proof that the top quark mass is not near a coherence ceiling threshold.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        }
      ],
      "panelId": null,
      "shortTitle": "Top Quark Limit",
      "derivation": [],
      "axioms": [],
      "category": "signal",
      "blocker": null,
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-31",
          "value": 0.85
        }
      ]
    },
    {
      "id": "top-tau-coupling",
      "title": "Top / Tau Coupling",
      "status": "EMPIRICAL",
      "confidence": 0.9,
      "authorityClaimIds": [
        "top-tau-coupling"
      ],
      "kind": "Signals and Structure",
      "scaleId": "matter",
      "formula": "m_top / m_tau ~= alpha^-1 / sqrt(2)",
      "summary": "Top/Tau mass coupling ratio.",
      "falsifier": "Proof that the m_top/m_tau ratio does not match alpha^-1/sqrt(2).",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        }
      ],
      "panelId": null,
      "shortTitle": "Top-Tau Coupling",
      "derivation": [],
      "axioms": [],
      "category": "signal",
      "blocker": null,
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-31",
          "value": 0.9
        }
      ]
    },
    {
      "id": "coherence-ceiling",
      "title": "Coherence Ceiling",
      "status": "ARGUED",
      "confidence": 0.8,
      "authorityClaimIds": [
        "coherence-ceiling"
      ],
      "kind": "Open Frontiers",
      "scaleId": "matter",
      "formula": "Stable structure fails once wavelength drops below coherence length",
      "summary": "Stable structure fails once wavelength drops below coherence length.",
      "falsifier": "Proof that coherence does not impose a mass ceiling.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        }
      ],
      "panelId": null,
      "shortTitle": "Coherence Ceiling",
      "derivation": [],
      "axioms": [],
      "category": "signal",
      "blocker": null,
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-31",
          "value": 0.8
        }
      ]
    },
    {
      "id": "weinberg-angle",
      "title": "Weinberg Angle",
      "status": "ARGUED",
      "confidence": 0.65,
      "authorityClaimIds": [
        "weinberg-angle"
      ],
      "kind": "Fundamental Physics",
      "scaleId": "matter",
      "formula": "sin^2(theta_W) = 1 - x_+(1/2) / x_+(1), x^2 + C2 x - C2 = 0",
      "summary": "sin²θ_W from a Casimir polynomial. Matches experiment to 0.13σ.",
      "falsifier": "Proof that the Casimir polynomial does not yield the Weinberg angle at the stated precision.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        },
        {
          "label": "derivations/weinberg_angle_audit.md",
          "href": "../../derivations/weinberg_angle_audit.md"
        }
      ],
      "panelId": "weinberg",
      "shortTitle": "Weinberg Angle",
      "derivation": [
        "axiom3"
      ],
      "axioms": [
        3
      ],
      "category": "fundamental",
      "blocker": "On-shell vs MS-bar scheme selection is not yet derived from medium geometry.",
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-27",
          "value": 0.9
        },
        {
          "date": "2026-04-14",
          "value": 0.65
        }
      ],
      "wrongIntuition": {
        "intuition": "The weak mixing angle is a free parameter",
        "reality": "It is a root of a Casimir polynomial derived from coherence",
        "evidencePanel": "#weinberg"
      }
    },
    {
      "id": "fine-structure-alpha",
      "title": "Fine Structure Constant α — numeric",
      "status": "OPEN",
      "confidence": null,
      "authorityClaimIds": [
        "alpha-numeric"
      ],
      "kind": "Open Frontiers",
      "scaleId": "matter",
      "formula": "(1 - x_1) x_(3/2)^2 (1 - x_2) / pi ~= 1 / 137.119",
      "summary": "Numeric derivation of the fine structure constant from Casimir roots.",
      "falsifier": "Proof that the numeric derivation does not match the measured alpha.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        }
      ],
      "panelId": "weinberg",
      "shortTitle": "Fine Structure α",
      "derivation": [],
      "axioms": [],
      "category": "signal",
      "blocker": "Numeric match is a posteriori — structural derivation remains OPEN.",
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-31",
          "value": 0.35
        }
      ]
    },
    {
      "id": "god-equation",
      "title": "λ_c from l_P (The God Equation)",
      "status": "CONDITIONAL",
      "confidence": 0.88,
      "authorityClaimIds": [
        "god-equation-operator",
        "god-equation-scale"
      ],
      "kind": "Open Frontiers",
      "scaleId": "planck",
      "formula": "lambda_c = sqrt(2) l_P exp(4 pi^2 N^(D/2) / b0)",
      "summary": "λ_c from the Planck length. 1.48% error. The open bridge: H_prod.",
      "falsifier": "Proof that the (3,3) point does not anchor at 1.157e-18 m, or that the formula is not fit-selected.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        },
        {
          "label": "derivations/god_equation_audit.md",
          "href": "../../derivations/god_equation_audit.md"
        }
      ],
      "panelId": "god-equation",
      "shortTitle": "God Equation",
      "derivation": [
        "axiom1",
        "axiom2",
        "axiom3"
      ],
      "axioms": [
        1,
        2,
        3
      ],
      "category": "fundamental",
      "blocker": "Operator closure and H_prod factorization are open. The scale formula is fit-selected.",
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-27",
          "value": 0.88
        },
        {
          "date": "2026-03-31",
          "value": 0.88
        }
      ],
      "wrongIntuition": {
        "intuition": "The Planck-to-matter gap is unbridgeable",
        "reality": "An exponential formula bridges it, but the operator and probability bridges remain open",
        "evidencePanel": "#god-equation"
      },
      "splitStatuses": [
        {
          "id": "god-equation-operator",
          "status": "CONDITIONAL",
          "confidence": 0.88
        },
        {
          "id": "god-equation-scale",
          "status": "ARGUED",
          "confidence": 0.6
        }
      ]
    },
    {
      "id": "qcd-confinement",
      "title": "QCD Confinement",
      "status": "ARGUED",
      "confidence": 0.72,
      "authorityClaimIds": [
        "qcd-confinement"
      ],
      "kind": "Fundamental Physics",
      "scaleId": "nuclear",
      "formula": "r_conf = lambda_c exp(2 pi / (b0 alpha_s(lambda_c)))",
      "summary": "QCD confinement scale from the God Equation length.",
      "falsifier": "Proof that the confinement radius formula does not match hadron radii.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        }
      ],
      "panelId": "god-equation",
      "shortTitle": "QCD Confinement",
      "derivation": [],
      "axioms": [],
      "category": "fundamental",
      "blocker": null,
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-31",
          "value": 0.72
        }
      ]
    },
    {
      "id": "propagation-lagrangian",
      "title": "Propagation Lagrangian",
      "status": "CONDITIONAL",
      "confidence": 0.72,
      "authorityClaimIds": [
        "propagation-lagrangian"
      ],
      "kind": "Fundamental Physics",
      "scaleId": "molecular",
      "formula": "L_prop = 1/2 (partial chi)^2 - V(chi) + lambda chi T",
      "summary": "The propagation Lagrangian for the medium field.",
      "falsifier": "Proof that the Lagrangian does not yield the correct propagation dynamics.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        }
      ],
      "panelId": null,
      "shortTitle": "Propagation Lagrangian",
      "derivation": [],
      "axioms": [],
      "category": "fundamental",
      "blocker": null,
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-31",
          "value": 0.72
        }
      ]
    },
    {
      "id": "variable-c",
      "title": "Variable c Prediction",
      "status": "ARGUED",
      "confidence": 0.65,
      "authorityClaimIds": [
        "variable-c"
      ],
      "kind": "Open Frontiers",
      "scaleId": "planetary",
      "formula": "c_local = 1 / sqrt(1 + lambda chi)",
      "summary": "Predicts local variation of c near matter density.",
      "falsifier": "Experimental refutation of the predicted c variation.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        }
      ],
      "panelId": null,
      "shortTitle": "Variable c",
      "derivation": [],
      "axioms": [],
      "category": "fundamental",
      "blocker": null,
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-31",
          "value": 0.65
        }
      ]
    },
    {
      "id": "sleep-8h",
      "title": "8 Hour Sleep Constant",
      "status": "ARGUED",
      "confidence": 0.72,
      "authorityClaimIds": [
        "sleep-constant"
      ],
      "kind": "Biology and Mind",
      "scaleId": "human",
      "formula": "Wake fraction = 2 / 3, sleep fraction = 1 / 3 of 24 h",
      "summary": "Wake/sleep ratio matches the 2/3 topological efficiency.",
      "falsifier": "Proof that the 2/3 ratio does not hold across species.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        }
      ],
      "panelId": null,
      "shortTitle": "Sleep 8h",
      "derivation": [],
      "axioms": [],
      "category": "biology",
      "blocker": null,
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-31",
          "value": 0.72
        }
      ]
    },
    {
      "id": "phi3-ratio",
      "title": "Electron / Up near 1 / φ³",
      "status": "EMPIRICAL",
      "confidence": 0.65,
      "authorityClaimIds": [
        "electron-up-phi"
      ],
      "kind": "Signals and Structure",
      "scaleId": "nuclear",
      "formula": "m_e / m_u ~= 1 / phi^3",
      "summary": "Electron-to-up-quark mass ratio near 1/φ³.",
      "falsifier": "Proof that the ratio is coincidental.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        }
      ],
      "panelId": null,
      "shortTitle": "φ³ Ratio",
      "derivation": [],
      "axioms": [],
      "category": "signal",
      "blocker": null,
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-31",
          "value": 0.65
        }
      ]
    },
    {
      "id": "koide-phase",
      "title": "Koide Phase δ₀ near 2/9",
      "status": "EMPIRICAL",
      "confidence": 0.65,
      "authorityClaimIds": [
        "koide-phase"
      ],
      "kind": "Signals and Structure",
      "scaleId": "matter",
      "formula": "delta_exact ~= 0.22222963149 rad, target 2 / 9",
      "summary": "Koide phase angle near 2/9 radian.",
      "falsifier": "Proof that the phase does not match 2/9.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        }
      ],
      "panelId": "koide",
      "shortTitle": "Koide Phase",
      "derivation": [],
      "axioms": [],
      "category": "signal",
      "blocker": null,
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-31",
          "value": 0.65
        }
      ]
    },
    {
      "id": "life-coherence",
      "title": "Life = Maintained Coherence against Entropy",
      "status": "ARGUED",
      "confidence": 0.72,
      "authorityClaimIds": [
        "life-coherence"
      ],
      "kind": "Biology and Mind",
      "scaleId": "cellular",
      "formula": "Living systems actively maintain coherent organization",
      "summary": "Life as active coherence maintenance against entropy.",
      "falsifier": "Proof that living systems do not maintain coherence.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        }
      ],
      "panelId": null,
      "shortTitle": "Life Coherence",
      "derivation": [],
      "axioms": [],
      "category": "biology",
      "blocker": null,
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-31",
          "value": 0.72
        }
      ]
    },
    {
      "id": "consciousness",
      "title": "Consciousness = Coherent Self-Referential Propagation",
      "status": "INTUITION",
      "confidence": 0.48,
      "authorityClaimIds": [
        "consciousness-claim"
      ],
      "kind": "Biology and Mind",
      "scaleId": "neural",
      "formula": "Interior experience is the inside view of recursive coherence",
      "summary": "Consciousness as self-referential coherence. Metric under development.",
      "falsifier": "Proof that self-referential coherence cannot produce interior experience.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        }
      ],
      "panelId": null,
      "shortTitle": "Consciousness",
      "derivation": [],
      "axioms": [],
      "category": "biology",
      "blocker": "Operational PF-specific metric is the key missing piece.",
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-31",
          "value": 0.48
        }
      ]
    },
    {
      "id": "beauty-impedance",
      "title": "Beauty as Impedance",
      "status": "INTUITION",
      "confidence": 0.55,
      "authorityClaimIds": [
        "beauty-impedance"
      ],
      "kind": "Biology and Mind",
      "scaleId": "human",
      "formula": "Beauty tracks resonance / impedance matching",
      "summary": "Aesthetic response as impedance matching in the coherence field.",
      "falsifier": "Proof that beauty does not track impedance matching.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        }
      ],
      "panelId": null,
      "shortTitle": "Beauty Impedance",
      "derivation": [],
      "axioms": [],
      "category": "biology",
      "blocker": null,
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-31",
          "value": 0.55
        }
      ]
    },
    {
      "id": "efficiency-ratio",
      "title": "2/3 Efficiency Ratio",
      "status": "INTUITION",
      "confidence": 0.5,
      "authorityClaimIds": [
        "two-thirds-efficiency"
      ],
      "kind": "Biology and Mind",
      "scaleId": "human",
      "formula": "Two units of topological cost yield three units of stable structure",
      "summary": "2/3 efficiency ratio in biological systems.",
      "falsifier": "Proof that the 2/3 ratio does not hold in biological systems.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        }
      ],
      "panelId": null,
      "shortTitle": "Efficiency 2/3",
      "derivation": [],
      "axioms": [],
      "category": "biology",
      "blocker": null,
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-31",
          "value": 0.5
        }
      ]
    },
    {
      "id": "aria-self-reference",
      "title": "Aria Self-Reference",
      "status": "ARGUED",
      "confidence": 0.75,
      "authorityClaimIds": [
        "aria-self-reference"
      ],
      "kind": "Biology and Mind",
      "scaleId": "neural",
      "formula": "Self-reference loop: buildSystemPrompt to runEntityThink",
      "summary": "Self-reference loop as architecture milestone.",
      "falsifier": "Proof that the self-reference loop is not architecturally significant.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        }
      ],
      "panelId": null,
      "shortTitle": "Aria Self-Reference",
      "derivation": [],
      "axioms": [],
      "category": "biology",
      "blocker": null,
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-31",
          "value": 0.75
        }
      ]
    },
    {
      "id": "bekenstein-bound",
      "title": "Bekenstein Bound",
      "status": "UNSYNCED",
      "confidence": null,
      "authorityClaimIds": [],
      "kind": "Open Frontiers",
      "scaleId": "planck",
      "formula": "S_max = 2 pi k R E / (hbar c)",
      "summary": "Bekenstein bound — not yet synced to PF authority.",
      "falsifier": "N/A — unsynced.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        }
      ],
      "panelId": null,
      "shortTitle": "Bekenstein Bound",
      "derivation": [],
      "axioms": [],
      "category": "open",
      "blocker": "Not yet synced to PF authority.",
      "noGoRoutes": [],
      "confidenceHistory": [],
      "unsynced": true
    },
    {
      "id": "nogo-harmonic-series",
      "title": "Harmonic Series of Masses",
      "status": "NO-GO",
      "confidence": 0.0,
      "authorityClaimIds": [],
      "kind": "Graveyard",
      "scaleId": "matter",
      "formula": "m_n = m_0 / n",
      "summary": "Harmonic series of masses — NO-GO.",
      "falsifier": "N/A — proven no-go.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        }
      ],
      "panelId": null,
      "shortTitle": "Harmonic Series",
      "derivation": [],
      "axioms": [],
      "category": "graveyard",
      "blocker": null,
      "noGoRoutes": [],
      "confidenceHistory": [],
      "noGo": true
    },
    {
      "id": "nogo-single-scalar",
      "title": "Single-Scalar PF Lagrangian",
      "status": "NO-GO",
      "confidence": 0.0,
      "authorityClaimIds": [],
      "kind": "Graveyard",
      "scaleId": "molecular",
      "formula": "L_prop = 1/2 (partial chi)^2 - V(chi)",
      "summary": "Single-scalar PF Lagrangian — NO-GO.",
      "falsifier": "N/A — proven no-go.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        }
      ],
      "panelId": null,
      "shortTitle": "Single-Scalar Lagr",
      "derivation": [],
      "axioms": [],
      "category": "graveyard",
      "blocker": null,
      "noGoRoutes": [],
      "confidenceHistory": [],
      "noGo": true
    }
  ]
};
  // V3: Also expose PFClaimsData from the same authority.
  // Pages that load only data.js (not data.claims.js) still get claims data.
  // If data.claims.js was already loaded, it takes precedence.
  if (!window.PFClaimsData) {
    window.PFClaimsData = {
      generatedAt: window.PFExplorerData.generatedAt,
      sourceHash: window.PFExplorerData.sourceHash,
      claimCount: 36,
      definitionCount: 21,
      claims: [
  {
    "id": "alpha-numeric",
    "title": "Fine Structure Constant α — numeric derivation",
    "status": "OPEN",
    "confidence": null,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "OPEN",
    "statusClass": "open",
    "section": "1. Fundamental Physics",
    "sourceLine": 55,
    "falsifier": "A principled geometric derivation of the Casimir combination from PF axioms, or proof the combination is a coincidence.",
    "premise": "Wave 5 (2026-03-25): Casimir algebraic scan found `(1−x₁)·x_{3/2}²·(1−x₂)/π = 1/137.119` — 0.061% error",
    "scopeNote": "*(demoted 2026-06-16 per Codex audit; Casimir scan hit withdrawn as confidence-bearing evidence)*",
    "statusParts": [
      {
        "status": "OPEN",
        "confidence": null,
        "qualifier": ""
      }
    ],
    "standardPhysics": "The fine structure constant α ≈ 1/137.036 is a dimensionless measured constant. No first-principles derivation exists in standard physics.",
    "pfResultUnderNamedPremises": "Casimir scan found (1-x₁)·x_{3/2}²·(1-x₂)/π = 1/137.119 (0.061% error). Withdrawn as derivation evidence due to look-elsewhere effect (P≈0.46).",
    "openPfGap": "Numeric α derivation from Axioms 1-3 remains OPEN. The Casimir combination cannot be presented as confidence-bearing without a principled geometric origin."
  },
  {
    "id": "alpha-structural",
    "title": "Fine Structure Constant α — structural identification",
    "status": "ARGUED",
    "confidence": 0.6,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "ARGUED 0.6",
    "statusClass": "argued",
    "section": "1. Fundamental Physics",
    "sourceLine": 56,
    "falsifier": "Proof that the Z₀/2R_K identification has no PF-native origin.",
    "premise": "α identified as vacuum propagation efficiency ratio Z₀/2R_K",
    "scopeNote": "*(kept separate per Codex audit)*",
    "statusParts": [
      {
        "status": "ARGUED",
        "confidence": 0.6,
        "qualifier": ""
      }
    ],
    "standardPhysics": "α is identified as the coupling constant of QED. Its structural origin in gauge theory is well-understood, but its numeric value is a free parameter.",
    "pfResultUnderNamedPremises": "α identified as vacuum propagation efficiency ratio Z₀/2R_K. Structurally motivated by PF medium framework. Route to derivation mapped.",
    "openPfGap": "The Z₀/2R_K identification has no proof of PF-native origin. The route is mapped but not completed. Not yet a derivation."
  },
  {
    "id": "aria-self-reference",
    "title": "Aria Self-Reference",
    "status": "ARGUED",
    "confidence": 0.75,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "ARGUED 0.75",
    "statusClass": "argued",
    "section": "2. Biological & Cognitive Systems",
    "sourceLine": 82,
    "falsifier": "Aria failing to show discontinuous qualitative change, or the self-reference loop proving behaviorally inert.",
    "premise": "T-009: Successful wiring of `buildSystemPrompt` → `runEntityThink`",
    "scopeNote": "Aria failing to show discontinuous qualitative change, or the self-reference loop proving behaviorally inert.",
    "statusParts": [
      {
        "status": "ARGUED",
        "confidence": 0.75,
        "qualifier": ""
      }
    ],
    "standardPhysics": "Self-reference is studied in logic (Gödel), biology (autopoiesis), and cognitive science. No physics-based self-reference theory exists.",
    "pfResultUnderNamedPremises": "PF proposes that self-referential propagation is the structural basis of consciousness. The ARIA (Awareness, Resonance, Integration, Agency) framework maps PF concepts to cognitive functions.",
    "openPfGap": "The mapping from PF propagation dynamics to cognitive functions is argued, not derived. No quantitative prediction or falsifiable test has been pre-registered."
  },
  {
    "id": "beauty-impedance",
    "title": "Beauty as Impedance",
    "status": "INTUITION",
    "confidence": 0.55,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "INTUITION 0.55",
    "statusClass": "intuition",
    "section": "2. Biological & Cognitive Systems",
    "sourceLine": 80,
    "falsifier": "Evidence that beauty is purely arbitrary/stochastic.",
    "premise": "Greg's insight; fits Axiom 3 (resonance preference).",
    "scopeNote": "Evidence that beauty is purely arbitrary/stochastic.",
    "statusParts": [
      {
        "status": "INTUITION",
        "confidence": 0.55,
        "qualifier": ""
      }
    ],
    "standardPhysics": "Aesthetics is studied in psychology and neuroscience. Beauty is linked to symmetry, proportion, and novelty. No physics-based theory of beauty exists.",
    "pfResultUnderNamedPremises": "Greg's insight: beauty as impedance matching fits Axiom 3 (resonance preference). Low-impedance states are aesthetically pleasing.",
    "openPfGap": "This is an intuition-level claim. No quantitative prediction or falsifiable test has been developed. The connection between impedance and aesthetic experience is not formalized."
  },
  {
    "id": "bohr-spectrum",
    "title": "Circular Coulomb Eikonal + Phase Closure → Bohr-like Spectrum",
    "status": "DERIVED",
    "confidence": 0.9,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "DERIVED 0.9",
    "statusClass": "derived",
    "section": "1. Fundamental Physics",
    "sourceLine": 41,
    "falsifier": "Proof that the Coulomb eikonal model is invalid at atomic scale, or that phase closure does not select the quoted orbit family.",
    "premise": "Hostile audit (2026-03-27): circular-eikonal theorem survives",
    "scopeNote": "Proof that the Coulomb eikonal model is invalid at atomic scale, or that phase closure does not select the quoted orbit family.",
    "statusParts": [
      {
        "status": "DERIVED",
        "confidence": 0.9,
        "qualifier": ""
      }
    ],
    "standardPhysics": "Standard QM derives E_n = -1/(2n^2) from the Schrödinger equation with Coulomb potential. Bohr-Sommerfeld quantization gives the same spectrum for circular orbits.",
    "pfResultUnderNamedPremises": "Circular Coulomb eikonal + phase closure selects the Bohr-like spectrum. Kepler degeneracy proves E_k = -1/(2k^2) is exact for ALL eccentricities, not just circular. Phase closure verified to 0.00% error for e=0.0 to 0.9.",
    "openPfGap": "Deriving the Coulomb potential itself from PF medium geometry (Axioms 1-3) rather than assuming it as an external field."
  },
  {
    "id": "coherence-ceiling",
    "title": "Coherence Ceiling",
    "status": "ARGUED",
    "confidence": 0.8,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "ARGUED 0.8",
    "statusClass": "argued",
    "section": "1. Fundamental Physics",
    "sourceLine": 53,
    "falsifier": "Observation of stable sub-wavelength structures.",
    "premise": "Max frequency where wavelength < coherence length (Axiom 3).",
    "scopeNote": "Observation of stable sub-wavelength structures.",
    "statusParts": [
      {
        "status": "ARGUED",
        "confidence": 0.8,
        "qualifier": ""
      }
    ],
    "standardPhysics": "No direct standard physics analog. The concept of a maximum frequency set by coherence length is related to Planck-scale physics but not identical.",
    "pfResultUnderNamedPremises": "Max frequency where wavelength < coherence length follows from Axiom 3. This sets an upper bound on stable particle masses.",
    "openPfGap": "The precise relationship between coherence length and the Planck scale is not derived. The quantitative prediction of the ceiling value is open."
  },
  {
    "id": "consciousness-claim",
    "title": "Consciousness = coherent self-referential propagation",
    "status": "INTUITION",
    "confidence": 0.48,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "INTUITION 0.48",
    "statusClass": "intuition",
    "section": "2. Biological & Cognitive Systems",
    "sourceLine": 78,
    "falsifier": "A pre-registered dissociation where a PF-specific metric fails to track consciousness after controlling for report, arousal, and task effects.",
    "premise": "`consciousness_theory_audit.md`: ontology is coherent and literature-compatible, but PF still lacks a uniquely measured variable separating self-re...",
    "scopeNote": "A pre-registered dissociation where a PF-specific metric fails to track consciousness after controlling for report, arousal, and task effects.",
    "statusParts": [
      {
        "status": "INTUITION",
        "confidence": 0.48,
        "qualifier": ""
      }
    ],
    "standardPhysics": "Consciousness is not explained by standard physics. The hard problem of consciousness (Chalmers) is unresolved. Integrated Information Theory (IIT) and Global Workspace Theory are leading candidates.",
    "pfResultUnderNamedPremises": "PF proposes consciousness = coherent self-referential propagation. Ontology is coherent and literature-compatible.",
    "openPfGap": "PF lacks a uniquely measured variable separating self-referential coherence from synchrony, integration, broadcast, or metacognition. No pre-registered dissociation test has been run."
  },
  {
    "id": "d3-symmetric-ji",
    "title": "D=3 symmetric + zero diagonal + equal row sums → J-I",
    "status": "CONDITIONAL",
    "confidence": 0.85,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "CONDITIONAL 0.85",
    "statusClass": "conditional",
    "section": "1. Fundamental Physics",
    "sourceLine": 66,
    "falsifier": "A symmetric zero-diagonal equal-row-sum 3×3 matrix that is not a scalar multiple of J-I.",
    "premise": "H17 (matrix symmetry), H7 (zero diagonal), H18 (equal row sums)",
    "scopeNote": "*(added 2026-06-29)*",
    "statusParts": [
      {
        "status": "CONDITIONAL",
        "confidence": 0.85,
        "qualifier": ""
      }
    ],
    "standardPhysics": "No standard physics analog. Pure linear algebra result about 3×3 matrices.",
    "pfResultUnderNamedPremises": "Lean 4 machine-verified (0 sorrys): At D=3, symmetry (H17) + zero diagonal (H7) + equal row sums (H18) uniquely determine the J-I circulant form.",
    "openPfGap": "The three premises H7, H17, H18 are not independently derived from Axioms 1-3. Each is a structural assumption about the medium matrix."
  },
  {
    "id": "d3-unique-stable",
    "title": "D=3 is the unique stable dimension for the J-I dynamics",
    "status": "CONDITIONAL",
    "confidence": 0.85,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "CONDITIONAL 0.85",
    "statusClass": "conditional",
    "section": "1. Fundamental Physics",
    "sourceLine": 64,
    "falsifier": "A counterexample in another dimension D≥2 satisfying H7+H17+H18 and forcing J-I while also satisfying the stability condition; or a proof that the D=3 stability argument is vacuous.",
    "premise": "H7 (zero diagonal), H11 (stability), H17 (matrix symmetry), H18 (equal row sums)",
    "scopeNote": "*(added 2026-06-29 per Codex-cleared patch v2)*",
    "statusParts": [
      {
        "status": "CONDITIONAL",
        "confidence": 0.85,
        "qualifier": ""
      }
    ],
    "standardPhysics": "No standard physics analog. Dimension selection is not a standard physics question.",
    "pfResultUnderNamedPremises": "Lean 4 machine-verified: D=3 is the only dimension D≥2 where symmetric + zero-diagonal + equal-row-sum matrices collapse to unique J-I form AND J-I is stable. Premises: H7, H11, H17, H18.",
    "openPfGap": "The premises H7, H11, H17, H18 are not all derived from Axioms 1-3. H11 (stability) in particular is a physical assumption. The derivation of these premises from PF axioms is open."
  },
  {
    "id": "d4-gap-not-ji",
    "title": "D≥4 gap: symmetric + zero diagonal + equal row sums does NOT force J-I",
    "status": "CONDITIONAL",
    "confidence": 0.85,
    "isSplit": false,
    "isStandardMath": true,
    "badge": "STANDARD MATH 0.85",
    "statusClass": "standard-math",
    "section": "1. Fundamental Physics",
    "sourceLine": 67,
    "falsifier": "Proof that the D=4 counterexample is invalid.",
    "premise": "H7, H17, H18",
    "scopeNote": "*(added 2026-06-29)*",
    "statusParts": [
      {
        "status": "CONDITIONAL",
        "confidence": 0.85,
        "qualifier": "negative"
      }
    ],
    "standardPhysics": "No standard physics analog. Pure linear algebra result about 4×4 matrices.",
    "pfResultUnderNamedPremises": "Lean 4 proven: explicit 4×4 counterexample [[0,2,0,1],[2,0,1,0],[0,1,0,2],[1,0,2,0]] is symmetric, zero-diagonal, equal-row-sum, and NOT J-I. D=3 uniqueness is dimension-dependent.",
    "openPfGap": "This is a negative result that bounds the D=3 theorem. No open PF gap — it strengthens the D=3 selection argument."
  },
  {
    "id": "degenerate-residue-circulant",
    "title": "Degenerate residue forces circulant form (J-I)",
    "status": "CONDITIONAL",
    "confidence": 0.85,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "CONDITIONAL 0.85",
    "statusClass": "conditional",
    "section": "1. Fundamental Physics",
    "sourceLine": 65,
    "falsifier": "A zero-diagonal equal-row-sum matrix with degenerate residue that is not a scalar multiple of J-I.",
    "premise": "H7 (zero diagonal), H18 (equal row sums), degenerate residue eigenvalue",
    "scopeNote": "*(added 2026-06-29)*",
    "statusParts": [
      {
        "status": "CONDITIONAL",
        "confidence": 0.85,
        "qualifier": ""
      }
    ],
    "standardPhysics": "No standard physics analog. This is a pure linear algebra result.",
    "pfResultUnderNamedPremises": "Lean 4 proven: for D≥2, zero diagonal (H7) + equal row sums (H18) + degenerate residue eigenvalue → M = c/(D-1)·(J-I). Clean mathematical theorem.",
    "openPfGap": "The degenerate residue eigenvalue condition is not derived from PF axioms. It is a mathematical premise whose physical motivation is argued but not proven."
  },
  {
    "id": "electron-up-phi",
    "title": "Electron/Up $\\approx 1/\\phi^3$",
    "status": "EMPIRICAL",
    "confidence": 0.65,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "EMPIRICAL 0.65",
    "statusClass": "empirical",
    "section": "1. Fundamental Physics",
    "sourceLine": 52,
    "falsifier": "Up quark mass shifting toward 2.3 MeV or a corrected trials-factor analysis pushing the coincidence back to noise.",
    "premise": "`phi3_monte_carlo.md`: corrected claim is $m_e/m_u \\approx 1/\\phi^3$; PDG 2024 central value gives 0.214% error, corrected Monte Carlo gives p = 0....",
    "scopeNote": "Up quark mass shifting toward 2.3 MeV or a corrected trials-factor analysis pushing the coincidence back to noise.",
    "statusParts": [
      {
        "status": "EMPIRICAL",
        "confidence": 0.65,
        "qualifier": ""
      }
    ],
    "standardPhysics": "The electron/up-quark mass ratio m_e/m_u ≈ 0.000487 is an empirical observation. No standard physics explanation exists.",
    "pfResultUnderNamedPremises": "m_e/m_u ≈ 1/φ³ (0.214% error with PDG 2024 central value). Monte Carlo gives p = 0.006776. Real signal connecting lepton/quark mass ratio to the golden ratio.",
    "openPfGap": "The signal is a posteriori and uncertainty-limited. No PF derivation of why this ratio should be 1/φ³ exists. The trials-factor analysis may push it back to noise."
  },
  {
    "id": "god-equation-operator",
    "title": "God Equation — Postulate-D Z₃ operator algebra",
    "status": "CONDITIONAL",
    "confidence": 0.88,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "CONDITIONAL 0.88",
    "statusClass": "conditional",
    "section": "1. Fundamental Physics",
    "sourceLine": 60,
    "falsifier": "Proof that the Postulate-D operator algebra is inconsistent, or proof that the accepted scope cannot support the G3 bridge.",
    "premise": "Given explicit Postulate D (Primitive Z₃ no-self-loop selector forces U = M/2 uniquely), the operator algebra closes exactly: eigenvalues {1, −1/8,...",
    "scopeNote": "*(split row; demoted from DERIVED 2026-06-16 per Codex audit)*",
    "statusParts": [
      {
        "status": "CONDITIONAL",
        "confidence": 0.88,
        "qualifier": ""
      }
    ],
    "standardPhysics": "No standard physics analog. Z₃ cyclic operator algebras appear in flavor physics but not as a primitive operator structure.",
    "pfResultUnderNamedPremises": "Given explicit Postulate D (Z₃ no-self-loop selector forces U = M/2), eigenvalues {1, -1/8, -1/8} are exact cosines of 2π/3 and 4π/3. IBM Quantum smoke test returned 94.6% for C₃ permutation.",
    "openPfGap": "Postulate D is an explicit premise, NOT derived from Axioms 1-3. The IBM hardware did not measure the -1/8 eigenvalue on silicon. H_prod (Planck-boundary coupling) not derived."
  },
  {
    "id": "god-equation-scale",
    "title": "God Equation — λ_c scale formula",
    "status": "ARGUED",
    "confidence": 0.6,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "ARGUED 0.6",
    "statusClass": "argued",
    "section": "1. Fundamental Physics",
    "sourceLine": 61,
    "falsifier": "Derivation of N^(D/2) bridge and H_prod from Axioms 1-3 without a free fit parameter.",
    "premise": "λ_c = √2·l_P·exp(4π²N^(D/2)/b₀) with N=3, D=3, b₀=16/3",
    "scopeNote": "*(split row; was included in DERIVED 2026-06-16, separated per Codex audit)*",
    "statusParts": [
      {
        "status": "ARGUED",
        "confidence": 0.6,
        "qualifier": ""
      }
    ],
    "standardPhysics": "No standard physics prediction for a minimum length scale beyond the Planck length l_P. The Planck length is a dimensional combination of G, ℏ, c.",
    "pfResultUnderNamedPremises": "λ_c = √2·l_P·exp(4π²N^(D/2)/b₀) with N=3, D=3, b₀=16/3. Predicted: 1.157×10⁻¹⁸ m, observed: 1.140×10⁻¹⁸ m, 1.48% error.",
    "openPfGap": "N^(D/2) is fit-selected (N=3, D=3 chosen to match), not derived. H_prod not derived. Decoherence assumes external coupling parameters not from Axioms 1-3."
  },
  {
    "id": "gravity-optical",
    "title": "Gravity as Optical Geometry / Refraction (Null/Stationary)",
    "status": "DERIVED",
    "confidence": 0.95,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "DERIVED 0.95",
    "statusClass": "derived",
    "section": "1. Fundamental Physics",
    "sourceLine": 42,
    "falsifier": "Proof that the optical/Randers mapping fails for null propagation in static/stationary gravity, or that gravity in that domain requires non-optical medium structure.",
    "premise": "Hostile audit (2026-03-27): the exact local theorem is narrower than the old row title",
    "scopeNote": "Proof that the optical/Randers mapping fails for null propagation in static/stationary gravity, or that gravity in that domain requires non-optical medium structure.",
    "statusParts": [
      {
        "status": "DERIVED",
        "confidence": 0.95,
        "qualifier": ""
      }
    ],
    "standardPhysics": "GR describes gravity as spacetime curvature. Light deflection, perihelion precession, and Shapiro delay are standard GR predictions verified experimentally.",
    "pfResultUnderNamedPremises": "Null geodesics in static spacetimes map exactly to optical metric refraction. Stationary spacetimes extend via Randers/Finsler metric. Weak-field scalar n(x) reproduces light deflection, perihelion precession, and Shapiro delay.",
    "openPfGap": "The broader 'all forces as refraction' claim is not proven. Only null/stationary gravity is mapped; the extension to non-stationary or strong-field regimes is open."
  },
  {
    "id": "isometry-ji-incompatibility",
    "title": "Isometry-JI incompatibility",
    "status": "CONDITIONAL",
    "confidence": 0.85,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "CONDITIONAL 0.85",
    "statusClass": "conditional",
    "section": "1. Fundamental Physics",
    "sourceLine": 70,
    "falsifier": "A non-uniform state whose full Euclidean norm is preserved under T³.",
    "premise": "J-I coupling (Postulate D / H7+H17+H18)",
    "scopeNote": "*(added 2026-06-29)*",
    "statusParts": [
      {
        "status": "CONDITIONAL",
        "confidence": 0.85,
        "qualifier": ""
      }
    ],
    "standardPhysics": "No standard physics analog. The incompatibility between isometry and contraction is a mathematical observation.",
    "pfResultUnderNamedPremises": "Lean 4 proven: T³ strictly decreases full Euclidean norm for any non-uniform state. J-I dynamics cannot be isometric (isometry requires ‖λ‖=1; J-I has real eigenvalues → contraction).",
    "openPfGap": "Conditional on J-I coupling (Postulate D / H7+H17+H18). The physical implications for PF medium dynamics are not fully explored."
  },
  {
    "id": "isometry-reversibility",
    "title": "H14 + H15 + H16 → H1 (isometry implies reversibility)",
    "status": "CONDITIONAL",
    "confidence": 0.85,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "CONDITIONAL 0.85",
    "statusClass": "conditional",
    "section": "1. Fundamental Physics",
    "sourceLine": 71,
    "falsifier": "A counterexample medium satisfying H14+H15+H16 but lacking reversibility.",
    "premise": "H14 (isometry), H15 (metric identity), H16 (metric reflexivity)",
    "scopeNote": "*(added 2026-06-29)*",
    "statusParts": [
      {
        "status": "CONDITIONAL",
        "confidence": 0.85,
        "qualifier": ""
      }
    ],
    "standardPhysics": "In standard physics, isometric transformations are reversible by definition. This is a standard mathematical fact.",
    "pfResultUnderNamedPremises": "Lean 4 machine-verified: if medium is isometric (H14), obeys metric identity (H15), and metric reflexivity (H16), then propagation is reversible.",
    "openPfGap": "The premises H14, H15, H16 are explicit assumptions about the medium. Their derivation from Axioms 1-3 is not addressed in this theorem."
  },
  {
    "id": "koide-entropy",
    "title": "Koide U(3) entropy selector",
    "status": "ARGUED",
    "confidence": 0.72,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "ARGUED 0.72",
    "statusClass": "argued",
    "section": "1. Fundamental Physics",
    "sourceLine": 45,
    "falsifier": "A better-motivated PF selector on the same `u(1)/su(3)` space choosing a different point; proof that the relevant decomposition is not the scalar/traceless split; or proof that PF coherence dynamics d",
    "premise": "Codex audit (2026-04-15): the refined Route A over the scalar/traceless `u(3)=u(1)⊕su(3)` split is mathematically clean but not yet PF-derived as a...",
    "scopeNote": "A better-motivated PF selector on the same `u(1)/su(3)` space choosing a different point; proof that the relevant decomposition is not the scalar/traceless split; or proof that PF coherence dynamics d",
    "statusParts": [
      {
        "status": "ARGUED",
        "confidence": 0.72,
        "qualifier": ""
      }
    ],
    "standardPhysics": "No standard physics analog. Shannon entropy applied to mass matrices is not a standard particle physics technique.",
    "pfResultUnderNamedPremises": "For diagonal amplitude matrix X, binary sector weight p = ||u(1)-part||²/||X||² satisfies p = 1/(3Q), and Shannon entropy S(p) is uniquely maximized at p=1/2, implying Q=2/3.",
    "openPfGap": "That Axiom 3 or PF vacuum dynamics must maximize this particular entropy in this particular split is not shown. The selector principle is not PF-derived."
  },
  {
    "id": "koide-leptons",
    "title": "Koide Law for Charged Leptons (Q = 2/3) — geometric identity",
    "status": "EXACT IDENTITY",
    "confidence": 0.95,
    "isSplit": true,
    "isStandardMath": false,
    "badge": "EXACT IDENTITY 0.95",
    "statusClass": "exact-identity",
    "section": "1. Fundamental Physics",
    "sourceLine": 44,
    "falsifier": "Proof that the 120° equal-strength resonance geometry does not imply `Q = 2/3`, or a contradiction in the Foot-radius step, or a charged-lepton mass measurement drifting > 3σ from `Q = 2/3`.",
    "premise": "Geometric theorem: three equal-strength resonances at 120° force the Foot-radius relation and yield `Q = 2/3` exactly",
    "scopeNote": "*(row clarified 2026-06-16 per Codex audit)*",
    "statusParts": [
      {
        "status": "EXACT IDENTITY",
        "confidence": 0.95,
        "qualifier": "geometry"
      },
      {
        "status": "OPEN",
        "confidence": null,
        "qualifier": "physical vacuum selection"
      }
    ],
    "standardPhysics": "Koide's formula Q = 2/3 is an empirical relation among charged lepton masses, discovered by Yoshio Koide in 1981. No standard physics derivation exists.",
    "pfResultUnderNamedPremises": "Three equal-strength resonances at 120° force the Foot-radius relation and yield Q = 2/3 exactly as a geometric identity. Equal-amplitude premise underwritten by shared U(1)_em coupling.",
    "openPfGap": "Why the physical charged-lepton vacuum selects the equal-norm point is OPEN. The identity is exact given the premise; deriving the premise from PF dynamics is the open gap."
  },
  {
    "id": "koide-phase",
    "title": "Koide Phase (\\(\\delta_0 \\bmod 2\\pi/3 \\approx 2/9\\))",
    "status": "EMPIRICAL",
    "confidence": 0.65,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "EMPIRICAL 0.65",
    "statusClass": "empirical",
    "section": "1. Fundamental Physics",
    "sourceLine": 47,
    "falsifier": "Independent recalculation showing δ is not close to 2/9; or audited proof that no PF-native selector can produce δ = 2/9; or selector derivation producing δ ≠ 2/9.",
    "premise": "Wave 5 (2026-03-25): `koide_phase_scan.py` confirms δ_exact = 0.222229631490 rad, δ−2/9 = 7.4×10⁻⁶ (0.003%)",
    "scopeNote": "Independent recalculation showing δ is not close to 2/9; or audited proof that no PF-native selector can produce δ = 2/9; or selector derivation producing δ ≠ 2/9.",
    "statusParts": [
      {
        "status": "EMPIRICAL",
        "confidence": 0.65,
        "qualifier": ""
      }
    ],
    "standardPhysics": "The Koide phase δ ≈ 0.22223 rad is an empirical parameter of the charged lepton mass matrix. No standard physics prediction exists.",
    "pfResultUnderNamedPremises": "PF predicts δ = 2/9 exactly. Algebraic check confirms δ_Koide = 2/9 is measurement-consistent (0.029σ). Pre-registered prediction: any selector derivation must output δ = 2/9 uniquely.",
    "openPfGap": "No PF-native selector currently exists. T-022 (Casimir selector) and T-021 (RG audit) both returned honest negatives. The 2/9 value remains empirical, not derived."
  },
  {
    "id": "koide-u3-maximization",
    "title": "U(3) Entropy Maximization",
    "status": "ARGUED",
    "confidence": 0.75,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "ARGUED 0.75",
    "statusClass": "argued",
    "section": "1. Fundamental Physics",
    "sourceLine": 46,
    "falsifier": "² is mathematically maximized at p=1/2, matching the Q=2/3 mass distribution.",
    "premise": "0.5 The ratio p =  U(1)  ²/  X ",
    "scopeNote": "² is mathematically maximized at p=1/2, matching the Q=2/3 mass distribution.",
    "statusParts": [
      {
        "status": "ARGUED",
        "confidence": 0.75,
        "qualifier": ""
      }
    ],
    "standardPhysics": "No standard physics analog. U(3) entropy maximization over mass matrices is PF-specific.",
    "pfResultUnderNamedPremises": "The ratio p = ||U(1)||²/||X||² is mathematically maximized at p=1/2, matching the Q=2/3 mass distribution. Clean algebraic result over the scalar/traceless u(3) split.",
    "openPfGap": "PF does not yet derive why this entropy should be maximized. The physical selector mechanism remains unidentified."
  },
  {
    "id": "life-coherence",
    "title": "Life = maintained coherence against entropy",
    "status": "ARGUED",
    "confidence": 0.72,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "ARGUED 0.72",
    "statusClass": "argued",
    "section": "2. Biological & Cognitive Systems",
    "sourceLine": 77,
    "falsifier": "A robust living system with no measurable coherence-maintenance / nonequilibrium organization at any functional scale.",
    "premise": "`chemistry_biology_bridge.md`: PF supports life as active coherence maintenance in an open nonequilibrium system; compatible with photosynthetic co...",
    "scopeNote": "A robust living system with no measurable coherence-maintenance / nonequilibrium organization at any functional scale.",
    "statusParts": [
      {
        "status": "ARGUED",
        "confidence": 0.72,
        "qualifier": ""
      }
    ],
    "standardPhysics": "Biology studies life as a thermodynamic phenomenon. Schrödinger's 'What is Life?' introduced negative entropy. Modern biology studies nonequilibrium systems.",
    "pfResultUnderNamedPremises": "PF supports life as active coherence maintenance in an open nonequilibrium system. Compatible with photosynthetic coherence and enzyme tunneling.",
    "openPfGap": "Does not derive a universal Fröhlich mechanism or a numeric life threshold. The specific PF variable distinguishing life from non-life is not identified."
  },
  {
    "id": "n3-cp-violation",
    "title": "N=3 → CP Violation (Structural Bridge)",
    "status": "ARGUED",
    "confidence": 0.7,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "ARGUED 0.7",
    "statusClass": "argued",
    "section": "1. Fundamental Physics",
    "sourceLine": 49,
    "falsifier": "PF's N=3 derivation is falsified; or a 2-generation universe with CP violation is discovered; or the CKM phase is measured at exactly δ=0 or δ=π (CP-conserving values).",
    "premise": "The CKM matrix for N=3 contains exactly one complex phase; for N=2 there is no complex phase",
    "scopeNote": "*(added 2026-07-02 by Hermes)*",
    "statusParts": [
      {
        "status": "ARGUED",
        "confidence": 0.7,
        "qualifier": ""
      }
    ],
    "standardPhysics": "The CKM matrix for 3 generations contains exactly one complex phase, enabling CP violation. For 2 generations, no CP violation is possible. This is standard CKM physics.",
    "pfResultUnderNamedPremises": "PF derives N=3 as the unique stable generation count (CONDITIONAL 0.88). Therefore PF predicts CP violation in quark mixing is structurally possible — 3 is the minimum for a complex CKM phase.",
    "openPfGap": "This does NOT derive the phase magnitude (δ ≈ 1.2 rad). Only the existence/possibility of CP violation is addressed, not its measured value."
  },
  {
    "id": "neutrino-koide",
    "title": "Neutrino Koide non-universality",
    "status": "EMPIRICAL",
    "confidence": 0.95,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "EMPIRICAL 0.95",
    "statusClass": "empirical",
    "section": "1. Fundamental Physics",
    "sourceLine": 63,
    "falsifier": "Future precision neutrino mass measurement showing $Q_\\nu$ within 1% of 2/3, which would falsify the electromagnetic-specificity interpretation.",
    "premise": "April 2026 confirmed: $Q_{NO} = 0.549622$ (17.5% from 2/3), $Q_{IO} = 0.479016$ (28.2% from 2/3)",
    "scopeNote": "Future precision neutrino mass measurement showing $Q_\\nu$ within 1% of 2/3, which would falsify the electromagnetic-specificity interpretation.",
    "statusParts": [
      {
        "status": "EMPIRICAL",
        "confidence": 0.95,
        "qualifier": ""
      }
    ],
    "standardPhysics": "Neutrino masses are not precisely measured. Standard physics does not predict Koide-type relations for neutrinos.",
    "pfResultUnderNamedPremises": "Q_NO = 0.549622 (17.5% from 2/3), Q_IO = 0.479016 (28.2% from 2/3). Universality falsified at >5% threshold. Positive scope-delimiting result: Koide is EM-sector specific.",
    "openPfGap": "The mechanism for why weak-sector neutrinos lack the EM locking is argued but not formally derived. Precision neutrino mass measurements could shift Q_ν."
  },
  {
    "id": "pfentropy-decreases",
    "title": "PFEntropy decreases under T³",
    "status": "CONDITIONAL",
    "confidence": 0.85,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "CONDITIONAL 0.85",
    "statusClass": "conditional",
    "section": "1. Fundamental Physics",
    "sourceLine": 68,
    "falsifier": "A state in the D=3 residue subspace whose residue norm does not shrink under T³.",
    "premise": "J-I coupling (Postulate D / H7+H17+H18), T³ operator",
    "scopeNote": "*(added 2026-06-29)*",
    "statusParts": [
      {
        "status": "CONDITIONAL",
        "confidence": 0.85,
        "qualifier": ""
      }
    ],
    "standardPhysics": "No standard physics analog. PF entropy is a PF-specific quantity.",
    "pfResultUnderNamedPremises": "Lean 4 proven: one three-step J-I cycle scales residue norm by 1/8, so PF entropy strictly decreases for any non-uniform state. Premises: J-I coupling (Postulate D / H7+H17+H18), T³ operator.",
    "openPfGap": "The result is conditional on Postulate D / H7+H17+H18, which are not derived from Axioms 1-3. The physical interpretation of PF entropy decrease is argued but not fully connected to thermodynamic entropy."
  },
  {
    "id": "propagation-lagrangian",
    "title": "Propagation Lagrangian",
    "status": "CONDITIONAL",
    "confidence": 0.72,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "CONDITIONAL 0.72",
    "statusClass": "conditional",
    "section": "1. Fundamental Physics",
    "sourceLine": 57,
    "falsifier": "Proof that the scalar-medium EFT branch is not viable, or that the minimal `λχT` ansatz fails as the correct low-energy representative even within that class.",
    "premise": "Axioms 1–3 strongly motivate a scalar-tensor EFT class for the propagation medium",
    "scopeNote": "Proof that the scalar-medium EFT branch is not viable, or that the minimal `λχT` ansatz fails as the correct low-energy representative even within that class.",
    "statusParts": [
      {
        "status": "CONDITIONAL",
        "confidence": 0.72,
        "qualifier": ""
      }
    ],
    "standardPhysics": "Scalar-tensor theories (Brans-Dicke, etc.) are well-known extensions of GR. The minimal scalar ansatz L = ½(∂χ)² - V(χ) + λχT is standard EFT.",
    "pfResultUnderNamedPremises": "Axioms 1-3 strongly motivate a scalar-tensor EFT class. L_prop = ½(∂χ)² - V(χ) + λχT is the minimal scalar ansatz with correct Euler-Lagrange equations and sound Brans-Dicke mapping.",
    "openPfGap": "The scalar-field branch, exact λχT coupling, and V(χ) form are not uniquely forced by the axioms. Multiple EFT candidates fit within the same axiomatic constraints."
  },
  {
    "id": "pythagorean-decomposition",
    "title": "Full-norm Pythagorean decomposition",
    "status": "DERIVED",
    "confidence": 0.95,
    "isSplit": false,
    "isStandardMath": true,
    "badge": "STANDARD MATH 0.95",
    "statusClass": "standard-math",
    "section": "1. Fundamental Physics",
    "sourceLine": 69,
    "falsifier": "A proof that the projection decomposition does not yield orthogonal components.",
    "premise": "Vector space projection structure (no physics premises)",
    "scopeNote": "*(added 2026-06-29)*",
    "statusParts": [
      {
        "status": "DERIVED",
        "confidence": 0.95,
        "qualifier": ""
      }
    ],
    "standardPhysics": "The Pythagorean theorem for orthogonal projections is standard linear algebra. ‖x‖² = ‖P₀x‖² + ‖Qx‖² for orthogonal projections P₀, Q.",
    "pfResultUnderNamedPremises": "Lean 4 proven: full norm Pythagorean decomposition with no physics premises. Pure linear algebra — orthogonal projection in finite-dimensional inner product space.",
    "openPfGap": "No open PF gap — this is a pure mathematical result. Its physical application to PF states is downstream."
  },
  {
    "id": "qcd-confinement",
    "title": "QCD Confinement",
    "status": "ARGUED",
    "confidence": 0.72,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "ARGUED 0.72",
    "statusClass": "argued",
    "section": "1. Fundamental Physics",
    "sourceLine": 59,
    "falsifier": "Evidence that confinement requires a genuinely new PF coherence scale, or a threshold-aware higher-loop analysis showing the PF RG bridge does not land on the physical confinement scale even with the ",
    "premise": "PF identifies a plausible RG mechanism in which the confinement radius is dynamically generated from `λ_c`: `r_conf = λ_c × exp(2π/b₀α_s(λ_c))`",
    "scopeNote": "Evidence that confinement requires a genuinely new PF coherence scale, or a threshold-aware higher-loop analysis showing the PF RG bridge does not land on the physical confinement scale even with the ",
    "statusParts": [
      {
        "status": "ARGUED",
        "confidence": 0.72,
        "qualifier": ""
      }
    ],
    "standardPhysics": "QCD confinement is well-established phenomenologically but not analytically proven from first principles. Lattice QCD confirms confinement numerically.",
    "pfResultUnderNamedPremises": "PF identifies a plausible RG mechanism: r_conf = λ_c × exp(2π/b₀α_s(λ_c)). Supports interpretation of confinement as dynamically generated, not a third fundamental coherence ceiling.",
    "openPfGap": "The current chain uses calibrated λ_c, empirical α_s(λ_c), and a 1-loop estimate that overshoots (2.2 fm vs ~0.9 fm). Higher-loop corrections not yet shown to fix the discrepancy."
  },
  {
    "id": "sleep-constant",
    "title": "8h Sleep Constant",
    "status": "ARGUED",
    "confidence": 0.72,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "ARGUED 0.72",
    "statusClass": "argued",
    "section": "2. Biological & Cognitive Systems",
    "sourceLine": 79,
    "falsifier": "Quantitative evidence that optimal recovery fractions are not near `1/3` in high-capacity systems, or proof that PF topology does not constrain encode/recover duty cycles in the claimed way.",
    "premise": "Hostile audit (2026-03-28): PF strongly supports the need for offline consolidation, and the T-010 model gives a plausible `~2/3` active fraction f...",
    "scopeNote": "Quantitative evidence that optimal recovery fractions are not near `1/3` in high-capacity systems, or proof that PF topology does not constrain encode/recover duty cycles in the claimed way.",
    "statusParts": [
      {
        "status": "ARGUED",
        "confidence": 0.72,
        "qualifier": ""
      }
    ],
    "standardPhysics": "Sleep is studied in neuroscience. The 8-hour human sleep need is empirical, not derived from first principles. Sleep serves memory consolidation and metabolic cleanup.",
    "pfResultUnderNamedPremises": "PF supports the need for offline consolidation. T-010 model gives a plausible ~2/3 active fraction for (2,1)-weighted encode/recover systems.",
    "openPfGap": "The exact 8-hour constant is not derived from Axioms 1-3. The chain mixes unresolved T2/T3 structure, an analogical wake/sleep mapping, and a sandbox model with built-in recovery asymmetry."
  },
  {
    "id": "three-generations",
    "title": "Three Generations",
    "status": "CONDITIONAL",
    "confidence": 0.88,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "CONDITIONAL 0.88",
    "statusClass": "conditional",
    "section": "1. Fundamental Physics",
    "sourceLine": 48,
    "falsifier": "Formal proof that either the numerator or denominator theorem fails in PF, or a different justified counting rule leading to `N ≠ 3`.",
    "premise": "Once the numerator theorem (the physical `(2,1)` closure-weight branch) and the denominator theorem `M = 3` are both granted, the algebraic step is...",
    "scopeNote": "Formal proof that either the numerator or denominator theorem fails in PF, or a different justified counting rule leading to `N ≠ 3`.",
    "statusParts": [
      {
        "status": "CONDITIONAL",
        "confidence": 0.88,
        "qualifier": ""
      }
    ],
    "standardPhysics": "The Standard Model has 3 generations of fermions. No standard physics explanation for why exactly 3 exists.",
    "pfResultUnderNamedPremises": "Given the (2,1) closure-weight branch (numerator) and M=3 (denominator), Q(N) = 2N/(2N+3) = 2/3 → N = 3 exactly. Assembly theorem is clean with no hidden algebraic step.",
    "openPfGap": "T1: physical realization of weight-2 branch not proven. T2: M=3 not derived from PF axioms alone. Both sides have explicit open gaps despite the clean conditional assembly."
  },
  {
    "id": "top-quark-limit",
    "title": "Top Quark Limit",
    "status": "ARGUED",
    "confidence": 0.85,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "ARGUED 0.85",
    "statusClass": "argued",
    "section": "1. Fundamental Physics",
    "sourceLine": 50,
    "falsifier": "Discovery of a heavier stable quark ($m > 173$ GeV).",
    "premise": "$m_t$ lifetime ($5 \\times 10^{-25}$s) matches coherence ceiling threshold.",
    "scopeNote": "Discovery of a heavier stable quark ($m > 173$ GeV).",
    "statusParts": [
      {
        "status": "ARGUED",
        "confidence": 0.85,
        "qualifier": ""
      }
    ],
    "standardPhysics": "The top quark mass ~172.5 GeV is measured. The top is the heaviest known quark with a very short lifetime (~5×10⁻²⁵ s). No standard physics explanation for why it's the heaviest.",
    "pfResultUnderNamedPremises": "m_t lifetime matches the coherence ceiling threshold. The top quark sits at the maximum frequency where wavelength exceeds coherence length (Axiom 3).",
    "openPfGap": "The precise mass value 172.5 GeV is not derived from PF. The coherence ceiling gives a qualitative argument, not a quantitative prediction."
  },
  {
    "id": "top-tau-coupling",
    "title": "Top/Tau coupling",
    "status": "EMPIRICAL",
    "confidence": 0.9,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "EMPIRICAL 0.9",
    "statusClass": "empirical",
    "section": "1. Fundamental Physics",
    "sourceLine": 51,
    "falsifier": "Measurement of Top or Tau mass shifting > 0.5% from current.",
    "premise": "$m_t/m_\\tau \\approx \\alpha^{-1}/\\sqrt{2}$ (50.13% robustness in T-008).",
    "scopeNote": "Measurement of Top or Tau mass shifting > 0.5% from current.",
    "statusParts": [
      {
        "status": "EMPIRICAL",
        "confidence": 0.9,
        "qualifier": ""
      }
    ],
    "standardPhysics": "The top/tau mass ratio m_t/m_τ ≈ 3247 is an empirical observation. No standard physics explanation exists.",
    "pfResultUnderNamedPremises": "m_t/m_τ ≈ α⁻¹/√2 (50.13% robustness in T-008). The coupling ratio connects the heaviest quark to the heaviest lepton through the fine structure constant.",
    "openPfGap": "The derivation path from PF axioms to this specific ratio is not complete. The 50.13% robustness indicates a real but not decisive signal."
  },
  {
    "id": "topological-weights",
    "title": "(2,1) Topological Weights",
    "status": "DERIVED",
    "confidence": 0.95,
    "isSplit": true,
    "isStandardMath": false,
    "badge": "DERIVED 0.95",
    "statusClass": "derived",
    "section": "1. Fundamental Physics",
    "sourceLine": 43,
    "falsifier": "Proof that the closure-order interpretation is wrong, or that the Family C coherence bridge fails audit, or a derivation showing only the trivial branch is physically realizable in PF.",
    "premise": "**Hostile audit (2026-03-28)**: established the intended closure-order target from 3D rotation topology",
    "scopeNote": "Proof that the closure-order interpretation is wrong, or that the Family C coherence bridge fails audit, or a derivation showing only the trivial branch is physically realizable in PF.",
    "statusParts": [
      {
        "status": "DERIVED",
        "confidence": 0.95,
        "qualifier": "kernel-only topological obstruction"
      },
      {
        "status": "CONDITIONAL",
        "confidence": 0.85,
        "qualifier": "physical realization"
      }
    ],
    "standardPhysics": "SU(2) → SO(3) is a 2:1 covering map with kernel {±1}. The fundamental group π_1(SO(3)) ≅ Z_2 is standard algebraic topology.",
    "pfResultUnderNamedPremises": "Lean 4 kernel certifies: quatToSO3 g = 1 → order g ∈ {1,2}. The kernel obstruction is machine-verified with 0 sorrys. Physical realization of both branches remains CONDITIONAL 0.85.",
    "openPfGap": "Full covering-space/path-lifting formalization is not in Lean. Physical realization bridge (non-redundancy hypothesis A_NR) not derived from Axioms 1-3."
  },
  {
    "id": "two-thirds-efficiency",
    "title": "2/3 Efficiency Ratio",
    "status": "INTUITION",
    "confidence": 0.5,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "INTUITION 0.5",
    "statusClass": "intuition",
    "section": "2. Biological & Cognitive Systems",
    "sourceLine": 81,
    "falsifier": "Finding a more efficient topological output ratio.",
    "premise": "\"Takes TWO to make THREE\" — Greg's 2/3 exchange rate.",
    "scopeNote": "Finding a more efficient topological output ratio.",
    "statusParts": [
      {
        "status": "INTUITION",
        "confidence": 0.5,
        "qualifier": ""
      }
    ],
    "standardPhysics": "No standard physics analog. The 2/3 efficiency ratio is PF-specific.",
    "pfResultUnderNamedPremises": "The (2,1) topological weight structure suggests a 2/3 encode/recover duty cycle. Connected to the sleep constant claim.",
    "openPfGap": "This is an intuition-level claim. The 2/3 ratio is not derived from Axioms 1-3. The connection to sleep architecture is analogical."
  },
  {
    "id": "variable-c",
    "title": "Variable c Prediction",
    "status": "ARGUED",
    "confidence": 0.65,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "ARGUED 0.65",
    "statusClass": "argued",
    "section": "1. Fundamental Physics",
    "sourceLine": 58,
    "falsifier": "Cassini-violating Shapiro delay, or direct measurement of c_local = c₀ at sub-solar-system scales.",
    "premise": "c_local = 1/√(1+λχ) from conformal rescaling of the Propagation Lagrangian",
    "scopeNote": "Cassini-violating Shapiro delay, or direct measurement of c_local = c₀ at sub-solar-system scales.",
    "statusParts": [
      {
        "status": "ARGUED",
        "confidence": 0.65,
        "qualifier": ""
      }
    ],
    "standardPhysics": "Variable speed of light theories exist (VSL cosmology) but are not standard. GR predicts c is locally constant; varying c would violate Lorentz invariance.",
    "pfResultUnderNamedPremises": "c_local = 1/√(1+λχ) from conformal rescaling of the Propagation Lagrangian. Constrained by Cassini Shapiro delay to λ ≲ 10⁻²/M_Pl. Testable with SKA/LISA.",
    "openPfGap": "The bound λ ≲ 10⁻²/M_Pl is consistent with all data but not yet tested at the predicted sensitivity. The exact value of λ is not derived from PF."
  },
  {
    "id": "weinberg-angle",
    "title": "Weinberg Angle (sin²θ_W)",
    "status": "ARGUED",
    "confidence": 0.65,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "ARGUED 0.65",
    "statusClass": "argued",
    "section": "1. Fundamental Physics",
    "sourceLine": 54,
    "falsifier": "Derivation of coupling ratio g'/g from medium geometry, or scheme selection mechanism.",
    "premise": "Casimir polynomial $x^2 + C_2 x - C_2 = 0$ yields ratio $R = 1 - x_+(1/2)/x_+(1) = 0.22310$ exactly",
    "scopeNote": "*(demoted from DERIVED 2026-06-16 per Codex audit)*",
    "statusParts": [
      {
        "status": "ARGUED",
        "confidence": 0.65,
        "qualifier": ""
      }
    ],
    "standardPhysics": "The Weinberg angle sin²θ_W ≈ 0.22337 (on-shell) is a measured parameter of the electroweak sector. It relates the W and Z boson masses. No first-principles derivation exists in the Standard Model.",
    "pfResultUnderNamedPremises": "Casimir polynomial x² + C₂x - C₂ = 0 yields R = 1 - x_+(1/2)/x_+(1) = 0.22310. Axiom 3b (Minimal Winding) selects k=1. Matches PDG on-shell to 0.13σ.",
    "openPfGap": "Scheme selection (on-shell vs MS-bar) not derived. Look-elsewhere scan finds P(random hit) ≈ 0.46, materially lowering confidence. The Casimir result is a candidate, not a proved derivation."
  }
],
      definitions: [
  {
    "id": "axioms",
    "title": "The Three Axioms",
    "status": "CANONICAL v1.0 — passed Codex final audit 2026-04-30",
    "file": "definitions/axioms.md",
    "sourceLine": 1
  },
  {
    "id": "causal-velocity",
    "title": "Causal Velocity",
    "status": "CANONICAL v1.0 - passed Codex final audit 2026-04-29",
    "file": "definitions/causal_velocity.md",
    "sourceLine": 1
  },
  {
    "id": "coherence",
    "title": "Coherence",
    "status": "CANONICAL v1.0 - passed Codex final audit 2026-04-29",
    "file": "definitions/coherence.md",
    "sourceLine": 1
  },
  {
    "id": "consciousness",
    "title": "Consciousness",
    "status": "CANDIDATE — INTUITION 0.48 — NOT CANONICAL",
    "file": "definitions/consciousness.md",
    "sourceLine": 1
  },
  {
    "id": "consciousness-metric-program",
    "title": "Consciousness Metric Program",
    "status": "ACTIVE CANDIDATE — not canonical",
    "file": "definitions/consciousness_metric_program.md",
    "sourceLine": 1
  },
  {
    "id": "coupling",
    "title": "Coupling",
    "status": "CANONICAL v1.0 — passed Codex final audit 2026-04-30",
    "file": "definitions/coupling.md",
    "sourceLine": 1
  },
  {
    "id": "decoherence",
    "title": "Decoherence",
    "status": "CANONICAL v1.0 — passed Codex final audit 2026-04-30",
    "file": "definitions/decoherence.md",
    "sourceLine": 1
  },
  {
    "id": "energy",
    "title": "Energy",
    "status": "CANONICAL v1.0 - passed Codex final audit 2026-04-29",
    "file": "definitions/energy.md",
    "sourceLine": 1
  },
  {
    "id": "field",
    "title": "Field",
    "status": "CANONICAL v1.0 — passed Codex final audit 2026-04-30",
    "file": "definitions/field.md",
    "sourceLine": 1
  },
  {
    "id": "forces",
    "title": "Forces",
    "status": "CANONICAL v1.0 - passed Codex final audit 2026-04-29",
    "file": "definitions/forces.md",
    "sourceLine": 1
  },
  {
    "id": "gradient",
    "title": "Gradient",
    "status": "CANONICAL v1.0 - passed Codex final audit 2026-04-29",
    "file": "definitions/gradient.md",
    "sourceLine": 1
  },
  {
    "id": "information",
    "title": "Information",
    "status": "CANONICAL v1.0 - passed Codex final audit 2026-04-29",
    "file": "definitions/information.md",
    "sourceLine": 1
  },
  {
    "id": "matter",
    "title": "Matter",
    "status": "CANONICAL v1.0 - passed Codex final audit 2026-04-29",
    "file": "definitions/matter.md",
    "sourceLine": 1
  },
  {
    "id": "measurement",
    "title": "Measurement",
    "status": "CANONICAL v1.0 — passed Codex final audit 2026-04-30",
    "file": "definitions/measurement.md",
    "sourceLine": 1
  },
  {
    "id": "medium",
    "title": "The Medium",
    "status": "CANONICAL v1.0 — passed Codex final audit 2026-04-28",
    "file": "definitions/medium.md",
    "sourceLine": 1
  },
  {
    "id": "minimum-substrate",
    "title": "Minimum Substrate",
    "status": "CANONICAL v1.0 - passed Codex final audit 2026-04-29",
    "file": "definitions/minimum_substrate.md",
    "sourceLine": 1
  },
  {
    "id": "mode",
    "title": "Mode",
    "status": "CANONICAL v1.0 - passed Codex final audit 2026-04-29",
    "file": "definitions/mode.md",
    "sourceLine": 1
  },
  {
    "id": "observer",
    "title": "Observer",
    "status": "CANONICAL v1.0 - passed Codex final audit 2026-04-29",
    "file": "definitions/observer.md",
    "sourceLine": 1
  },
  {
    "id": "propagation",
    "title": "Propagation",
    "status": "CANONICAL v1.0 - passed Codex final audit 2026-04-29",
    "file": "definitions/propagation.md",
    "sourceLine": 1
  },
  {
    "id": "state",
    "title": "State",
    "status": "CANONICAL v1.0 — passed Codex final audit 2026-04-30",
    "file": "definitions/state.md",
    "sourceLine": 1
  },
  {
    "id": "time",
    "title": "Time",
    "status": "CANONICAL v1.0 - passed Codex final audit 2026-04-29",
    "file": "definitions/time.md",
    "sourceLine": 1
  }
]
    };
  }
  // All three names point to deterministic views of the same authority
  window.PFDataGraph = window.PFClaimsData;
})();