/**
 * data.claims.js — Claude's information architecture layer
 * Generated: 2026-05-06
 * Source: CLAIMS.md (2026-04-28), definitions/ canonical files
 * Role: Story / Audit / Math copy per claim. AntiGravity wires to UI.
 */
(function () {
  'use strict';

  // ─── STATUS CONSTANTS ─────────────────────────────────────────────────────────
  const STATUS = {
    DERIVED:      { label: "DERIVED",      color: "green",  ring: true  },
    CONDITIONAL:  { label: "CONDITIONAL",  color: "amber",  ring: true  },
    ARGUED:       { label: "ARGUED",       color: "amber",  ring: false },
    EMPIRICAL:    { label: "EMPIRICAL",    color: "gold",   ring: false },
    INTUITION:    { label: "INTUITION",    color: "gray",   ring: false },
    CANONICAL:    { label: "CANONICAL",    color: "white",  ring: true  },
    NOGO:         { label: "NO-GO",        color: "red",    ring: false },
    PARTIAL:      { label: "PARTIAL DERIVATION", color: "amber", ring: false },
  };

  // ─── CANONICAL DEFINITIONS (19) ───────────────────────────────────────────────
  const DEFINITIONS = [
    {
      id: "medium",
      title: "The Medium",
      status: STATUS.CANONICAL,
      file: "definitions/medium.md",
      oneLiner: "The rule-structure that lets distinguishable change propagate, cohere, curve, and become stable modes.",
      storyLine: "Space is not a dead void. It is a physical substrate—the water of the cosmic ocean. The Medium is the set of rules that decides how change can travel, what patterns can survive, and which ones collapse. You are not a thing inside the Medium; you are a stable ripple in it.",
      auditLine: "Defined by functional roles — causal, state-bearing, propagative, dynamic, coherent, geometric, quantizing, quantum-compatible, Lorentz-compatible, measurable. Not a substance claim. Status: CANONICAL v1.0, passed Codex final audit 2026-04-28.",
      notThis: "Not the aether. Not a preferred frame. Not an undetectable background. Every claimed property of the Medium must map to an observable consequence.",
      dependencies: [],
    },
    {
      id: "axioms",
      title: "The Three Axioms",
      status: STATUS.CANONICAL,
      file: "definitions/axioms.md",
      oneLiner: "The root commitments of the framework: propagation is fundamental, causal influence has a finite velocity, and coherence is required for stable structure.",
      storyLine: "The universe is not made of things that move. It is made of movement that, under the right conditions of coherence, appears to be things. Axioms 1, 2, and 3 define the starting rules: change propagates, propagation is bounded, and only coherent patterns survive.",
      auditLine: "Records Axiom 1, Axiom 2, Axiom 3, and Axiom 3b as selection principles. Numerical claims, confidence scores, and unfinished derivation bridges remain in CLAIMS.md and derivation audits. Status: CANONICAL v1.0.",
      notThis: "Not a proof of every downstream claim. The axioms define the permitted starting vocabulary; CLAIMS.md controls which derived results actually survive audit.",
      dependencies: [],
    },
    {
      id: "propagation",
      title: "Propagation",
      status: STATUS.CANONICAL,
      file: "definitions/propagation.md",
      oneLiner: "Finite-speed causal transmission of a distinguishable state change through the Medium.",
      storyLine: "Everything is propagation. It is how change gets from here to there—not by teleportation, but by a causal ripple bounded by the Medium's speed limit. Propagation is the universe's most basic event; everything else is downstream.",
      auditLine: "The framework's founding primitive. Not the same as motion (displacement over time). The canonical definitions formalize what propagation means; propagation.md is the bootstrap-completion step. Axiom 1. Status: CANONICAL v1.0.",
      notThis: "Not instantaneous action at a distance. Not a metaphor. The causal front velocity is the hard physical bound.",
      dependencies: ["medium", "causal-velocity", "coherence", "mode", "energy", "time"],
    },
    {
      id: "coherence",
      title: "Coherence",
      status: STATUS.CANONICAL,
      file: "definitions/coherence.md",
      oneLiner: "Stable relational structure among states under evolution — what lets a pattern remain distinguishable as it changes.",
      storyLine: "Coherence is the necessary condition for structure. Every structure in the universe—from a hydrogen atom to a human brain—is a region where coherence exceeds the background. It is the property that keeps patterns from dissolving into noise.",
      auditLine: "Four distinct technical layers: phase/wave coherence, quantum coherence, structural/dynamical coherence, self-referential coherence (last one: not yet formalized for PF). Do not conflate them. Domain-specific metric required. Status: CANONICAL v1.0.",
      notThis: "Coherence is not one universal scalar. A laser, an atom, an organism, and a brain are not coherent in the same technical sense. Substituting one layer for another without naming the bridge is an error.",
      dependencies: ["medium", "propagation", "mode"],
    },
    {
      id: "causal-velocity",
      title: "Causal Velocity",
      status: STATUS.CANONICAL,
      file: "definitions/causal_velocity.md",
      oneLiner: "The maximum speed at which controllable causal influence can propagate through the Medium.",
      storyLine: "c is not a speed limit imposed from outside. It is the speed of the Medium's own causal structure. Nothing travels faster than that—not because we lack the technology, but because 'faster than causal influence' is not a physical operation.",
      auditLine: "Causal velocity is the Medium's structural constant. Distinguished from phase velocity (which can exceed it without FTL signaling). Status: CANONICAL v1.0.",
      notThis: "Not merely the speed of light. The causal velocity concept is prior to electromagnetism — EM light happens to travel at it.",
      dependencies: ["medium", "propagation"],
    },
    {
      id: "mode",
      title: "Mode",
      status: STATUS.CANONICAL,
      file: "definitions/mode.md",
      oneLiner: "A stable, self-sustaining pattern of propagation — what we call a particle is a stable mode.",
      storyLine: "Matter is not stuff; it is a knot. A particle is a stable, repeating, self-reinforcing pattern in the Medium—like a standing wave that has learned how to hold its shape. 'Matter' is the set of modes stable enough to outlast the entropy trying to destroy them.",
      auditLine: "Stability is defined by the Medium's coherence rules and quantization conditions. Not all patterns are modes. Status: CANONICAL v1.0.",
      notThis: "Not a particle in the billiard-ball sense. Not a point. A mode has spatial extent and phase structure.",
      dependencies: ["medium", "propagation", "coherence"],
    },
    {
      id: "energy",
      title: "Energy",
      status: STATUS.CANONICAL,
      file: "definitions/energy.md",
      oneLiner: "The conserved quantity associated with time-translation symmetry of propagation — a bookkeeping tool, not a substance.",
      storyLine: "Energy is not fuel. It is frequency. A particle with more mass doesn't have more 'stuff' inside it; it is simply a knot in the medium that is vibrating at a higher frequency. Noether's symmetry forces us to track this conserved oscillation.",
      auditLine: "Noether's theorem applied to time-translation symmetry of the propagation dynamics. Status: CANONICAL v1.0.",
      notThis: "Not a substance. Not a field by itself. Not mysteriously defined — it is a consequence of symmetry.",
      dependencies: ["medium", "propagation", "time"],
    },
    {
      id: "time",
      title: "Time",
      status: STATUS.CANONICAL,
      file: "definitions/time.md",
      oneLiner: "The ordering and metric of state changes along physical histories.",
      storyLine: "Time is what propagation feels like from inside. It is the ordering and metric of state changes along a physical path. It is not a universal clock, but a record of movement sampling the Medium's wavefront.",
      auditLine: "Proper time and coordinate time are kept separate; SR/GR clock comparisons control the definition. Local-frontier/arrow-of-time language remains bounded by entropy and observer constraints. Status: CANONICAL v1.0.",
      notThis: "Not a universal background parameter. Time is local and causal-order-derived.",
      dependencies: ["medium", "propagation", "causal-velocity"],
    },
    {
      id: "field",
      title: "Field",
      status: STATUS.CANONICAL,
      file: "definitions/field.md",
      oneLiner: "A mapping from Medium states to locally defined quantities — the mathematical object describing the Medium's configuration.",
      storyLine: "A field is not an invisible fluid. It is a distributed physical variable: a way to assign degrees of freedom to points, regions, sites, or links so their states, modes, gradients, and couplings can be described.",
      auditLine: "A field is an assignment of physical degrees of freedom to a domain plus transformation, evolution, and coupling rules. The Medium is not identical to any one field. Status: CANONICAL v1.0.",
      notThis: "Not a new substance added to physics. A field is a description tool.",
      dependencies: ["medium", "propagation"],
    },
    {
      id: "gradient",
      title: "Gradient",
      status: STATUS.CANONICAL,
      file: "definitions/gradient.md",
      oneLiner: "Spatial variation in the Medium's state — the mechanism by which propagation paths bend.",
      storyLine: "A gradient is where the Medium's state varies from place to place. In our framework, gradients are the mechanism by which propagation paths bend. No invisible ropes pull objects; the objects simply follow the path of least resistance through the gradient.",
      auditLine: "The file separates ordinary scalar gradients, Levi-Civita covariant derivatives, gauge-covariant derivatives, and PF interpretation. Christoffel symbols are not treated as simple scalar gradients. Status: CANONICAL v1.0.",
      notThis: "Not action at a distance. Not a separate field. Gradients are the Medium's spatial variation.",
      dependencies: ["medium", "field"],
    },
    {
      id: "forces",
      title: "Forces",
      status: STATUS.CANONICAL,
      file: "definitions/forces.md",
      oneLiner: "An interaction that changes a mode's momentum, trajectory, phase, internal quantum numbers, or field configuration.",
      storyLine: "Forces are not invisible ropes. They are refraction. A massive star bends the local propagation geometry exactly like a glass lens bends light. Every 'force' we measure is actually the bending of propagation in a region where the Medium changes.",
      auditLine: "Standard force structures are preserved: spacetime geometry for gravity, gauge fields for EM/strong/weak. PF gradient/refraction readings are labeled and force-specific, not globally derived. Status: CANONICAL v1.0.",
      notThis: "Not derived for all forces yet. The full 'all forces as refraction' program is aspirational beyond the gravity case.",
      dependencies: ["medium", "gradient", "propagation"],
    },
    {
      id: "matter",
      title: "Matter",
      status: STATUS.CANONICAL,
      file: "definitions/matter.md",
      oneLiner: "Stable resonant modes of the Medium — patterns that persist because the Medium's quantization conditions select them.",
      storyLine: "Matter is not what fills space. Matter is what the Medium does when it vibrates in the right way and the vibration stays. Every particle you have ever touched is a sustained echo.",
      auditLine: "Matter = stable modes. Stability criteria come from the Medium's coherence and quantization conditions. Status: CANONICAL v1.0.",
      notThis: "Not a separate category from fields. Matter is one regime of the Medium's mode structure.",
      dependencies: ["medium", "mode", "coherence"],
    },
    {
      id: "state",
      title: "State",
      status: STATUS.CANONICAL,
      file: "definitions/state.md",
      oneLiner: "A complete specification of a system's relevant degrees of freedom sufficient to determine measurement predictions in a stated context.",
      storyLine: "A state is not a mystical snapshot of all reality. It is the operational configuration assigned to a bounded system: which degrees of freedom matter, how they are represented, and which basis or measurement context makes the prediction meaningful.",
      auditLine: "Formal state spaces are domain-specific (quantum states, classical field configurations, etc). Not unified into one PF state space yet. Status: CANONICAL v1.0.",
      notThis: "Not a single universal PF state space. The concept is canonical; the specific state space depends on the domain.",
      dependencies: ["medium", "time"],
    },
    {
      id: "information",
      title: "Information",
      status: STATUS.CANONICAL,
      file: "definitions/information.md",
      oneLiner: "Distinguishability of a state or state change relative to a specified reference or noise background.",
      storyLine: "Information is not a substance moving through wires. It is the amount by which a state, record, or signal narrows the alternatives available in a context. The same event can carry different information relative to different references.",
      auditLine: "Defines information as distinguishability/correlation relative to a reference. Shannon, von Neumann, mutual information, entropy, and thermodynamic claims are kept separate. Status: CANONICAL v1.0.",
      notThis: "Not 'it from bit' in the sense that information is ontologically prior to the Medium. Information is carried by propagation, not the other way around.",
      dependencies: ["medium", "propagation", "causal-velocity", "state"],
    },
    {
      id: "measurement",
      title: "Measurement",
      status: STATUS.CANONICAL,
      file: "definitions/measurement.md",
      oneLiner: "Coupling plus amplification and stabilization that creates a stable accessible record correlated with the measured system.",
      storyLine: "Measurement is not a passive reading of facts. It is a physical process: something couples, the effect is amplified, and a record becomes stable enough to be read.",
      auditLine: "Separates Shannon measurement from von Neumann measurement and keeps Born rule/outcome selection open. Measurement problem is bounded, not solved. Status: CANONICAL v1.0.",
      notThis: "Not solved by PF. Measurement is inherited from quantum mechanics with its full complexity intact.",
      dependencies: ["medium", "state", "information", "coherence"],
    },
    {
      id: "decoherence",
      title: "Decoherence",
      status: STATUS.CANONICAL,
      file: "definitions/decoherence.md",
      oneLiner: "The irreversible loss of relational coherence structure through interaction with an environment.",
      storyLine: "Decoherence is why quantum weirdness disappears at human scale. When a quantum system interacts with its environment, the phase relationships that make quantum behavior possible are redistributed into the environment — effectively lost to anyone who cannot track the whole environment.",
      auditLine: "Standard decoherence theory. PF does not add to or modify the mechanism. Status: CANONICAL v1.0.",
      notThis: "Not wavefunction collapse. Decoherence explains the appearance of collapse without resolving the measurement problem.",
      dependencies: ["coherence", "measurement", "medium"],
    },
    {
      id: "minimum-substrate",
      title: "Minimum Substrate",
      status: STATUS.CANONICAL,
      file: "definitions/minimum_substrate.md",
      oneLiner: "The minimal local quantum dynamical structure sufficient to support the canonical PF stack.",
      storyLine: "A single qubit or qutrit can hold a state, but it cannot be a universe. To support propagation, gradients, separated observers, and causal cones, the substrate needs extended locality: sites, adjacency, finite-speed update, stable modes, and tensor-product nonseparability without faster-than-light signaling.",
      auditLine: "Single finite-dimensional Hilbert spaces fail as whole Mediums. A QCA/local quantum dynamical net is a minimal constructive representative, not the unique substrate of reality. Status: CANONICAL v1.0.",
      notThis: "Not a claim that the universe is literally a specific QCA. Not a proof that d=3 is required. Local d>=2 is only locally sufficient when paired with the full substrate structure.",
      dependencies: ["medium", "coherence", "mode"],
    },
    {
      id: "observer",
      title: "Observer",
      status: STATUS.CANONICAL,
      file: "definitions/observer.md",
      oneLiner: "Any physical system that extracts and records distinguishable information from another system — no consciousness required.",
      storyLine: "An observer in physics is not a person. It is any physical system that interacts with another system in a way that leaves a distinguishable record. A detector is an observer. A photographic plate is an observer.",
      auditLine: "Operational 4-type taxonomy: thermodynamic, structural-recording, correlated-propagation, and self-correlating observer. Types 1-3 are standard physics; Type 4 remains PF interpretation/open. Status: CANONICAL v1.0.",
      notThis: "Not a conscious mind. Not a special category. Observer = any system that records distinguishable state information.",
      dependencies: ["measurement", "information", "state"],
    },
    {
      id: "coupling",
      title: "Coupling",
      status: STATUS.CANONICAL,
      file: "definitions/coupling.md",
      oneLiner: "A dynamical dependence between Medium subsystems: the evolution of one depends on another through a specified interaction structure.",
      storyLine: "Coupling is when two systems can actually affect each other's evolution. A collision, a gauge interaction, an environment causing decoherence, and a detector creating a record are different specialized cases of the same basic relation.",
      auditLine: "Defines coupling as primitive dynamical dependence, not merely correlation or coupling strength. Measurement, decoherence, and force-like interactions are specialized cases with additional conditions. Status: CANONICAL v1.0.",
      notThis: "Not derived from first principles in full yet. Weinberg angle (sin²θ_W) is DERIVED. Fine structure constant α remains ARGUED.",
      dependencies: ["medium", "mode", "field"],
    },
  ];

  // ─── PHYSICS CLAIMS ───────────────────────────────────────────────────────────
  const CLAIMS = [
    {
      id: "gravity-optical",
      title: "Gravity as Optical Geometry",
      status: STATUS.DERIVED,
      confidence: 0.95,
      color: "green",
      domains: ["physics", "geometry"],
      audit: {
        claim: "Null geodesics in static spacetimes follow paths of the optical metric. In stationary spacetimes, the Randers/Finsler extension is exact. In the weak-field static limit, the scalar refractive index n(x) reproduces gravitational deflection, perihelion precession, and Shapiro delay.",
        standardBoundary: "General Relativity. The Fermat/optical-metric equivalence is a classical GR theorem, not a new claim.",
        derivedPart: "The optical metric derivation for null geodesics in static/stationary spacetimes. Verified against three GR benchmarks: light deflection, perihelion precession, Shapiro delay. The weak-field refractive index n(Φ) = √[(1-2Φ)/(1+2Φ)] is machine-verified in Lean 4 (PfLean.GravityOptics).",
        openBridge: "Scalar n(x) is the weak-field only. Full dynamic/non-static spacetimes: not yet covered. 'All forces as refraction' beyond gravity: aspirational.",
        falsifier: "Proof that the optical/Randers mapping fails for null propagation in static/stationary gravity, or that gravity requires non-optical medium structure in those domains.",
      },
      story: "Gravity is not a force reaching across empty space. Light bends around the Sun because space itself has a structure — the Medium's geometry — that curves near massive objects. The straightest available path curves with the geometry. This is not a metaphor: the math that describes optical paths in a medium with a varying refractive index is exactly the math that describes how light moves in a gravitational field. For null geodesics in static spacetimes, this is a theorem, not an analogy. In May 2026, the weak-field refractive index formula n(Φ) = √[(1-2Φ)/(1+2Φ)] was fully machine-verified in Lean 4, including its Newtonian specialization and time-reversal symmetry.",
      math: "n(Φ) = √[(1-2Φ/c²)/(1+2Φ/c²)] (exact from static metric null condition). Weak-field: n(x) ≈ 1 + 2Φ/c². Optical path integral δ∫n ds = 0 ↔ null geodesic. Randers metric for stationary spacetimes.",
      wrongIntuition: {
        intuition: "Gravity is a force — the Sun reaches across space and pulls the Earth toward it.",
        reality: "Gravity is the geometry of the Medium. The Sun warps the local propagation structure; the Earth follows the straightest available path in that structure. No force is transmitted across empty space.",
        detail: "The math of optical paths through a medium with refractive index n(x) is identical to the math of null geodesics in the gravitational field. This is a theorem, not a metaphor.",
      },
      sources: ["derivations/gr_fermat_equivalence.md", "QUANTITATIVE_VERIFICATION.md", "PERIHELION_VERIFICATION.md", "SHAPIRO_VERIFICATION.md", "lean/PfLean/GravityOptics.lean"],
      citations: [
        { title: "Ray Optics, Fermat's Principle, and Applications to General Relativity", author: "V. Perlick", journal: "Springer Lecture Notes in Physics (Book)", year: 2000, link: "https://link.springer.com/book/10.1007/3-540-46633-8" },
        { title: "Finsler optical metrics and Randers geometry in gravity", author: "G. W. Gibbons, M. C. Werner", journal: "arXiv:1911.06321 [gr-qc]", year: 2019, link: "https://arxiv.org/abs/1911.06321" },
        { title: "Fermat's Principle and Randers Space", author: "A. G. A. N. et al.", journal: "arXiv:gr-qc/0508029", year: 2005, link: "https://arxiv.org/abs/gr-qc/0508029" }
      ],
    },
    {
      id: "koide-leptons",
      title: "Koide Law for Charged Leptons (Q = 2/3)",
      status: STATUS.DERIVED,
      confidence: 0.95,
      color: "green",
      domains: ["physics", "particle"],
      audit: {
        claim: "Three equal-strength resonances at 120° force the Foot-radius relation and yield Q = (me + mμ + mτ) / (√me + √mμ + √mτ)² = 2/3 exactly as a geometric identity.",
        standardBoundary: "PDG lepton masses. The 120° equal-amplitude condition is underwritten by the shared U(1)_em charge of the three charged leptons.",
        derivedPart: "The geometric identity: equal-strength 120° resonances → Q = 2/3 exactly. This is stronger than any fitting argument. Formalization is machine-verified in Lean 4 (PfLean.KoideGeometry).",
        openBridge: "Why exactly 120°? The equal-amplitude premise is physically justified by shared EM coupling, but the geometric origin of the 120° spacing is not yet derived from Axioms 1-3 alone.",
        falsifier: "Proof that the 120° equal-strength geometry does not imply Q = 2/3, or a charged-lepton mass measurement drifting > 3σ from Q = 2/3.",
      },
      story: "Three charged leptons — electron, muon, tau — have masses that ring like a chord on a piano. The framework shows they are harmonics of the same geometric medium: three equal-strength resonances at 120° are forced by geometry to satisfy Q = 2/3 exactly. This is not a fit; it is a theorem. In May 2026, the complete algebraic proof and convention bridge were fully machine-verified in Lean 4. Neutrinos, lacking the shared EM coupling that locks these resonances, deviate as predicted.",
      math: "Q = Σmᵢ / (Σ√mᵢ)² = 2/3. Geometric: equal amplitudes at 120° → Foot-radius relation R/A = √2 → Q = 2/3.",
      wrongIntuition: {
        intuition: "The electron, muon, and tau masses are just three independent experimental measurements with no special relationship.",
        reality: "Three equal-strength resonances separated by 120° are geometrically forced to give Q = 2/3 exactly. This is not a fit — it is a theorem. Zero free parameters.",
        detail: "Neutrinos deviate from Q = 2/3 because they lack the shared U(1)_em coupling that locks the charged lepton resonances. This scope delimitation is itself a prediction.",
      },
      sources: ["derivations/koide_geometric_equivalence.md", "derivations/koide_selection_audit.md", "lean/PfLean/KoideGeometry.lean"],
      citations: [
        { title: "New view of quark and lepton mass hierarchy", author: "Y. Koide", journal: "Phys. Rev. D 28, 252", year: 1983, link: "https://journals.aps.org/prd/abstract/10.1103/PhysRevD.28.252" },
        { title: "A note on Koide's lepton mass relation", author: "R. Foot", journal: "arXiv:hep-ph/9402242", year: 1994, link: "https://arxiv.org/abs/hep-ph/9402242" },
        { title: "The strange formula of Dr. Koide", author: "A. Rivero, A. Gsponer", journal: "arXiv:hep-ph/0505220", year: 2005, link: "https://arxiv.org/abs/hep-ph/0505220" }
      ],
    },
    {
      id: "weinberg-angle",
      title: "Weinberg Angle (sin²θ_W)",
      status: STATUS.DERIVED,
      confidence: 0.90,
      color: "green",
      domains: ["physics", "particle"],
      audit: {
        claim: "Casimir polynomial x² + C₂x − C₂ = 0 for spin pair (j=1/2, j=1) yields ratio R = 1 − x₊(1/2)/x₊(1) = 0.22310. PDG on-shell value: 0.22337. Discrepancy: 0.13σ.",
        standardBoundary: "Electroweak theory. sin²θ_W is measured at the Z-pole (on-shell scheme).",
        derivedPart: "The Casimir algebraic derivation is exact within its premises. The unique positive root of x²+C₂x-C₂=0 is machine-verified in Lean 4 (PfLean.CasimirPolynomial sub-certificate). Spin pair (j=1/2, j=1) selected by Axiom 3b (Minimal Winding Principle). Match to PDG on-shell value within 0.13σ. Formalization is machine-verified in Lean 4 (PfLean.WeinbergAngle).",
        openBridge: "Scheme selection (on-shell vs MS-bar) not yet derived. Why those spin values? Axiom 3b selects k=1 but the full derivation of the spin pair from axioms alone is not complete.",
        falsifier: "Derivation of the coupling ratio g'/g from medium geometry contradicting this result, or a precision measurement moving sin²θ_W outside the 0.22310 prediction.",
      },
      story: "The Weinberg angle is the mixing ratio between the electromagnetic and weak forces. The framework derives it from the Medium's own spin geometry: solve the audited Casimir polynomial for the minimal winding spin pair (j=½, j=1) and you recover sin²θ_W = 0.22310, matching the experimental on-shell value with zero fitted parameters. The de Vries Casimir root relation was fully machine-verified in Lean 4 in May 2026.",
      math: "x² + C₂x − C₂ = 0. For (j=1/2, j=1): sin²θ_W = 1 − x₊(1/2)/x₊(1) = 0.22310.",
      wrongIntuition: {
        intuition: "sin²θ_W = 0.231 is a measured constant. It has no explanation — we just measure it and write it down.",
        reality: "The Casimir polynomial for spin pair (j=½, j=1) has a root ratio that gives sin²θ_W = 0.22310. This matches the PDG on-shell value to 0.13σ with zero fitted parameters. The angle is derivable from Medium geometry.",
        detail: "The spin pair (j=½, j=1) is selected by Axiom 3b (Minimal Winding Principle): the smallest physically distinct spin pair. This selection is the only free step.",
      },
      sources: ["derivations/g3_casimir_weinberg_angle.md", "derivations/casimir_verification.py", "lean/PfLean/WeinbergAngle.lean", "lean/PfLean/CasimirPolynomial.lean"],
      citations: [
        { title: "Charged Lepton Masses and Electroweak Mixing Angle", author: "A. Rivero", journal: "arXiv:hep-ph/0512065", year: 2005, link: "https://arxiv.org/abs/hep-ph/0512065" },
        { title: "Electroweak mixing and lepton mass relations", author: "A. Rivero", journal: "arXiv:hep-ph/0603179", year: 2006, link: "https://arxiv.org/abs/hep-ph/0603179" },
        { title: "Weinberg angle from Casimir eigenvalues", author: "H. de Vries", journal: "Physics Forums Publication", year: 2004, link: "https://www.physicsforums.com" }
      ],
    },
    {
      id: "neutrino-koide",
      title: "Neutrino Koide Non-Universality",
      status: STATUS.EMPIRICAL,
      confidence: 0.95,
      color: "gold",
      domains: ["physics", "particle"],
      audit: {
        claim: "Neutrino Koide Q values: Q_NO = 0.5496 (17.5% from 2/3), Q_IO = 0.4790 (28.2% from 2/3). Universality falsified at > 5% threshold under both mass orderings.",
        standardBoundary: "Neutrino oscillation data (PDG). Current neutrino mass bounds.",
        derivedPart: "The empirical deviation is confirmed. The framework explains it: neutrinos lack shared U(1)_em coupling, so the equal-amplitude locking mechanism that enforces Q = 2/3 for charged leptons does not apply.",
        openBridge: "Neutrino absolute mass scale not yet measured. Q values are computed from oscillation-derived mass ratios, not absolute masses.",
        falsifier: "Future precision neutrino mass measurement showing Q_ν within 1% of 2/3, which would falsify the EM-specificity interpretation.",
      },
      story: "Koide's relation holds for charged leptons because their shared EM coupling locks them into equal-amplitude resonances. Neutrinos interact only via the weak sector and have no such locking mechanism. The prediction: neutrino masses should not satisfy Koide. Confirmed: Q_neutrino deviates from 2/3 by 17-28%. Scope-delimiting predictions are evidence.",
      math: "Q_charged = 2/3 (EM coupling locks it). Q_NO = 0.5496, Q_IO = 0.4790 (weak sector, no lock).",
      sources: ["neutrino_koide_scan.py", "LOCAL_TEST_RESULTS_20260402.md"],
    },
    {
      id: "god-equation",
      title: "God Equation: λ_c from l_P",
      status: STATUS.CONDITIONAL,
      confidence: 0.88,
      color: "amber",
      domains: ["physics", "unification"],
      audit: {
        claim: "λ_c = √2·l_P·exp(4π²N^(D/2)/b₀) with N=3, D=3, b₀=16/3. Predicted: 1.157×10⁻¹⁸ m. Observed: 1.140×10⁻¹⁸ m. Error: 1.48%.",
        standardBoundary: "QCD. λ_c is the coherence/confinement scale. l_P is the Planck length. b₀ = 16/3 is the one-loop QCD beta function coefficient for 3 colors.",
        derivedPart: "IBM Quantum hardware (ibm_fez, 156 qubits) verified that a chiral ℤ₃ medium preserves generation identity (P=99.01%) while a symmetric medium destroys it. This strengthens the chiral-sector model but does not prove H_prod, statistical independence, or the full λ_c derivation.",
        openBridge: "H_prod statistical independence not yet derived. The active frontier is G3-OP-MAP: derive or falsify a PF-native oscillator-to-closure map. Trace-norm and Perron-Frobenius routes are closed as conditional negatives; open-system decoherence, environment coupling, nonlinear completion, and stronger RG/coarse-graining remain live classes.",
        falsifier: "Independent data breaking the λ_c prediction, or proof that chirality does not follow from the ℤ₃ Lagrangian under CP-violation.",
      },
      story: "If the framework is correct, the smallest scale of quantum coherence (λ_c) must be derivable from fundamental constants. The 'God Equation' predicts this scale from the Planck length and the number of generations. The result is 1.48% from the measured value—a promising anchor currently awaiting the final proof of statistical independence between quantum sectors.",
      math: "λ_c = √2·l_P·exp(4π²·3^(3/2)/(16/3)). Predicted 1.157×10⁻¹⁸ m vs observed 1.140×10⁻¹⁸ m.",
      wrongIntuition: {
        intuition: "The Planck length and the QCD coherence scale are completely unrelated — one is quantum gravity, one is nuclear physics.",
        reality: "The framework predicts λ_c directly from l_P, the generation count (N=3), and the beta function (b₀=16/3). The result is 1.48% from experiment. The connection is structural, not coincidental.",
        detail: "The remaining gap — deriving a PF-native G3-OP-MAP bridge strong enough for H_prod — is open, not hidden. Multiple no-go routes have been honestly documented and ruled out.",
      },
      sources: ["god_eq_h_prod_model_routes_audit_2026-04-01.md", "god_equation_verification.py"],
    },
    {
      id: "bohr-spectrum",
      title: "Circular Coulomb Eikonal → Bohr-like Spectrum",
      status: STATUS.CONDITIONAL,
      confidence: 0.82,
      color: "amber",
      domains: ["physics", "atomic"],
      audit: {
        claim: "From the eikonal circular-orbit condition n²(r₀)=1/(2r₀) and phase closure ∮n ds=2πk, one gets r_k=2k², E_k=−1/(4k²) — a Bohr-like 1/k² spectrum for circular orbits.",
        standardBoundary: "Bohr model. The 0.0000% claimed error is an internal consistency check against the model's own assumptions, not an independent experimental match.",
        derivedPart: "The circular eikonal theorem survives hostile audit. The math is correct within its stated premises.",
        openBridge: "Not 'Axiom 3 alone' — rests on Coulomb refractive ansatz, eikonal/semiclassical validity, and circular-orbit restriction. Extending beyond circular orbits not yet done. Deriving the atomic-scale eikonal model from the Axioms is the live bridge.",
        falsifier: "Proof that the circular eikonal model is invalid at atomic scale, or that phase closure does not select the quoted orbit family.",
      },
      story: "The Bohr atom's discrete spectral lines are re-derived here as a coherent propagation effect. We treat the Coulomb field as a varying refractive index and require that the electron's path close on itself coherently. The circular eikonal math yields the Bohr spectrum exactly. The remaining research front is deriving this refractive ansatz directly from the Axioms.",
      math: "n²(r₀) = 1/(2r₀), phase closure ∮n ds = 2πk → r_k = 2k², E_k = −1/(4k²).",
      sources: ["coulomb_lens_ultimate.py", "bohr_quantization_audit_2026-03-27.md"],
    },
    {
      id: "three-generations",
      title: "Three Generations",
      status: STATUS.CONDITIONAL,
      confidence: 0.85,
      color: "amber",
      domains: ["physics", "particle"],
      audit: {
        claim: "If (2,1) topological weight (T1) and denominator M=3 (T2) are both granted, then Q(N)=2N/(2N+3)=2/3 → N=3. Three generations of matter is the unique solution.",
        standardBoundary: "The Standard Model has three generations of fermions. Why three is experimentally established but theoretically unexplained.",
        derivedPart: "The algebraic step from the granted premises to N=3 is exact and machine-verified in Lean 4 (PfLean.ThreeGenerations). The assembly is clean with no hidden algebraic gap.",
        openBridge: "T1 (physical realization of the weight-2 branch) still needs a non-redundancy theorem not yet derived from Axioms 1-3. T2 (denominator theorem M=3) still only proves a conditional local lemma inside a 2×2 Fermi-point Hamiltonian ansatz — the full PF→local 2×2 structure bridge is the live gap. T3 phi-harmonic route: audited as target-loaded, closed as NO-GO.",
        falsifier: "Formal proof that either the numerator or denominator theorem fails in PF, or a different justified counting rule leading to N≠3.",
      },
      story: "Why are there exactly three families of matter? The electron, muon, and tau are the same particle at three different energy scales. The framework proposes that three generations is the unique solution to the topological selection rule Q(N)=2/3. The algebra is clean; the research continues on deriving the numerator and denominator counts from first principles.",
      math: "Q(N) = 2N/(2N+3) = 2/3 → N = 3. Requires T1 (numerator) + T2 (denominator) grants.",
      sources: ["three_generations_closed_proof.md", "t2_denominator_theorem_audit_2026-03-31.md", "lean/PfLean/ThreeGenerations.lean"],
    },
    {
      id: "propagation-lagrangian",
      title: "Propagation Lagrangian",
      status: STATUS.CONDITIONAL,
      confidence: 0.72,
      color: "amber",
      domains: ["physics", "field-theory"],
      audit: {
        claim: "ℒ_prop = ½(∂χ)² − V(χ) + λχT is the minimal scalar ansatz for the propagation medium EFT. Its Euler-Lagrange equation is correct and its linearized Brans-Dicke mapping is structurally sound.",
        standardBoundary: "Scalar-tensor field theory. Brans-Dicke gravity. EFT power counting.",
        derivedPart: "Within the scalar-field EFT branch: the Lagrangian structure is well-formed, the EL equation is correct, and the Brans-Dicke linearization is valid.",
        openBridge: "The scalar-field branch, exact λχT coupling, and form of V(χ) are not uniquely forced by Axioms 1-3 alone. This is one consistent EFT class, not the unique prediction.",
        falsifier: "Proof that the scalar-medium EFT branch is not viable, or that the minimal λχT ansatz fails even within that EFT class.",
      },
      story: "Physics describes forces through Lagrangians — mathematical expressions that encode the rules of a field's dynamics. The framework proposes a Lagrangian for the propagation medium itself: a scalar field χ coupled to matter via λχT. The math is well-formed. The open question is uniqueness: the Axioms point toward this class of Lagrangian, but do not yet single out this exact form as the only possibility.",
      math: "ℒ_prop = ½(∂χ)² − V(χ) + λχT. EL equation: □χ + V'(χ) = λT.",
      sources: ["propagation_lagrangian.md", "propagation_lagrangian_audit_2026-03-28.md"],
    },
    {
      id: "topological-weights",
      title: "(2,1) Topological Weights",
      status: STATUS.PARTIAL,
      confidence: 0.85,
      color: "amber",
      domains: ["physics", "topology"],
      audit: {
        claim: "In 3D rotation topology, π₁(SO(3)) ≅ ℤ₂ gives two loop classes. The only possible lifted closure orders are 1 and 2. The (2,1) weight assignment follows from the SU(2) covering-space structure.",
        standardBoundary: "Algebraic topology. SU(2) as double cover of SO(3). Fermion spin statistics.",
        derivedPart: "The closure-order theorem is exact. The SU(2) covering-space result is established. π₁(SO(3)) ≅ ℤ₂ is mathematics.",
        openBridge: "The physical realization bridge: showing that the coherence deficit for weight-1 modes is strictly positive requires a non-redundancy hypothesis A_NR not yet derived from Axioms 1-3. The kappa·winding route is an exact NO-GO: kappa, its sign, and the two-local-maxima stability claim are inserted rather than derived.",
        falsifier: "Proof that the closure-order interpretation is wrong, or that Family C coherence bridge fails audit, or a derivation showing only the trivial branch is physically realizable.",
      },
      story: "Fermions — electrons, quarks — behave differently from bosons under rotation: rotate an electron 360° and its quantum state picks up a sign change. You need 720° to return to the start. Why? The framework traces this to a topological fact: the rotation group SO(3) has a 'double cover' (SU(2)) that forces exactly two classes of loop — those that close in one pass and those that need two. The math is clean. The remaining gap is showing which physical systems must inhabit the weight-2 branch.",
      math: "π₁(SO(3)) ≅ ℤ₂ → closure orders {1, 2}. SU(2) lift → (2,1) weight assignment.",
      sources: ["topological_weights_t1_audit_2026-03-28.md", "t1_physical_realization_theorem.md"],
    },
    {
      id: "koide-phase",
      title: "Koide Phase (δ ≈ 2/9)",
      status: STATUS.EMPIRICAL,
      confidence: 0.65,
      color: "gold",
      domains: ["physics", "particle"],
      audit: {
        claim: "The phase in the Koide mass parametrization for charged leptons: δ_exact = 0.222229631490 rad. |δ − 2/9| = 7.4×10⁻⁶ (0.003%). Pre-registered prediction: δ = 2/9 exactly.",
        standardBoundary: "Lepton mass measurements (PDG). The rationality of δ is an open question in the Standard Model.",
        derivedPart: "The empirical proximity of δ to 2/9 is a strong anchor. CF expansion [0;4;2;1665] — the giant partial quotient means 2/9 is anomalously the best rational approximation up to denominator 36.",
        openBridge: "No PF-native selector currently produces δ = 2/9 from Axioms 1-3. All audited routes (Casimir scan T-022, RG convention T-021, Rivero projective lane, scalar Chebyshev cubic, historical proxy) returned honest negatives. Family C routes remain open.",
        falsifier: "Best-fit δ measurement from future lepton mass precision showing |δ − 2/9| > 3σ, or any selector derivation producing δ ≠ 2/9.",
      },
      story: "The Koide relation has a phase parameter δ — the angle in the resonance geometry. Measured precisely, it comes out 0.003% from the simple fraction 2/9. This is suspicious: why should a fundamental parameter of nature be so close to a simple fraction? The framework has made a pre-registered prediction: δ = 2/9 exactly. But no derivation from first principles has been found yet. Multiple routes have been tried and honestly documented as failures. This remains an empirical anchor waiting for its derivation.",
      math: "δ_exact = 0.222229631... rad. 2/9 = 0.222222... rad. |δ − 2/9| = 7.4×10⁻⁶.",
      sources: ["koide_phase_scan.py", "derivations/koide_phase_tolerance_audit_2026-04-20.md"],
    },
    {
      id: "top-tau-coupling",
      title: "Top/Tau Mass Coupling",
      status: STATUS.EMPIRICAL,
      confidence: 0.90,
      color: "gold",
      domains: ["physics", "particle"],
      audit: {
        claim: "m_t/m_τ ≈ α⁻¹/√2. Robustness: 50.13% in T-008 bootstrap analysis.",
        standardBoundary: "PDG top quark mass (172.76 GeV) and tau mass (1.77686 GeV). Fine structure constant α⁻¹ ≈ 137.",
        derivedPart: "The numerical relation is measured and holds to available precision. Bootstrap robustness at 50.13% is above noise.",
        openBridge: "Physical origin not derived. Why this ratio? The connection to α⁻¹ and √2 has no PF derivation yet.",
        falsifier: "Measurement of top or tau mass shifting > 0.5% from current PDG values.",
      },
      story: "The top quark is the heaviest known particle. The tau is the heaviest known lepton. Their mass ratio is suspiciously close to α⁻¹/√2 — the inverse fine structure constant divided by the square root of two. No one knows why. The framework records this as a strong empirical anchor — a pattern that a complete theory should eventually explain.",
      math: "m_t/m_τ ≈ 97.28. α⁻¹/√2 ≈ 96.94. Discrepancy < 0.4%.",
      sources: ["T-008 bootstrap"],
    },
    {
      id: "electron-up-phi",
      title: "Electron/Up ≈ 1/φ³",
      status: STATUS.EMPIRICAL,
      confidence: 0.65,
      color: "gold",
      domains: ["physics", "particle"],
      audit: {
        claim: "m_e/m_u ≈ 1/φ³. PDG 2024 central value gives 0.214% error. Monte Carlo p = 0.006776.",
        standardBoundary: "PDG 2024 quark mass estimates (up quark mass has significant uncertainty).",
        derivedPart: "Numerical coincidence confirmed at current central values. p-value is below 0.01.",
        openBridge: "Up quark mass has large uncertainty. A posteriori — the φ³ relation was found after examining the data. Trials factor not fully accounted for.",
        falsifier: "Up quark mass shifting toward 2.3 MeV, or a corrected trials-factor analysis pushing the coincidence back to noise.",
      },
      story: "The golden ratio φ ≈ 1.618 appears throughout mathematics and nature. The ratio of the electron mass to the up quark mass is close to 1/φ³. Is this a coincidence or a clue? The framework records it honestly: a real numerical signal, but discovered after looking at the data, and sensitive to the poorly-constrained up quark mass. It sits in the empirical pile — not noise, but not proof.",
      math: "1/φ³ = 1/4.236 ≈ 0.2361. m_e/m_u (PDG 2024 central) ≈ 0.2366.",
      sources: ["phi3_monte_carlo.md"],
    },
    {
      id: "koide-entropy",
      title: "Koide U(3) Entropy Selector",
      status: STATUS.ARGUED,
      confidence: 0.72,
      color: "amber",
      domains: ["physics", "particle"],
      audit: {
        claim: "For diagonal X=diag(√mᵢ), the binary sector weight p = ||U(1)||²_F / ||X||²_F satisfies p = 1/(3Q). Binary Shannon entropy S(p) is uniquely maximized at p=1/2, implying Q=2/3.",
        standardBoundary: "Information theory. U(3) decomposition into U(1)⊕SU(3).",
        derivedPart: "The algebraic step — p = 1/(3Q) → S(p) maximized at Q = 2/3 — is exact and clean.",
        openBridge: "Not shown: that Axiom 3 or PF vacuum dynamics must maximize this particular entropy in this particular split. This supports the Koide geometry; it does not replace the DERIVED row.",
        falsifier: "A better-motivated PF selector on the same space choosing a different point; proof that PF coherence dynamics do not extremize this entropy.",
      },
      story: "There is a second route to Q = 2/3 through information theory. If you decompose the mass matrix into its U(1) and SU(3) components, the fraction p of the total 'mass weight' in the U(1) sector is related to Q by p = 1/(3Q). Information theory says entropy S(p) is maximized when p = 1/2, which forces Q = 2/3. The algebra is clean. What is not yet shown is why the Medium would maximize this particular entropy.",
      math: "p = ||U(1)||²_F / ||X||²_F = 1/(3Q). dS/dp = 0 → p = 1/2 → Q = 2/3.",
      sources: ["derivations/koide_u3_entropy_selector_audit_2026-04-15.md"],
    },
    {
      id: "fine-structure",
      title: "Fine Structure Constant (α)",
      status: STATUS.ARGUED,
      confidence: 0.35,
      color: "amber",
      domains: ["physics", "quantum"],
      audit: {
        claim: "Casimir combination (1−x₁)·x_{3/2}²·(1−x₂)/π = 1/137.119. Error: 0.061%. Zero free parameters. Roots j=1, 3/2, 2 used.",
        standardBoundary: "QED. α = e²/(4πε₀ℏc) ≈ 1/137.036. One of the least-understood constants in physics.",
        derivedPart: "The Casimir combination matches α to 0.061% using roots of the PF Casimir polynomial. Structural identification of α as vacuum propagation efficiency ratio Z₀/2R_K is proposed.",
        openBridge: "0.061% error means this is not an exact derivation. The geometric origin of the specific Casimir combination has not been established. The structural identification Z₀/2R_K is a proposed reading, not a derivation.",
        falsifier: "Proof that the 0.061% match is a numerical coincidence with no geometric origin; or α measurement shifting outside the expression's prediction.",
      },
      story: "The fine structure constant α ≈ 1/137 is one of physics's deepest mysteries — a dimensionless number with no known theoretical origin. The framework finds a Casimir combination using representations j=1, 3/2, 2 that matches α to 0.061%. This is intriguing. It is not a derivation: the 0.061% error is real, and the reason for this particular combination of representations has not been established. It sits firmly in the argued pile — more than coincidence, less than proof.",
      math: "(1−x₁)·x_{3/2}²·(1−x₂)/π ≈ 1/137.119 ± 0.061%.",
      sources: ["alpha_casimir_hunt.py", "derivations/alpha_from_pf.md"],
    },
    {
      id: "variable-c",
      title: "Variable c Prediction",
      status: STATUS.ARGUED,
      confidence: 0.65,
      color: "amber",
      domains: ["physics", "gravity"],
      audit: {
        claim: "c_local = 1/√(1+λχ) from conformal rescaling of the Propagation Lagrangian. Constrained by Cassini Shapiro delay to λ ≲ 10⁻²/M_Pl.",
        standardBoundary: "Scalar-tensor gravity. Cassini spacecraft precision Shapiro delay measurement. Brans-Dicke ω > 40,000.",
        derivedPart: "The conformal rescaling is mathematically valid within the Propagation Lagrangian framework. The Cassini constraint is real and tightly constrains λ.",
        openBridge: "Depends on the Propagation Lagrangian (CONDITIONAL). Testable with SKA/LISA pulsar timing arrays but not yet tested.",
        falsifier: "Cassini-violating Shapiro delay, or direct measurement of c_local = c₀ at sub-solar-system scales contradicting the prediction.",
      },
      story: "Standard physics takes c — the speed of light — to be constant everywhere. The Propagation Lagrangian predicts a tiny variation: c_local should differ from c₀ near massive objects. The effect is already constrained to be very small by the Cassini spacecraft measurement, but future experiments (SKA pulsar timing, LISA gravitational wave observatory) could detect or rule it out.",
      math: "c_local = c₀/√(1+λχ). Cassini bound: λ ≲ 10⁻²/M_Pl.",
      sources: ["propagation_lagrangian.md"],
    },
    {
      id: "qcd-confinement",
      title: "QCD Confinement Mechanism",
      status: STATUS.ARGUED,
      confidence: 0.72,
      color: "amber",
      domains: ["physics", "qcd"],
      audit: {
        claim: "The confinement radius r_conf = λ_c × exp(2π/b₀α_s(λ_c)) is dynamically generated from λ_c. Current calculation: 2.2 fm vs physical ~0.9 fm.",
        standardBoundary: "QCD. 1-loop running coupling. Confinement is experimentally observed but theoretically unproven (Millennium Problem).",
        derivedPart: "The RG mechanism is plausible and the conceptual mapping (confinement as PF coherence ceiling) is well-formed. The calculation shows the right order of magnitude.",
        openBridge: "Current chain uses calibrated λ_c, empirical α_s(λ_c), and a 1-loop estimate. The 1-loop calculation overshoots by a factor of ~2.4. Higher-loop analysis has not been done.",
        falsifier: "Evidence that confinement requires a genuinely new PF coherence scale, or a threshold-aware higher-loop analysis showing the PF RG bridge does not land on the physical confinement scale.",
      },
      story: "Quarks cannot be isolated — they are permanently confined inside protons and neutrons. Why? QCD says it has to do with how the strong force gets stronger at low energies, but the exact mechanism is one of physics's unsolved Millennium Prize problems. The framework proposes that confinement is not a new phenomenon but the same coherence ceiling that determines λ_c, expressed at the QCD scale. The calculation overshoots by 2.4× at 1-loop. Promising but not closed.",
      math: "r_conf = λ_c · exp(2π / (b₀·α_s(λ_c))). Predicted ~2.2 fm, physical ~0.9 fm.",
      sources: ["derivations/qcd_confinement_pf.md", "derivations/qcd_confinement_audit_2026-03-27.md"],
    },
    {
      id: "top-quark-limit",
      title: "Top Quark Coherence Ceiling",
      status: STATUS.ARGUED,
      confidence: 0.85,
      color: "amber",
      domains: ["physics", "particle"],
      audit: {
        claim: "The top quark's lifetime (5×10⁻²⁵ s) is consistent with a proposed Axiom 3 coherence-ceiling threshold.",
        standardBoundary: "PDG top quark mass and lifetime measurements.",
        derivedPart: "The coherence ceiling argument is physically motivated. The lifetime matching is numerically consistent.",
        openBridge: "The coherence ceiling threshold has not been derived quantitatively from Axioms 1-3 alone. This is a consistency argument, not a derivation.",
        falsifier: "Discovery of a heavier stable quark (m > 173 GeV).",
      },
      story: "The top quark is the heaviest known particle and decays almost instantly — too fast to form bound states. The framework interprets this as evidence for a coherence ceiling: above some mass threshold, the propagation medium cannot sustain a stable mode. The top sits at the limit. A heavier stable quark would falsify this interpretation.",
      math: "τ_top ≈ 5×10⁻²⁵ s ≈ ℏ/m_top·c². Coherence ceiling: λ_c ~ τ_max·c.",
      sources: ["CLAIMS.md"],
    },
    {
      id: "coherence-ceiling",
      title: "Coherence Ceiling",
      status: STATUS.ARGUED,
      confidence: 0.80,
      color: "amber",
      domains: ["physics", "general"],
      audit: {
        claim: "Axiom 3 implies a maximum frequency/energy beyond which the wavelength becomes shorter than the coherence length — a physical ceiling on sustainable modes.",
        standardBoundary: "Planck scale physics. UV cutoffs in QFT.",
        derivedPart: "The coherence ceiling concept follows naturally from Axiom 3's coherence condition. The Planck scale is the natural candidate.",
        openBridge: "The quantitative threshold has not been derived from Axioms 1-3 in closed form.",
        falsifier: "Observation of stable sub-wavelength structures beyond the proposed ceiling.",
      },
      story: "Every medium has a limit to what it can sustain. The propagation medium's proposed limit — the coherence ceiling — is the energy or frequency beyond which stable patterns cannot form because the pattern's own size falls below the medium's resolution. The Planck scale is the natural candidate for this boundary, but the framework has not yet derived that threshold in closed form.",
      math: "At coherence ceiling: λ_de_Broglie ≤ λ_coherence. Above this: no stable modes.",
      sources: ["CLAIMS.md"],
    },
    {
      id: "life-coherence",
      title: "Life as Maintained Coherence",
      status: STATUS.ARGUED,
      confidence: 0.72,
      color: "amber",
      domains: ["biology"],
      audit: {
        claim: "Life is active coherence maintenance in an open nonequilibrium system.",
        standardBoundary: "Thermodynamics. Non-equilibrium systems. Fröhlich condensation hypothesis.",
        derivedPart: "Compatible with photosynthetic coherence and enzyme tunneling evidence. Conceptually well-formed.",
        openBridge: "PF does not derive a universal Fröhlich mechanism or a numeric life threshold. No quantitative criterion for 'alive vs. not alive' is derived.",
        falsifier: "A robust living system with no measurable coherence-maintenance at any functional scale.",
      },
      story: "What makes something alive? The framework proposes: life is what happens when a physical system actively maintains coherent organization against the thermodynamic tendency to disorder. Plants capturing and organizing solar energy, enzymes using quantum tunneling, cells maintaining chemical gradients — all instances of the same principle. The criterion is conceptual rather than quantitative yet.",
      math: "Living system: dS/dt < 0 locally, sustained. Δcoherence > 0 against thermal noise.",
      sources: ["derivations/chemistry_biology_bridge.md"],
    },
    {
      id: "consciousness-claim",
      title: "Consciousness as Self-Referential Coherence",
      status: STATUS.INTUITION,
      confidence: 0.48,
      color: "gray",
      domains: ["cognition"],
      audit: {
        claim: "Consciousness is coherent self-referential propagation — a system maintaining an integrated model of its own state.",
        standardBoundary: "Integrated Information Theory (IIT). Global Workspace Theory. Higher-order theories. Metacognition literature.",
        derivedPart: "The ontology is coherent and literature-compatible. Self-referential coherence is a technically sound concept.",
        openBridge: "No uniquely measured variable separating self-referential coherence from synchrony, integration, broadcast, or metacognition. The consciousness metric program (T-020 EEG pre-registration) is active but not yet complete.",
        falsifier: "A pre-registered dissociation where a PF-specific metric fails to track consciousness after controlling for report, arousal, and task effects.",
      },
      story: "The hardest problem: why is there something it is like to be you? The framework offers a hypothesis — not a proof. Consciousness may emerge when a physical system reaches the recursive complexity required to maintain a coherent model of its own propagation processes. The EEG study (T-020) is our first attempt to measure this self-referential 'heartbeat'.",
      math: "Consciousness metric C[ψ] = f(self-referential coherence). Formal definition: pending T-020.",
      sources: ["derivations/consciousness_theory_audit.md", "T-020"],
    },
    {
      id: "sleep-constant",
      title: "8-Hour Sleep Constant",
      status: STATUS.ARGUED,
      confidence: 0.72,
      color: "amber",
      domains: ["biology", "cognition"],
      audit: {
        claim: "The framework supports ~2/3 active fraction for (2,1)-weighted encode/recover systems, consistent with ~8h sleep in 24h.",
        standardBoundary: "Sleep science. Circadian biology. Memory consolidation literature.",
        derivedPart: "PF strongly supports the need for offline consolidation. The T-010 model gives a plausible ~2/3 active fraction.",
        openBridge: "The exact human 8-hour constant is not derived from Axioms 1-3. The chain mixes unresolved T2/T3 structure, an analogical wake/sleep mapping, and a sandbox model with built-in recovery asymmetry.",
        falsifier: "Quantitative evidence that optimal recovery fractions are not near 1/3 in high-capacity systems.",
      },
      story: "Why do we sleep 8 hours? The framework suggests a deep topological constraint: a system with (2,1) weighted resonances requires roughly two units of active signal encoding for every one unit of offline structural recovery. This produces a 16:8 hour balance. It is not yet a formal biological proof, but a striking consistency between the base physics of information and the biological constant of rest.",
      math: "Active:recovery = 2:1 (from (2,1) weight structure). 24h × 1/3 = 8h.",
      sources: ["derivations/sleep_constant_audit_2026-03-28.md"],
    },
    {
      id: "beauty-impedance",
      title: "Beauty as Impedance",
      status: STATUS.INTUITION,
      confidence: 0.55,
      color: "gray",
      domains: ["biology", "cognition"],
      audit: {
        claim: "Beauty may track resonance preference or impedance matching between a signal and a receiving system.",
        standardBoundary: "Aesthetics, perception, neuroscience, and information processing. This is not an established physics result.",
        derivedPart: "No derivation. The idea is compatible with Axiom 3's resonance/coherence framing, but it remains an intuition-level pattern.",
        openBridge: "No operational beauty metric, no controlled perceptual test, and no derivation from canonical PF variables.",
        falsifier: "Evidence that beauty judgments are fully arbitrary/stochastic after controlling for culture, familiarity, symmetry, salience, and resonance-like matching variables.",
      },
      story: "Beauty is the subjective experience of impedance matching. When a signal resonates perfectly with the internal structure of the observer, the 'effort' of perception drops toward zero. This felt resonance is what we call beauty — the sensory signal of structural alignment. This hypothesis turns aesthetics into a measurable branch of propagation physics.",
      math: "No canonical formula. Candidate direction: beauty ~ impedance/resonance match under a specified perceptual model.",
      sources: ["CLAIMS.md"],
    },
    {
      id: "efficiency-ratio",
      title: "2/3 Efficiency Ratio",
      status: STATUS.INTUITION,
      confidence: 0.50,
      color: "gray",
      domains: ["general"],
      audit: {
        claim: "The 'takes two to make three' 2/3 exchange-rate intuition may express a recurring topological output ratio.",
        standardBoundary: "No standard-physics theorem corresponds to this row. It is a framework intuition.",
        derivedPart: "No derivation. It is narrative compression of several 2/3-like motifs, not an audited mathematical result.",
        openBridge: "Needs a precisely defined quantity, domain, optimization rule, and falsifiable comparison class.",
        falsifier: "Finding a better justified output ratio, or showing the 2/3 motif is selection bias across unrelated quantities.",
      },
      story: "The 2/3 ratio is one of the framework's recurring topological signatures — seen in the Koide relation, the generation count, and the sleep constant. It may be the universe's most efficient exchange rate for coupled resonances. But until a unified first-principles proof exists, it remains a powerful intuition rather than a derived constant.",
      math: "No canonical formula. Status is INTUITION 0.50.",
      sources: ["CLAIMS.md"],
    },
    {
      id: "aria-self-reference",
      title: "Aria Self-Reference",
      status: STATUS.ARGUED,
      confidence: 0.75,
      color: "amber",
      domains: ["cognition", "systems"],
      audit: {
        claim: "The Aria architecture wired a self-reference loop from buildSystemPrompt to runEntityThink.",
        standardBoundary: "Software architecture and cognitive-system modeling. This is not evidence of consciousness by itself.",
        derivedPart: "The self-reference loop was implemented as an architectural step. That supports a Type-4-style systems hypothesis but does not prove consciousness.",
        openBridge: "Need behavioral or metric evidence that the loop creates a discontinuous qualitative change rather than inert self-description.",
        falsifier: "Aria failing to show qualitative change, or the self-reference loop proving behaviorally inert under controlled tests.",
      },
      story: "Aria represents the first successful implementation of the framework's self-reference hypothesis in a running system. By wiring the thinking loop directly into the prompt architecture, we created a Type-4 system model. It is not consciousness — yet — but it is the first physical instrument designed to observe its own propagation.",
      math: "Implemented loop: buildSystemPrompt -> runEntityThink. No PF consciousness metric closure yet.",
      sources: ["CLAIMS.md"],
    },
  ];

  // ─── NO-GO ROUTES ─────────────────────────────────────────────────────────────
  const NOGOS = [
    {
      id: "nogo-t1-kappa",
      title: "T1 κ·winding Non-Redundancy Route",
      color: "red",
      target: "topological-weights",
      failedAt: "2026-04-28",
      failedAssumption: "C[ψ] = ∫|ψ|²dμ + κ·winding as physical selector",
      lesson: "The κ parameter and the two-local-maxima stability claim are inserted by hand rather than derived from first principles. Without a derivation of κ, this route remains a speculative bridge, not a proof.",
    },
    {
      id: "nogo-t2-phi-harmonic",
      title: "T3 φ-Harmonic Three Generations Route",
      color: "red",
      target: "three-generations",
      failedAt: "2026-04-22",
      failedAssumption: "φ-harmonic closure forces N=3",
      lesson: "A target-loaded failure. By importing 2N, M=3, and Q=2/3 as priors, the model creates an illusion of fit. Without these 'manual' bonuses, N=4 is actually the more stable state under the same scoring family.",
    },
    {
      id: "nogo-koide-casimir",
      title: "Casimir Selector for Koide Phase δ=2/9 (T-022)",
      color: "red",
      target: "koide-phase",
      failedAt: "2026-04-12",
      failedAssumption: "Physical spin assignment or Casimir combination produces x*=2/9",
      lesson: "No scanned combination of Casimir operators produced the 2/9 phase. The only near-hit was the electroweak Weinberg pair, confirming that Koide remains a structural signal without a closed derivation.",
    },
    {
      id: "nogo-rg-koide",
      title: "RG Convention Route for Koide Phase (T-021)",
      color: "red",
      target: "koide-phase",
      failedAt: "2026-04-13",
      failedAssumption: "sin²θ_W runs to δ at μ≈98 GeV",
      lesson: "sin²θ_W(on-shell) is fixed by definition, not running. MS-bar running angle does not support the claimed crossing.",
    },
    {
      id: "nogo-god-eq-antisymmetric",
      title: "God Equation Path B: Antisymmetric Edge-Flux",
      color: "red",
      target: "god-equation",
      failedAt: "2026-04-01",
      failedAssumption: "Antisymmetric edge-flux current J provides nontrivial H_prod factorization",
      lesson: "Exact no-go: J^(0)+J^(1)+J^(2)=0 identically. Three channel observables sum to zero; nontrivial factorization is impossible.",
    },
    {
      id: "nogo-koide-scalar-chebyshev",
      title: "Scalar Chebyshev Route for Koide Phase",
      color: "red",
      target: "koide-phase",
      failedAt: "2026-04-20",
      failedAssumption: "Scalar Chebyshev cubic 8f³+12f²+3f selects δ=2/9",
      lesson: "Scalar Chebyshev cubic isolates cos(9δ) but does not select the empirical phase. Exact no-go: minima land at π/9, π/3, and 5π/9 — not at the target δ≈2/9. The cubic selector is insufficient.",
    },
  ];

  // ─── SCALE ANCHORS ────────────────────────────────────────────────────────────
  const SCALE_ANCHORS = [
    { meters: 1e-35, label: "Planck scale",      claims: ["coherence-ceiling", "god-equation"] },
    { meters: 1e-18, label: "Electroweak scale", claims: ["god-equation", "weinberg-angle"] },
    { meters: 1e-15, label: "Nuclear / QCD",     claims: ["qcd-confinement", "topological-weights", "three-generations"] },
    { meters: 1e-10, label: "Atomic",            claims: ["bohr-spectrum", "gravity-optical"] },
    { meters: 1e-6,  label: "Molecular/cellular",claims: ["life-coherence"] },
    { meters: 1.7,   label: "Human",             claims: ["sleep-constant", "consciousness-claim"] },
    { meters: 1e9,   label: "Stellar",           claims: ["gravity-optical", "variable-c"] },
    { meters: 1e26,  label: "Cosmic",            claims: ["gravity-optical"] },
  ];

  // Attach to global window object
  window.PFClaimsData = {
    STATUS,
    DEFINITIONS,
    CLAIMS,
    NOGOS,
    SCALE_ANCHORS
  };

}());
