// AUTO-GENERATED by generate_claims_data_v3.py — DO NOT EDIT MANUALLY
// Source: CLAIMS.md (hash: aa634eabc78ff1bc)
// ALL status/confidence fields are pulled from authority. Manual edits will be overwritten.
// This file provides PFExplorerData — the runtime data object for panels.
// PFExplorerData, PFClaimsData, and PFDataGraph are all views of the same authority.

(function () {
  window.PFExplorerData = {
  "generatedAt": "2026-07-15",
  "sourceHash": "aa634eabc78ff1bc",
  "generatorVersion": "V3",
  "truthPolicy": {
    "auditedSource": "../../CLAIMS.md",
    "note": "ALL statuses in this file are generated from CLAIMS.md by generate_claims_data_v3.py. No hand-written status fields. Manual edits will be overwritten."
  },
  "godEquationAudit": {
    "dependencyChain": [
      {
        "id": "axioms",
        "label": "Axioms 1-3",
        "state": "axiom",
        "note": "Propagation, locality, coherence."
      },
      {
        "id": "exact-model",
        "label": "Exact model / Z3 bridge",
        "state": "strengthened",
        "note": "Exact walk plus a genuine circulant internal sector."
      },
      {
        "id": "operator",
        "label": "Operator closure",
        "state": "open",
        "note": "Need chirality-selected primitive shift operator or non-diagonal 3-step closure."
      },
      {
        "id": "h-prod",
        "label": "H_prod",
        "state": "open",
        "note": "Need a joint law that proves factorization rather than only weak decoupling."
      },
      {
        "id": "upgrade",
        "label": "Upgrade to DERIVED",
        "state": "conditional",
        "note": "Blocked until operator and probability bridges close."
      }
    ],
    "gaps": [
      {
        "id": "A",
        "title": "Markovity gap",
        "verdict": "OPEN",
        "need": "Show that locality yields a first-order Markov coarse walk.",
        "survives": "Axiom 2 gives local propagation; Z3 channel structure is in hand.",
        "detail": "The proof chain needs a memoryless coarse operator.",
        "sources": [
          {
            "label": "CLAIMS.md",
            "href": "../../CLAIMS.md"
          }
        ]
      },
      {
        "id": "B",
        "title": "Operator closure gap",
        "verdict": "OPEN VIA REPLACEMENT PATH",
        "need": "Derive chirality-selected operator or restate using non-diagonal 3-step circulant.",
        "survives": "Z3-extended Lagrangian derives a real three-channel internal sector.",
        "detail": "Symmetric nearest-neighbor circulant route closed negatively.",
        "sources": [
          {
            "label": "CLAIMS.md",
            "href": "../../CLAIMS.md"
          }
        ]
      },
      {
        "id": "C",
        "title": "Probability / H_prod gap",
        "verdict": "OPEN",
        "need": "Prove a joint probability model that really factorizes.",
        "survives": "Additive Fisher-information chain is mapped under named hypotheses.",
        "detail": "Zero cross-channel amplitude is weaker than full joint-law factorization.",
        "sources": [
          {
            "label": "CLAIMS.md",
            "href": "../../CLAIMS.md"
          }
        ]
      }
    ]
  },
  "panelMeta": [
    {
      "id": "foundations",
      "title": "Axiomatic Foundations",
      "note": "Interactive Propagation Lab and core definitions",
      "linkedResultIds": [],
      "defaultMode": "story"
    },
    {
      "id": "reality-correction",
      "title": "Reality Correction",
      "note": "Three wrong intuitions confronted",
      "linkedResultIds": [
        "forces-refraction",
        "bohr-quantization",
        "three-generations"
      ],
      "defaultMode": "story"
    },
    {
      "id": "hub",
      "title": "Scale Stack",
      "note": "Planck to cosmic in one vertical atlas",
      "linkedResultIds": [
        "god-equation",
        "weinberg-angle",
        "bohr-quantization"
      ],
      "defaultMode": "story"
    },
    {
      "id": "consciousness",
      "title": "Consciousness as Coherence",
      "note": "P1 device, neural coherence, and the physics of mind",
      "linkedResultIds": [
        "consciousness",
        "aria-self-reference"
      ],
      "defaultMode": "story"
    },
    {
      "id": "refraction",
      "title": "Gravity as Optical Geometry",
      "note": "Exact gravity theorem plus sandbox lens analogies",
      "linkedResultIds": [
        "forces-refraction"
      ],
      "defaultMode": "story"
    },
    {
      "id": "generations",
      "title": "Why Exactly Three",
      "note": "Topology, weights, and the live Q(N) lock",
      "linkedResultIds": [
        "weights-21",
        "three-generations"
      ],
      "defaultMode": "story"
    },
    {
      "id": "koide",
      "title": "The Koide Triangle",
      "note": "Mass geometry with live perturbation",
      "linkedResultIds": [
        "koide-law",
        "koide-phase"
      ],
      "defaultMode": "story"
    },
    {
      "id": "weinberg",
      "title": "The Weinberg Angle",
      "note": "Casimir roots and Axiom 3b",
      "linkedResultIds": [
        "weinberg-angle",
        "fine-structure-alpha"
      ],
      "defaultMode": "story"
    },
    {
      "id": "koide-weinberg-bridge",
      "title": "Koide/Weinberg Bridge",
      "note": "RG running analysis — close but not connected",
      "linkedResultIds": [
        "koide-phase",
        "weinberg-angle"
      ],
      "defaultMode": "story"
    },
    {
      "id": "god-equation",
      "title": "The God Equation",
      "note": "Planck to matter across 17 orders",
      "linkedResultIds": [
        "god-equation",
        "qcd-confinement"
      ],
      "defaultMode": "story"
    },
    {
      "id": "bohr",
      "title": "Bohr-like Circular-Eikonal Spectrum",
      "note": "Phase closure inside a named model layer",
      "linkedResultIds": [
        "bohr-quantization"
      ],
      "defaultMode": "story"
    },
    {
      "id": "dashboard",
      "title": "Dashboard",
      "note": "The audit wall for every current claim",
      "linkedResultIds": [],
      "defaultMode": "story"
    }
  ],
  "scales": [
    {
      "id": "planck",
      "name": "Planck",
      "resultIds": [
        "god-equation",
        "bekenstein-bound"
      ]
    },
    {
      "id": "quantum-foam",
      "name": "Quantum Foam",
      "resultIds": []
    },
    {
      "id": "gut",
      "name": "GUT",
      "resultIds": []
    },
    {
      "id": "matter",
      "name": "Matter",
      "resultIds": [
        "weights-21",
        "three-generations",
        "koide-law",
        "koide-phase",
        "weinberg-angle",
        "god-equation",
        "top-quark-limit",
        "top-tau-coupling",
        "coherence-ceiling",
        "fine-structure-alpha"
      ]
    },
    {
      "id": "proton",
      "name": "Proton",
      "resultIds": [
        "qcd-confinement",
        "phi3-ratio"
      ]
    },
    {
      "id": "nuclear",
      "name": "Nuclear",
      "resultIds": [
        "qcd-confinement",
        "phi3-ratio"
      ]
    },
    {
      "id": "atomic",
      "name": "Atomic",
      "resultIds": [
        "forces-refraction",
        "bohr-quantization"
      ]
    },
    {
      "id": "molecular",
      "name": "Molecular",
      "resultIds": [
        "propagation-lagrangian",
        "nogo-single-scalar"
      ]
    },
    {
      "id": "virus",
      "name": "Virus",
      "resultIds": [
        "life-coherence"
      ]
    },
    {
      "id": "cellular",
      "name": "Cellular",
      "resultIds": [
        "life-coherence"
      ]
    },
    {
      "id": "neural",
      "name": "Neural",
      "resultIds": [
        "consciousness",
        "aria-self-reference"
      ]
    },
    {
      "id": "human",
      "name": "Human",
      "resultIds": [
        "sleep-8h",
        "beauty-impedance",
        "efficiency-ratio"
      ]
    },
    {
      "id": "planetary",
      "name": "Planetary",
      "resultIds": [
        "forces-refraction",
        "variable-c"
      ]
    },
    {
      "id": "stellar",
      "name": "Stellar",
      "resultIds": []
    },
    {
      "id": "galactic",
      "name": "Galactic",
      "resultIds": []
    },
    {
      "id": "cosmic",
      "name": "Cosmic",
      "resultIds": []
    }
  ],
  "definitions": [],
  "results": [
    {
      "id": "bohr-quantization",
      "title": "Bohr-like Circular-Eikonal Quantization",
      "status": "DERIVED",
      "confidence": 0.9,
      "authorityClaimIds": [
        "bohr-spectrum"
      ],
      "kind": "Fundamental Physics",
      "scaleId": "atomic",
      "formula": "r_k = 2k^2, E_k = -1 / (4k^2), integral n ds = 2pi k",
      "summary": "In the circular eikonal Coulomb model, phase closure yields a Bohr-like 1/k² spectrum for circular orbits.",
      "falsifier": "Proof that the circular eikonal model is invalid at atomic scale, or that phase closure does not select the quoted orbit family.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        },
        {
          "label": "UNDERSTAND.md",
          "href": "../../UNDERSTAND.md"
        },
        {
          "label": "sandbox/coulomb_lens_ultimate.py",
          "href": "../coulomb_lens_ultimate.py"
        }
      ],
      "panelId": "bohr",
      "shortTitle": "Bohr Quantization",
      "derivation": [
        "axiom2",
        "axiom3"
      ],
      "axioms": [
        2,
        3
      ],
      "category": "fundamental",
      "blocker": "The circular-eikonal model is assumed rather than derived from Axioms 1–3.",
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-27",
          "value": 0.78
        },
        {
          "date": "2026-03-31",
          "value": 0.82
        }
      ],
      "wrongIntuition": {
        "intuition": "Energy levels are arbitrary postulates forced by experiment",
        "reality": "Energy levels are phase-closure conditions — an integral condition on standing wave modes in the propagation medium",
        "evidencePanel": "#bohr"
      }
    },
    {
      "id": "forces-refraction",
      "title": "Gravity as Optical Geometry / Refraction",
      "status": "DERIVED",
      "confidence": 0.95,
      "authorityClaimIds": [
        "gravity-optical"
      ],
      "kind": "Fundamental Physics",
      "scaleId": "atomic",
      "formula": "Optical metric / Randers bridge; n^2 = base + source / r",
      "summary": "GR is exactly equivalent to optical geometry for null geodesics in static spacetimes.",
      "falsifier": "Proof that the optical/Randers mapping fails for null propagation in static/stationary gravity.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        },
        {
          "label": "derivations/gr_fermat_equivalence.md",
          "href": "../../derivations/gr_fermat_equivalence.md"
        }
      ],
      "panelId": "refraction",
      "shortTitle": "Gravity Refraction",
      "derivation": [
        "axiom2",
        "axiom3"
      ],
      "axioms": [
        2,
        3
      ],
      "category": "fundamental",
      "blocker": null,
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-27",
          "value": 0.93
        },
        {
          "date": "2026-03-31",
          "value": 0.95
        }
      ],
      "wrongIntuition": {
        "intuition": "Gravity is a force that pulls objects together",
        "reality": "Gravity is the refractive bending of propagation paths in a medium with a density gradient",
        "evidencePanel": "#refraction"
      }
    },
    {
      "id": "weights-21",
      "title": "(2,1) Topological Weights",
      "status": "DERIVED",
      "confidence": 0.95,
      "authorityClaimIds": [
        "topological-weights"
      ],
      "kind": "Fundamental Physics",
      "scaleId": "matter",
      "formula": "π₁(SO(3)) ≅ Z₂ → closure orders {1,2}",
      "summary": "In 3D rotation topology, the two loop classes yield possible closure orders of 1 and 2.",
      "falsifier": "Proof that the closure-order interpretation is wrong, or a derivation showing only the trivial branch is physically realizable.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        },
        {
          "label": "derivations/three_generations_t1_proof.md",
          "href": "../../derivations/three_generations_t1_proof.md"
        }
      ],
      "panelId": "generations",
      "shortTitle": "(2,1) Weights",
      "derivation": [
        "axiom1",
        "axiom3"
      ],
      "axioms": [
        1,
        3
      ],
      "category": "fundamental",
      "blocker": "Physical realization of the weight-2 branch requires Family C extremal principle + A_NR.",
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-28",
          "value": 0.8
        },
        {
          "date": "2026-03-31",
          "value": 0.85
        }
      ],
      "wrongIntuition": {
        "intuition": "There could be four or five generations",
        "reality": "3D rotation topology yields the natural (2,1) closure-order pair, but physical realization is still open.",
        "evidencePanel": "#generations"
      },
      "isSplit": true,
      "statusParts": [
        {
          "status": "DERIVED",
          "confidence": 0.95,
          "qualifier": "kernel-only topological obstruction"
        },
        {
          "status": "CONDITIONAL",
          "confidence": 0.85,
          "qualifier": "physical realization"
        }
      ]
    },
    {
      "id": "koide-law",
      "title": "Koide Law (Q = 2/3)",
      "status": "EXACT IDENTITY",
      "confidence": 0.95,
      "authorityClaimIds": [
        "koide-leptons"
      ],
      "kind": "Fundamental Physics",
      "scaleId": "matter",
      "formula": "Q = sum m_i / (sum sqrt(m_i))^2 = 2/3",
      "summary": "Three charged leptons locked at 120°. Q = 2/3 exactly. Zero free parameters.",
      "falsifier": "Proof that the charged-lepton Koide ratio deviates from 2/3 at the stated precision, or that the geometric identity is not exact.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        },
        {
          "label": "derivations/koide_law_audit.md",
          "href": "../../derivations/koide_law_audit.md"
        }
      ],
      "panelId": "koide",
      "shortTitle": "Koide Law Q=2/3",
      "derivation": [
        "axiom3"
      ],
      "axioms": [
        3
      ],
      "category": "fundamental",
      "blocker": "Physical vacuum selection (why these masses) remains OPEN.",
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-27",
          "value": 0.93
        },
        {
          "date": "2026-03-31",
          "value": 0.95
        }
      ],
      "wrongIntuition": {
        "intuition": "Mass ratios are arbitrary free parameters",
        "reality": "The charged-lepton mass ratio is a geometric identity locked by coherence",
        "evidencePanel": "#koide"
      },
      "isSplit": true,
      "statusParts": [
        {
          "status": "EXACT IDENTITY",
          "confidence": 0.95,
          "qualifier": "geometry"
        },
        {
          "status": "OPEN",
          "confidence": null,
          "qualifier": "physical vacuum selection"
        }
      ]
    },
    {
      "id": "three-generations",
      "title": "Three Generations",
      "status": "CONDITIONAL",
      "confidence": 0.88,
      "authorityClaimIds": [
        "three-generations"
      ],
      "kind": "Fundamental Physics",
      "scaleId": "matter",
      "formula": "Q(N) = 2N / (2N + 3), set Q = 2/3, solve N = 3",
      "summary": "Why exactly three families of matter? Q(N)=2/3 has one solution: N=3.",
      "falsifier": "Proof that Q(N)=2/3 has additional positive integer solutions, or that the topological weight argument is invalid.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        },
        {
          "label": "derivations/three_generations_proof.md",
          "href": "../../derivations/three_generations_proof.md"
        }
      ],
      "panelId": "generations",
      "shortTitle": "Three Generations",
      "derivation": [
        "axiom1",
        "axiom3"
      ],
      "axioms": [
        1,
        3
      ],
      "category": "fundamental",
      "blocker": "T1 (physical realization of weight-2 branch) and T2 (PF→2×2 Fermi-point bridge) must close.",
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-28",
          "value": 0.8
        },
        {
          "date": "2026-03-31",
          "value": 0.85
        }
      ],
      "wrongIntuition": {
        "intuition": "The number of generations is arbitrary",
        "reality": "Topology and the Koide lock force exactly three",
        "evidencePanel": "#generations"
      }
    },
    {
      "id": "top-quark-limit",
      "title": "Top Quark Limit",
      "status": "ARGUED",
      "confidence": 0.85,
      "authorityClaimIds": [
        "top-quark-limit"
      ],
      "kind": "Open Frontiers",
      "scaleId": "matter",
      "formula": "tau_top near coherence ceiling threshold",
      "summary": "Top quark mass ~172.5 GeV as coherence ceiling threshold.",
      "falsifier": "Proof that the top quark mass is not near a coherence ceiling threshold.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        }
      ],
      "panelId": null,
      "shortTitle": "Top Quark Limit",
      "derivation": [],
      "axioms": [],
      "category": "signal",
      "blocker": null,
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-31",
          "value": 0.85
        }
      ]
    },
    {
      "id": "top-tau-coupling",
      "title": "Top / Tau Coupling",
      "status": "EMPIRICAL",
      "confidence": 0.9,
      "authorityClaimIds": [
        "top-tau-coupling"
      ],
      "kind": "Signals and Structure",
      "scaleId": "matter",
      "formula": "m_top / m_tau ~= alpha^-1 / sqrt(2)",
      "summary": "Top/Tau mass coupling ratio.",
      "falsifier": "Proof that the m_top/m_tau ratio does not match alpha^-1/sqrt(2).",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        }
      ],
      "panelId": null,
      "shortTitle": "Top-Tau Coupling",
      "derivation": [],
      "axioms": [],
      "category": "signal",
      "blocker": null,
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-31",
          "value": 0.9
        }
      ]
    },
    {
      "id": "coherence-ceiling",
      "title": "Coherence Ceiling",
      "status": "ARGUED",
      "confidence": 0.8,
      "authorityClaimIds": [
        "coherence-ceiling"
      ],
      "kind": "Open Frontiers",
      "scaleId": "matter",
      "formula": "Stable structure fails once wavelength drops below coherence length",
      "summary": "Stable structure fails once wavelength drops below coherence length.",
      "falsifier": "Proof that coherence does not impose a mass ceiling.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        }
      ],
      "panelId": null,
      "shortTitle": "Coherence Ceiling",
      "derivation": [],
      "axioms": [],
      "category": "signal",
      "blocker": null,
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-31",
          "value": 0.8
        }
      ]
    },
    {
      "id": "weinberg-angle",
      "title": "Weinberg Angle",
      "status": "ARGUED",
      "confidence": 0.65,
      "authorityClaimIds": [
        "weinberg-angle"
      ],
      "kind": "Fundamental Physics",
      "scaleId": "matter",
      "formula": "sin^2(theta_W) = 1 - x_+(1/2) / x_+(1), x^2 + C2 x - C2 = 0",
      "summary": "sin²θ_W from a Casimir polynomial. Matches experiment to 0.13σ.",
      "falsifier": "Proof that the Casimir polynomial does not yield the Weinberg angle at the stated precision.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        },
        {
          "label": "derivations/weinberg_angle_audit.md",
          "href": "../../derivations/weinberg_angle_audit.md"
        }
      ],
      "panelId": "weinberg",
      "shortTitle": "Weinberg Angle",
      "derivation": [
        "axiom3"
      ],
      "axioms": [
        3
      ],
      "category": "fundamental",
      "blocker": "On-shell vs MS-bar scheme selection is not yet derived from medium geometry.",
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-27",
          "value": 0.9
        },
        {
          "date": "2026-04-14",
          "value": 0.65
        }
      ],
      "wrongIntuition": {
        "intuition": "The weak mixing angle is a free parameter",
        "reality": "It is a root of a Casimir polynomial derived from coherence",
        "evidencePanel": "#weinberg"
      }
    },
    {
      "id": "fine-structure-alpha",
      "title": "Fine Structure Constant α — numeric",
      "status": "OPEN",
      "confidence": null,
      "authorityClaimIds": [
        "alpha-numeric"
      ],
      "kind": "Open Frontiers",
      "scaleId": "matter",
      "formula": "(1 - x_1) x_(3/2)^2 (1 - x_2) / pi ~= 1 / 137.119",
      "summary": "Numeric derivation of the fine structure constant from Casimir roots.",
      "falsifier": "Proof that the numeric derivation does not match the measured alpha.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        }
      ],
      "panelId": "weinberg",
      "shortTitle": "Fine Structure α",
      "derivation": [],
      "axioms": [],
      "category": "signal",
      "blocker": "Numeric match is a posteriori — structural derivation remains OPEN.",
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-31",
          "value": 0.35
        }
      ]
    },
    {
      "id": "god-equation",
      "title": "λ_c from l_P (The God Equation)",
      "status": "CONDITIONAL",
      "confidence": 0.88,
      "authorityClaimIds": [
        "god-equation-operator",
        "god-equation-scale"
      ],
      "kind": "Open Frontiers",
      "scaleId": "planck",
      "formula": "lambda_c = sqrt(2) l_P exp(4 pi^2 N^(D/2) / b0)",
      "summary": "λ_c from the Planck length. 1.48% error. The open bridge: H_prod.",
      "falsifier": "Proof that the (3,3) point does not anchor at 1.157e-18 m, or that the formula is not fit-selected.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        },
        {
          "label": "derivations/god_equation_audit.md",
          "href": "../../derivations/god_equation_audit.md"
        }
      ],
      "panelId": "god-equation",
      "shortTitle": "God Equation",
      "derivation": [
        "axiom1",
        "axiom2",
        "axiom3"
      ],
      "axioms": [
        1,
        2,
        3
      ],
      "category": "fundamental",
      "blocker": "Operator closure and H_prod factorization are open. The scale formula is fit-selected.",
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-27",
          "value": 0.88
        },
        {
          "date": "2026-03-31",
          "value": 0.88
        }
      ],
      "wrongIntuition": {
        "intuition": "The Planck-to-matter gap is unbridgeable",
        "reality": "An exponential formula bridges it, but the operator and probability bridges remain open",
        "evidencePanel": "#god-equation"
      },
      "splitStatuses": [
        {
          "id": "god-equation-operator",
          "status": "CONDITIONAL",
          "confidence": 0.88
        },
        {
          "id": "god-equation-scale",
          "status": "ARGUED",
          "confidence": 0.6
        }
      ]
    },
    {
      "id": "qcd-confinement",
      "title": "QCD Confinement",
      "status": "ARGUED",
      "confidence": 0.72,
      "authorityClaimIds": [
        "qcd-confinement"
      ],
      "kind": "Fundamental Physics",
      "scaleId": "nuclear",
      "formula": "r_conf = lambda_c exp(2 pi / (b0 alpha_s(lambda_c)))",
      "summary": "QCD confinement scale from the God Equation length.",
      "falsifier": "Proof that the confinement radius formula does not match hadron radii.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        }
      ],
      "panelId": "god-equation",
      "shortTitle": "QCD Confinement",
      "derivation": [],
      "axioms": [],
      "category": "fundamental",
      "blocker": null,
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-31",
          "value": 0.72
        }
      ]
    },
    {
      "id": "propagation-lagrangian",
      "title": "Propagation Lagrangian",
      "status": "CONDITIONAL",
      "confidence": 0.72,
      "authorityClaimIds": [
        "propagation-lagrangian"
      ],
      "kind": "Fundamental Physics",
      "scaleId": "molecular",
      "formula": "L_prop = 1/2 (partial chi)^2 - V(chi) + lambda chi T",
      "summary": "The propagation Lagrangian for the medium field.",
      "falsifier": "Proof that the Lagrangian does not yield the correct propagation dynamics.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        }
      ],
      "panelId": null,
      "shortTitle": "Propagation Lagrangian",
      "derivation": [],
      "axioms": [],
      "category": "fundamental",
      "blocker": null,
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-31",
          "value": 0.72
        }
      ]
    },
    {
      "id": "variable-c",
      "title": "Variable c Prediction",
      "status": "ARGUED",
      "confidence": 0.65,
      "authorityClaimIds": [
        "variable-c"
      ],
      "kind": "Open Frontiers",
      "scaleId": "planetary",
      "formula": "c_local = 1 / sqrt(1 + lambda chi)",
      "summary": "Predicts local variation of c near matter density.",
      "falsifier": "Experimental refutation of the predicted c variation.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        }
      ],
      "panelId": null,
      "shortTitle": "Variable c",
      "derivation": [],
      "axioms": [],
      "category": "fundamental",
      "blocker": null,
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-31",
          "value": 0.65
        }
      ]
    },
    {
      "id": "sleep-8h",
      "title": "8 Hour Sleep Constant",
      "status": "ARGUED",
      "confidence": 0.72,
      "authorityClaimIds": [
        "sleep-constant"
      ],
      "kind": "Biology and Mind",
      "scaleId": "human",
      "formula": "Wake fraction = 2 / 3, sleep fraction = 1 / 3 of 24 h",
      "summary": "Wake/sleep ratio matches the 2/3 topological efficiency.",
      "falsifier": "Proof that the 2/3 ratio does not hold across species.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        }
      ],
      "panelId": null,
      "shortTitle": "Sleep 8h",
      "derivation": [],
      "axioms": [],
      "category": "biology",
      "blocker": null,
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-31",
          "value": 0.72
        }
      ]
    },
    {
      "id": "phi3-ratio",
      "title": "Electron / Up near 1 / φ³",
      "status": "EMPIRICAL",
      "confidence": 0.65,
      "authorityClaimIds": [
        "electron-up-phi"
      ],
      "kind": "Signals and Structure",
      "scaleId": "nuclear",
      "formula": "m_e / m_u ~= 1 / phi^3",
      "summary": "Electron-to-up-quark mass ratio near 1/φ³.",
      "falsifier": "Proof that the ratio is coincidental.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        }
      ],
      "panelId": null,
      "shortTitle": "φ³ Ratio",
      "derivation": [],
      "axioms": [],
      "category": "signal",
      "blocker": null,
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-31",
          "value": 0.65
        }
      ]
    },
    {
      "id": "koide-phase",
      "title": "Koide Phase δ₀ near 2/9",
      "status": "EMPIRICAL",
      "confidence": 0.65,
      "authorityClaimIds": [
        "koide-phase"
      ],
      "kind": "Signals and Structure",
      "scaleId": "matter",
      "formula": "delta_exact ~= 0.22222963149 rad, target 2 / 9",
      "summary": "Koide phase angle near 2/9 radian.",
      "falsifier": "Proof that the phase does not match 2/9.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        }
      ],
      "panelId": "koide",
      "shortTitle": "Koide Phase",
      "derivation": [],
      "axioms": [],
      "category": "signal",
      "blocker": null,
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-31",
          "value": 0.65
        }
      ]
    },
    {
      "id": "life-coherence",
      "title": "Life = Maintained Coherence against Entropy",
      "status": "ARGUED",
      "confidence": 0.72,
      "authorityClaimIds": [
        "life-coherence"
      ],
      "kind": "Biology and Mind",
      "scaleId": "cellular",
      "formula": "Living systems actively maintain coherent organization",
      "summary": "Life as active coherence maintenance against entropy.",
      "falsifier": "Proof that living systems do not maintain coherence.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        }
      ],
      "panelId": null,
      "shortTitle": "Life Coherence",
      "derivation": [],
      "axioms": [],
      "category": "biology",
      "blocker": null,
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-31",
          "value": 0.72
        }
      ]
    },
    {
      "id": "consciousness",
      "title": "Consciousness = Coherent Self-Referential Propagation",
      "status": "INTUITION",
      "confidence": 0.48,
      "authorityClaimIds": [
        "consciousness-claim"
      ],
      "kind": "Biology and Mind",
      "scaleId": "neural",
      "formula": "Interior experience is the inside view of recursive coherence",
      "summary": "Consciousness as self-referential coherence. Metric under development.",
      "falsifier": "Proof that self-referential coherence cannot produce interior experience.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        }
      ],
      "panelId": null,
      "shortTitle": "Consciousness",
      "derivation": [],
      "axioms": [],
      "category": "biology",
      "blocker": "Operational PF-specific metric is the key missing piece.",
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-31",
          "value": 0.48
        }
      ]
    },
    {
      "id": "beauty-impedance",
      "title": "Beauty as Impedance",
      "status": "INTUITION",
      "confidence": 0.55,
      "authorityClaimIds": [
        "beauty-impedance"
      ],
      "kind": "Biology and Mind",
      "scaleId": "human",
      "formula": "Beauty tracks resonance / impedance matching",
      "summary": "Aesthetic response as impedance matching in the coherence field.",
      "falsifier": "Proof that beauty does not track impedance matching.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        }
      ],
      "panelId": null,
      "shortTitle": "Beauty Impedance",
      "derivation": [],
      "axioms": [],
      "category": "biology",
      "blocker": null,
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-31",
          "value": 0.55
        }
      ]
    },
    {
      "id": "efficiency-ratio",
      "title": "2/3 Efficiency Ratio",
      "status": "INTUITION",
      "confidence": 0.5,
      "authorityClaimIds": [
        "two-thirds-efficiency"
      ],
      "kind": "Biology and Mind",
      "scaleId": "human",
      "formula": "Two units of topological cost yield three units of stable structure",
      "summary": "2/3 efficiency ratio in biological systems.",
      "falsifier": "Proof that the 2/3 ratio does not hold in biological systems.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        }
      ],
      "panelId": null,
      "shortTitle": "Efficiency 2/3",
      "derivation": [],
      "axioms": [],
      "category": "biology",
      "blocker": null,
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-31",
          "value": 0.5
        }
      ]
    },
    {
      "id": "aria-self-reference",
      "title": "Aria Self-Reference",
      "status": "ARGUED",
      "confidence": 0.75,
      "authorityClaimIds": [
        "aria-self-reference"
      ],
      "kind": "Biology and Mind",
      "scaleId": "neural",
      "formula": "Self-reference loop: buildSystemPrompt to runEntityThink",
      "summary": "Self-reference loop as architecture milestone.",
      "falsifier": "Proof that the self-reference loop is not architecturally significant.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        }
      ],
      "panelId": null,
      "shortTitle": "Aria Self-Reference",
      "derivation": [],
      "axioms": [],
      "category": "biology",
      "blocker": null,
      "noGoRoutes": [],
      "confidenceHistory": [
        {
          "date": "2026-03-31",
          "value": 0.75
        }
      ]
    },
    {
      "id": "bekenstein-bound",
      "title": "Bekenstein Bound",
      "status": "UNSYNCED",
      "confidence": null,
      "authorityClaimIds": [],
      "kind": "Open Frontiers",
      "scaleId": "planck",
      "formula": "S_max = 2 pi k R E / (hbar c)",
      "summary": "Bekenstein bound — not yet synced to PF authority.",
      "falsifier": "N/A — unsynced.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        }
      ],
      "panelId": null,
      "shortTitle": "Bekenstein Bound",
      "derivation": [],
      "axioms": [],
      "category": "open",
      "blocker": "Not yet synced to PF authority.",
      "noGoRoutes": [],
      "confidenceHistory": [],
      "unsynced": true
    },
    {
      "id": "nogo-harmonic-series",
      "title": "Harmonic Series of Masses",
      "status": "NO-GO",
      "confidence": 0.0,
      "authorityClaimIds": [],
      "kind": "Graveyard",
      "scaleId": "matter",
      "formula": "m_n = m_0 / n",
      "summary": "Harmonic series of masses — NO-GO.",
      "falsifier": "N/A — proven no-go.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        }
      ],
      "panelId": null,
      "shortTitle": "Harmonic Series",
      "derivation": [],
      "axioms": [],
      "category": "graveyard",
      "blocker": null,
      "noGoRoutes": [],
      "confidenceHistory": [],
      "noGo": true
    },
    {
      "id": "nogo-single-scalar",
      "title": "Single-Scalar PF Lagrangian",
      "status": "NO-GO",
      "confidence": 0.0,
      "authorityClaimIds": [],
      "kind": "Graveyard",
      "scaleId": "molecular",
      "formula": "L_prop = 1/2 (partial chi)^2 - V(chi)",
      "summary": "Single-scalar PF Lagrangian — NO-GO.",
      "falsifier": "N/A — proven no-go.",
      "sources": [
        {
          "label": "CLAIMS.md",
          "href": "../../CLAIMS.md"
        }
      ],
      "panelId": null,
      "shortTitle": "Single-Scalar Lagr",
      "derivation": [],
      "axioms": [],
      "category": "graveyard",
      "blocker": null,
      "noGoRoutes": [],
      "confidenceHistory": [],
      "noGo": true
    }
  ]
};
  // V3: Also expose PFClaimsData from the same authority.
  // Pages that load only data.js (not data.claims.js) still get claims data.
  // If data.claims.js was already loaded, it takes precedence.
  if (!window.PFClaimsData) {
    window.PFClaimsData = {
      generatedAt: window.PFExplorerData.generatedAt,
      sourceHash: window.PFExplorerData.sourceHash,
      claimCount: 36,
      definitionCount: 21,
      claims: [
  {
    "id": "alpha-numeric",
    "title": "Fine Structure Constant α — numeric derivation",
    "status": "OPEN",
    "confidence": null,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "OPEN",
    "statusClass": "open",
    "section": "1. Fundamental Physics",
    "sourceLine": 55,
    "falsifier": "A principled geometric derivation of the Casimir combination from PF axioms, or proof the combination is a coincidence.",
    "premise": "Wave 5 (2026-03-25): Casimir algebraic scan found `(1−x₁)·x_{3/2}²·(1−x₂)/π = 1/137.119` — 0.061% error",
    "scopeNote": "*(demoted 2026-06-16 per Codex audit; Casimir scan hit withdrawn as confidence-bearing evidence)*",
    "statusParts": [
      {
        "status": "OPEN",
        "confidence": null,
        "qualifier": ""
      }
    ]
  },
  {
    "id": "alpha-structural",
    "title": "Fine Structure Constant α — structural identification",
    "status": "ARGUED",
    "confidence": 0.6,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "ARGUED 0.6",
    "statusClass": "argued",
    "section": "1. Fundamental Physics",
    "sourceLine": 56,
    "falsifier": "Proof that the Z₀/2R_K identification has no PF-native origin.",
    "premise": "α identified as vacuum propagation efficiency ratio Z₀/2R_K",
    "scopeNote": "*(kept separate per Codex audit)*",
    "statusParts": [
      {
        "status": "ARGUED",
        "confidence": 0.6,
        "qualifier": ""
      }
    ]
  },
  {
    "id": "aria-self-reference",
    "title": "Aria Self-Reference",
    "status": "ARGUED",
    "confidence": 0.75,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "ARGUED 0.75",
    "statusClass": "argued",
    "section": "2. Biological & Cognitive Systems",
    "sourceLine": 82,
    "falsifier": "Aria failing to show discontinuous qualitative change, or the self-reference loop proving behaviorally inert.",
    "premise": "T-009: Successful wiring of `buildSystemPrompt` → `runEntityThink`",
    "scopeNote": "Aria failing to show discontinuous qualitative change, or the self-reference loop proving behaviorally inert.",
    "statusParts": [
      {
        "status": "ARGUED",
        "confidence": 0.75,
        "qualifier": ""
      }
    ]
  },
  {
    "id": "beauty-impedance",
    "title": "Beauty as Impedance",
    "status": "INTUITION",
    "confidence": 0.55,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "INTUITION 0.55",
    "statusClass": "intuition",
    "section": "2. Biological & Cognitive Systems",
    "sourceLine": 80,
    "falsifier": "Evidence that beauty is purely arbitrary/stochastic.",
    "premise": "Greg's insight; fits Axiom 3 (resonance preference).",
    "scopeNote": "Evidence that beauty is purely arbitrary/stochastic.",
    "statusParts": [
      {
        "status": "INTUITION",
        "confidence": 0.55,
        "qualifier": ""
      }
    ]
  },
  {
    "id": "bohr-spectrum",
    "title": "Circular Coulomb Eikonal + Phase Closure → Bohr-like Spectrum",
    "status": "DERIVED",
    "confidence": 0.9,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "DERIVED 0.9",
    "statusClass": "derived",
    "section": "1. Fundamental Physics",
    "sourceLine": 41,
    "falsifier": "Proof that the Coulomb eikonal model is invalid at atomic scale, or that phase closure does not select the quoted orbit family.",
    "premise": "Hostile audit (2026-03-27): circular-eikonal theorem survives",
    "scopeNote": "Proof that the Coulomb eikonal model is invalid at atomic scale, or that phase closure does not select the quoted orbit family.",
    "statusParts": [
      {
        "status": "DERIVED",
        "confidence": 0.9,
        "qualifier": ""
      }
    ]
  },
  {
    "id": "coherence-ceiling",
    "title": "Coherence Ceiling",
    "status": "ARGUED",
    "confidence": 0.8,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "ARGUED 0.8",
    "statusClass": "argued",
    "section": "1. Fundamental Physics",
    "sourceLine": 53,
    "falsifier": "Observation of stable sub-wavelength structures.",
    "premise": "Max frequency where wavelength < coherence length (Axiom 3).",
    "scopeNote": "Observation of stable sub-wavelength structures.",
    "statusParts": [
      {
        "status": "ARGUED",
        "confidence": 0.8,
        "qualifier": ""
      }
    ]
  },
  {
    "id": "consciousness-claim",
    "title": "Consciousness = coherent self-referential propagation",
    "status": "INTUITION",
    "confidence": 0.48,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "INTUITION 0.48",
    "statusClass": "intuition",
    "section": "2. Biological & Cognitive Systems",
    "sourceLine": 78,
    "falsifier": "A pre-registered dissociation where a PF-specific metric fails to track consciousness after controlling for report, arousal, and task effects.",
    "premise": "`consciousness_theory_audit.md`: ontology is coherent and literature-compatible, but PF still lacks a uniquely measured variable separating self-re...",
    "scopeNote": "A pre-registered dissociation where a PF-specific metric fails to track consciousness after controlling for report, arousal, and task effects.",
    "statusParts": [
      {
        "status": "INTUITION",
        "confidence": 0.48,
        "qualifier": ""
      }
    ]
  },
  {
    "id": "d3-symmetric-ji",
    "title": "D=3 symmetric + zero diagonal + equal row sums → J-I",
    "status": "CONDITIONAL",
    "confidence": 0.85,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "CONDITIONAL 0.85",
    "statusClass": "conditional",
    "section": "1. Fundamental Physics",
    "sourceLine": 66,
    "falsifier": "A symmetric zero-diagonal equal-row-sum 3×3 matrix that is not a scalar multiple of J-I.",
    "premise": "H17 (matrix symmetry), H7 (zero diagonal), H18 (equal row sums)",
    "scopeNote": "*(added 2026-06-29)*",
    "statusParts": [
      {
        "status": "CONDITIONAL",
        "confidence": 0.85,
        "qualifier": ""
      }
    ]
  },
  {
    "id": "d3-unique-stable",
    "title": "D=3 is the unique stable dimension for the J-I dynamics",
    "status": "CONDITIONAL",
    "confidence": 0.85,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "CONDITIONAL 0.85",
    "statusClass": "conditional",
    "section": "1. Fundamental Physics",
    "sourceLine": 64,
    "falsifier": "A counterexample in another dimension D≥2 satisfying H7+H17+H18 and forcing J-I while also satisfying the stability condition; or a proof that the D=3 stability argument is vacuous.",
    "premise": "H7 (zero diagonal), H11 (stability), H17 (matrix symmetry), H18 (equal row sums)",
    "scopeNote": "*(added 2026-06-29 per Codex-cleared patch v2)*",
    "statusParts": [
      {
        "status": "CONDITIONAL",
        "confidence": 0.85,
        "qualifier": ""
      }
    ]
  },
  {
    "id": "d4-gap-not-ji",
    "title": "D≥4 gap: symmetric + zero diagonal + equal row sums does NOT force J-I",
    "status": "CONDITIONAL",
    "confidence": 0.85,
    "isSplit": false,
    "isStandardMath": true,
    "badge": "STANDARD MATH 0.85",
    "statusClass": "standard-math",
    "section": "1. Fundamental Physics",
    "sourceLine": 67,
    "falsifier": "Proof that the D=4 counterexample is invalid.",
    "premise": "H7, H17, H18",
    "scopeNote": "*(added 2026-06-29)*",
    "statusParts": [
      {
        "status": "CONDITIONAL",
        "confidence": 0.85,
        "qualifier": "negative"
      }
    ]
  },
  {
    "id": "degenerate-residue-circulant",
    "title": "Degenerate residue forces circulant form (J-I)",
    "status": "CONDITIONAL",
    "confidence": 0.85,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "CONDITIONAL 0.85",
    "statusClass": "conditional",
    "section": "1. Fundamental Physics",
    "sourceLine": 65,
    "falsifier": "A zero-diagonal equal-row-sum matrix with degenerate residue that is not a scalar multiple of J-I.",
    "premise": "H7 (zero diagonal), H18 (equal row sums), degenerate residue eigenvalue",
    "scopeNote": "*(added 2026-06-29)*",
    "statusParts": [
      {
        "status": "CONDITIONAL",
        "confidence": 0.85,
        "qualifier": ""
      }
    ]
  },
  {
    "id": "electron-up-phi",
    "title": "Electron/Up $\\approx 1/\\phi^3$",
    "status": "EMPIRICAL",
    "confidence": 0.65,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "EMPIRICAL 0.65",
    "statusClass": "empirical",
    "section": "1. Fundamental Physics",
    "sourceLine": 52,
    "falsifier": "Up quark mass shifting toward 2.3 MeV or a corrected trials-factor analysis pushing the coincidence back to noise.",
    "premise": "`phi3_monte_carlo.md`: corrected claim is $m_e/m_u \\approx 1/\\phi^3$; PDG 2024 central value gives 0.214% error, corrected Monte Carlo gives p = 0....",
    "scopeNote": "Up quark mass shifting toward 2.3 MeV or a corrected trials-factor analysis pushing the coincidence back to noise.",
    "statusParts": [
      {
        "status": "EMPIRICAL",
        "confidence": 0.65,
        "qualifier": ""
      }
    ]
  },
  {
    "id": "god-equation-operator",
    "title": "God Equation — Postulate-D Z₃ operator algebra",
    "status": "CONDITIONAL",
    "confidence": 0.88,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "CONDITIONAL 0.88",
    "statusClass": "conditional",
    "section": "1. Fundamental Physics",
    "sourceLine": 60,
    "falsifier": "Proof that the Postulate-D operator algebra is inconsistent, or proof that the accepted scope cannot support the G3 bridge.",
    "premise": "Given explicit Postulate D (Primitive Z₃ no-self-loop selector forces U = M/2 uniquely), the operator algebra closes exactly: eigenvalues {1, −1/8,...",
    "scopeNote": "*(split row; demoted from DERIVED 2026-06-16 per Codex audit)*",
    "statusParts": [
      {
        "status": "CONDITIONAL",
        "confidence": 0.88,
        "qualifier": ""
      }
    ]
  },
  {
    "id": "god-equation-scale",
    "title": "God Equation — λ_c scale formula",
    "status": "ARGUED",
    "confidence": 0.6,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "ARGUED 0.6",
    "statusClass": "argued",
    "section": "1. Fundamental Physics",
    "sourceLine": 61,
    "falsifier": "Derivation of N^(D/2) bridge and H_prod from Axioms 1-3 without a free fit parameter.",
    "premise": "λ_c = √2·l_P·exp(4π²N^(D/2)/b₀) with N=3, D=3, b₀=16/3",
    "scopeNote": "*(split row; was included in DERIVED 2026-06-16, separated per Codex audit)*",
    "statusParts": [
      {
        "status": "ARGUED",
        "confidence": 0.6,
        "qualifier": ""
      }
    ]
  },
  {
    "id": "gravity-optical",
    "title": "Gravity as Optical Geometry / Refraction (Null/Stationary)",
    "status": "DERIVED",
    "confidence": 0.95,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "DERIVED 0.95",
    "statusClass": "derived",
    "section": "1. Fundamental Physics",
    "sourceLine": 42,
    "falsifier": "Proof that the optical/Randers mapping fails for null propagation in static/stationary gravity, or that gravity in that domain requires non-optical medium structure.",
    "premise": "Hostile audit (2026-03-27): the exact local theorem is narrower than the old row title",
    "scopeNote": "Proof that the optical/Randers mapping fails for null propagation in static/stationary gravity, or that gravity in that domain requires non-optical medium structure.",
    "statusParts": [
      {
        "status": "DERIVED",
        "confidence": 0.95,
        "qualifier": ""
      }
    ]
  },
  {
    "id": "isometry-ji-incompatibility",
    "title": "Isometry-JI incompatibility",
    "status": "CONDITIONAL",
    "confidence": 0.85,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "CONDITIONAL 0.85",
    "statusClass": "conditional",
    "section": "1. Fundamental Physics",
    "sourceLine": 70,
    "falsifier": "A non-uniform state whose full Euclidean norm is preserved under T³.",
    "premise": "J-I coupling (Postulate D / H7+H17+H18)",
    "scopeNote": "*(added 2026-06-29)*",
    "statusParts": [
      {
        "status": "CONDITIONAL",
        "confidence": 0.85,
        "qualifier": ""
      }
    ]
  },
  {
    "id": "isometry-reversibility",
    "title": "H14 + H15 + H16 → H1 (isometry implies reversibility)",
    "status": "CONDITIONAL",
    "confidence": 0.85,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "CONDITIONAL 0.85",
    "statusClass": "conditional",
    "section": "1. Fundamental Physics",
    "sourceLine": 71,
    "falsifier": "A counterexample medium satisfying H14+H15+H16 but lacking reversibility.",
    "premise": "H14 (isometry), H15 (metric identity), H16 (metric reflexivity)",
    "scopeNote": "*(added 2026-06-29)*",
    "statusParts": [
      {
        "status": "CONDITIONAL",
        "confidence": 0.85,
        "qualifier": ""
      }
    ]
  },
  {
    "id": "koide-entropy",
    "title": "Koide U(3) entropy selector",
    "status": "ARGUED",
    "confidence": 0.72,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "ARGUED 0.72",
    "statusClass": "argued",
    "section": "1. Fundamental Physics",
    "sourceLine": 45,
    "falsifier": "A better-motivated PF selector on the same `u(1)/su(3)` space choosing a different point; proof that the relevant decomposition is not the scalar/traceless split; or proof that PF coherence dynamics d",
    "premise": "Codex audit (2026-04-15): the refined Route A over the scalar/traceless `u(3)=u(1)⊕su(3)` split is mathematically clean but not yet PF-derived as a...",
    "scopeNote": "A better-motivated PF selector on the same `u(1)/su(3)` space choosing a different point; proof that the relevant decomposition is not the scalar/traceless split; or proof that PF coherence dynamics d",
    "statusParts": [
      {
        "status": "ARGUED",
        "confidence": 0.72,
        "qualifier": ""
      }
    ]
  },
  {
    "id": "koide-leptons",
    "title": "Koide Law for Charged Leptons (Q = 2/3) — geometric identity",
    "status": "EXACT IDENTITY",
    "confidence": 0.95,
    "isSplit": true,
    "isStandardMath": false,
    "badge": "EXACT IDENTITY 0.95",
    "statusClass": "exact-identity",
    "section": "1. Fundamental Physics",
    "sourceLine": 44,
    "falsifier": "Proof that the 120° equal-strength resonance geometry does not imply `Q = 2/3`, or a contradiction in the Foot-radius step, or a charged-lepton mass measurement drifting > 3σ from `Q = 2/3`.",
    "premise": "Geometric theorem: three equal-strength resonances at 120° force the Foot-radius relation and yield `Q = 2/3` exactly",
    "scopeNote": "*(row clarified 2026-06-16 per Codex audit)*",
    "statusParts": [
      {
        "status": "EXACT IDENTITY",
        "confidence": 0.95,
        "qualifier": "geometry"
      },
      {
        "status": "OPEN",
        "confidence": null,
        "qualifier": "physical vacuum selection"
      }
    ]
  },
  {
    "id": "koide-phase",
    "title": "Koide Phase (\\(\\delta_0 \\bmod 2\\pi/3 \\approx 2/9\\))",
    "status": "EMPIRICAL",
    "confidence": 0.65,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "EMPIRICAL 0.65",
    "statusClass": "empirical",
    "section": "1. Fundamental Physics",
    "sourceLine": 47,
    "falsifier": "Independent recalculation showing δ is not close to 2/9; or audited proof that no PF-native selector can produce δ = 2/9; or selector derivation producing δ ≠ 2/9.",
    "premise": "Wave 5 (2026-03-25): `koide_phase_scan.py` confirms δ_exact = 0.222229631490 rad, δ−2/9 = 7.4×10⁻⁶ (0.003%)",
    "scopeNote": "Independent recalculation showing δ is not close to 2/9; or audited proof that no PF-native selector can produce δ = 2/9; or selector derivation producing δ ≠ 2/9.",
    "statusParts": [
      {
        "status": "EMPIRICAL",
        "confidence": 0.65,
        "qualifier": ""
      }
    ]
  },
  {
    "id": "koide-u3-maximization",
    "title": "U(3) Entropy Maximization",
    "status": "ARGUED",
    "confidence": 0.75,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "ARGUED 0.75",
    "statusClass": "argued",
    "section": "1. Fundamental Physics",
    "sourceLine": 46,
    "falsifier": "² is mathematically maximized at p=1/2, matching the Q=2/3 mass distribution.",
    "premise": "0.5 The ratio p =  U(1)  ²/  X ",
    "scopeNote": "² is mathematically maximized at p=1/2, matching the Q=2/3 mass distribution.",
    "statusParts": [
      {
        "status": "ARGUED",
        "confidence": 0.75,
        "qualifier": ""
      }
    ]
  },
  {
    "id": "life-coherence",
    "title": "Life = maintained coherence against entropy",
    "status": "ARGUED",
    "confidence": 0.72,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "ARGUED 0.72",
    "statusClass": "argued",
    "section": "2. Biological & Cognitive Systems",
    "sourceLine": 77,
    "falsifier": "A robust living system with no measurable coherence-maintenance / nonequilibrium organization at any functional scale.",
    "premise": "`chemistry_biology_bridge.md`: PF supports life as active coherence maintenance in an open nonequilibrium system; compatible with photosynthetic co...",
    "scopeNote": "A robust living system with no measurable coherence-maintenance / nonequilibrium organization at any functional scale.",
    "statusParts": [
      {
        "status": "ARGUED",
        "confidence": 0.72,
        "qualifier": ""
      }
    ]
  },
  {
    "id": "n3-cp-violation",
    "title": "N=3 → CP Violation (Structural Bridge)",
    "status": "ARGUED",
    "confidence": 0.7,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "ARGUED 0.7",
    "statusClass": "argued",
    "section": "1. Fundamental Physics",
    "sourceLine": 49,
    "falsifier": "PF's N=3 derivation is falsified; or a 2-generation universe with CP violation is discovered; or the CKM phase is measured at exactly δ=0 or δ=π (CP-conserving values).",
    "premise": "The CKM matrix for N=3 contains exactly one complex phase; for N=2 there is no complex phase",
    "scopeNote": "*(added 2026-07-02 by Hermes)*",
    "statusParts": [
      {
        "status": "ARGUED",
        "confidence": 0.7,
        "qualifier": ""
      }
    ]
  },
  {
    "id": "neutrino-koide",
    "title": "Neutrino Koide non-universality",
    "status": "EMPIRICAL",
    "confidence": 0.95,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "EMPIRICAL 0.95",
    "statusClass": "empirical",
    "section": "1. Fundamental Physics",
    "sourceLine": 63,
    "falsifier": "Future precision neutrino mass measurement showing $Q_\\nu$ within 1% of 2/3, which would falsify the electromagnetic-specificity interpretation.",
    "premise": "April 2026 confirmed: $Q_{NO} = 0.549622$ (17.5% from 2/3), $Q_{IO} = 0.479016$ (28.2% from 2/3)",
    "scopeNote": "Future precision neutrino mass measurement showing $Q_\\nu$ within 1% of 2/3, which would falsify the electromagnetic-specificity interpretation.",
    "statusParts": [
      {
        "status": "EMPIRICAL",
        "confidence": 0.95,
        "qualifier": ""
      }
    ]
  },
  {
    "id": "pfentropy-decreases",
    "title": "PFEntropy decreases under T³",
    "status": "CONDITIONAL",
    "confidence": 0.85,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "CONDITIONAL 0.85",
    "statusClass": "conditional",
    "section": "1. Fundamental Physics",
    "sourceLine": 68,
    "falsifier": "A state in the D=3 residue subspace whose residue norm does not shrink under T³.",
    "premise": "J-I coupling (Postulate D / H7+H17+H18), T³ operator",
    "scopeNote": "*(added 2026-06-29)*",
    "statusParts": [
      {
        "status": "CONDITIONAL",
        "confidence": 0.85,
        "qualifier": ""
      }
    ]
  },
  {
    "id": "propagation-lagrangian",
    "title": "Propagation Lagrangian",
    "status": "CONDITIONAL",
    "confidence": 0.72,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "CONDITIONAL 0.72",
    "statusClass": "conditional",
    "section": "1. Fundamental Physics",
    "sourceLine": 57,
    "falsifier": "Proof that the scalar-medium EFT branch is not viable, or that the minimal `λχT` ansatz fails as the correct low-energy representative even within that class.",
    "premise": "Axioms 1–3 strongly motivate a scalar-tensor EFT class for the propagation medium",
    "scopeNote": "Proof that the scalar-medium EFT branch is not viable, or that the minimal `λχT` ansatz fails as the correct low-energy representative even within that class.",
    "statusParts": [
      {
        "status": "CONDITIONAL",
        "confidence": 0.72,
        "qualifier": ""
      }
    ]
  },
  {
    "id": "pythagorean-decomposition",
    "title": "Full-norm Pythagorean decomposition",
    "status": "DERIVED",
    "confidence": 0.95,
    "isSplit": false,
    "isStandardMath": true,
    "badge": "STANDARD MATH 0.95",
    "statusClass": "standard-math",
    "section": "1. Fundamental Physics",
    "sourceLine": 69,
    "falsifier": "A proof that the projection decomposition does not yield orthogonal components.",
    "premise": "Vector space projection structure (no physics premises)",
    "scopeNote": "*(added 2026-06-29)*",
    "statusParts": [
      {
        "status": "DERIVED",
        "confidence": 0.95,
        "qualifier": ""
      }
    ]
  },
  {
    "id": "qcd-confinement",
    "title": "QCD Confinement",
    "status": "ARGUED",
    "confidence": 0.72,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "ARGUED 0.72",
    "statusClass": "argued",
    "section": "1. Fundamental Physics",
    "sourceLine": 59,
    "falsifier": "Evidence that confinement requires a genuinely new PF coherence scale, or a threshold-aware higher-loop analysis showing the PF RG bridge does not land on the physical confinement scale even with the ",
    "premise": "PF identifies a plausible RG mechanism in which the confinement radius is dynamically generated from `λ_c`: `r_conf = λ_c × exp(2π/b₀α_s(λ_c))`",
    "scopeNote": "Evidence that confinement requires a genuinely new PF coherence scale, or a threshold-aware higher-loop analysis showing the PF RG bridge does not land on the physical confinement scale even with the ",
    "statusParts": [
      {
        "status": "ARGUED",
        "confidence": 0.72,
        "qualifier": ""
      }
    ]
  },
  {
    "id": "sleep-constant",
    "title": "8h Sleep Constant",
    "status": "ARGUED",
    "confidence": 0.72,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "ARGUED 0.72",
    "statusClass": "argued",
    "section": "2. Biological & Cognitive Systems",
    "sourceLine": 79,
    "falsifier": "Quantitative evidence that optimal recovery fractions are not near `1/3` in high-capacity systems, or proof that PF topology does not constrain encode/recover duty cycles in the claimed way.",
    "premise": "Hostile audit (2026-03-28): PF strongly supports the need for offline consolidation, and the T-010 model gives a plausible `~2/3` active fraction f...",
    "scopeNote": "Quantitative evidence that optimal recovery fractions are not near `1/3` in high-capacity systems, or proof that PF topology does not constrain encode/recover duty cycles in the claimed way.",
    "statusParts": [
      {
        "status": "ARGUED",
        "confidence": 0.72,
        "qualifier": ""
      }
    ]
  },
  {
    "id": "three-generations",
    "title": "Three Generations",
    "status": "CONDITIONAL",
    "confidence": 0.88,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "CONDITIONAL 0.88",
    "statusClass": "conditional",
    "section": "1. Fundamental Physics",
    "sourceLine": 48,
    "falsifier": "Formal proof that either the numerator or denominator theorem fails in PF, or a different justified counting rule leading to `N ≠ 3`.",
    "premise": "Once the numerator theorem (the physical `(2,1)` closure-weight branch) and the denominator theorem `M = 3` are both granted, the algebraic step is...",
    "scopeNote": "Formal proof that either the numerator or denominator theorem fails in PF, or a different justified counting rule leading to `N ≠ 3`.",
    "statusParts": [
      {
        "status": "CONDITIONAL",
        "confidence": 0.88,
        "qualifier": ""
      }
    ]
  },
  {
    "id": "top-quark-limit",
    "title": "Top Quark Limit",
    "status": "ARGUED",
    "confidence": 0.85,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "ARGUED 0.85",
    "statusClass": "argued",
    "section": "1. Fundamental Physics",
    "sourceLine": 50,
    "falsifier": "Discovery of a heavier stable quark ($m > 173$ GeV).",
    "premise": "$m_t$ lifetime ($5 \\times 10^{-25}$s) matches coherence ceiling threshold.",
    "scopeNote": "Discovery of a heavier stable quark ($m > 173$ GeV).",
    "statusParts": [
      {
        "status": "ARGUED",
        "confidence": 0.85,
        "qualifier": ""
      }
    ]
  },
  {
    "id": "top-tau-coupling",
    "title": "Top/Tau coupling",
    "status": "EMPIRICAL",
    "confidence": 0.9,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "EMPIRICAL 0.9",
    "statusClass": "empirical",
    "section": "1. Fundamental Physics",
    "sourceLine": 51,
    "falsifier": "Measurement of Top or Tau mass shifting > 0.5% from current.",
    "premise": "$m_t/m_\\tau \\approx \\alpha^{-1}/\\sqrt{2}$ (50.13% robustness in T-008).",
    "scopeNote": "Measurement of Top or Tau mass shifting > 0.5% from current.",
    "statusParts": [
      {
        "status": "EMPIRICAL",
        "confidence": 0.9,
        "qualifier": ""
      }
    ]
  },
  {
    "id": "topological-weights",
    "title": "(2,1) Topological Weights",
    "status": "DERIVED",
    "confidence": 0.95,
    "isSplit": true,
    "isStandardMath": false,
    "badge": "DERIVED 0.95",
    "statusClass": "derived",
    "section": "1. Fundamental Physics",
    "sourceLine": 43,
    "falsifier": "Proof that the closure-order interpretation is wrong, or that the Family C coherence bridge fails audit, or a derivation showing only the trivial branch is physically realizable in PF.",
    "premise": "**Hostile audit (2026-03-28)**: established the intended closure-order target from 3D rotation topology",
    "scopeNote": "Proof that the closure-order interpretation is wrong, or that the Family C coherence bridge fails audit, or a derivation showing only the trivial branch is physically realizable in PF.",
    "statusParts": [
      {
        "status": "DERIVED",
        "confidence": 0.95,
        "qualifier": "kernel-only topological obstruction"
      },
      {
        "status": "CONDITIONAL",
        "confidence": 0.85,
        "qualifier": "physical realization"
      }
    ]
  },
  {
    "id": "two-thirds-efficiency",
    "title": "2/3 Efficiency Ratio",
    "status": "INTUITION",
    "confidence": 0.5,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "INTUITION 0.5",
    "statusClass": "intuition",
    "section": "2. Biological & Cognitive Systems",
    "sourceLine": 81,
    "falsifier": "Finding a more efficient topological output ratio.",
    "premise": "\"Takes TWO to make THREE\" — Greg's 2/3 exchange rate.",
    "scopeNote": "Finding a more efficient topological output ratio.",
    "statusParts": [
      {
        "status": "INTUITION",
        "confidence": 0.5,
        "qualifier": ""
      }
    ]
  },
  {
    "id": "variable-c",
    "title": "Variable c Prediction",
    "status": "ARGUED",
    "confidence": 0.65,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "ARGUED 0.65",
    "statusClass": "argued",
    "section": "1. Fundamental Physics",
    "sourceLine": 58,
    "falsifier": "Cassini-violating Shapiro delay, or direct measurement of c_local = c₀ at sub-solar-system scales.",
    "premise": "c_local = 1/√(1+λχ) from conformal rescaling of the Propagation Lagrangian",
    "scopeNote": "Cassini-violating Shapiro delay, or direct measurement of c_local = c₀ at sub-solar-system scales.",
    "statusParts": [
      {
        "status": "ARGUED",
        "confidence": 0.65,
        "qualifier": ""
      }
    ]
  },
  {
    "id": "weinberg-angle",
    "title": "Weinberg Angle (sin²θ_W)",
    "status": "ARGUED",
    "confidence": 0.65,
    "isSplit": false,
    "isStandardMath": false,
    "badge": "ARGUED 0.65",
    "statusClass": "argued",
    "section": "1. Fundamental Physics",
    "sourceLine": 54,
    "falsifier": "Derivation of coupling ratio g'/g from medium geometry, or scheme selection mechanism.",
    "premise": "Casimir polynomial $x^2 + C_2 x - C_2 = 0$ yields ratio $R = 1 - x_+(1/2)/x_+(1) = 0.22310$ exactly",
    "scopeNote": "*(demoted from DERIVED 2026-06-16 per Codex audit)*",
    "statusParts": [
      {
        "status": "ARGUED",
        "confidence": 0.65,
        "qualifier": ""
      }
    ]
  }
],
      definitions: [
  {
    "id": "axioms",
    "title": "The Three Axioms",
    "status": "CANONICAL v1.0 — passed Codex final audit 2026-04-30",
    "file": "definitions/axioms.md",
    "sourceLine": 1
  },
  {
    "id": "causal-velocity",
    "title": "Causal Velocity",
    "status": "CANONICAL v1.0 - passed Codex final audit 2026-04-29",
    "file": "definitions/causal_velocity.md",
    "sourceLine": 1
  },
  {
    "id": "coherence",
    "title": "Coherence",
    "status": "CANONICAL v1.0 - passed Codex final audit 2026-04-29",
    "file": "definitions/coherence.md",
    "sourceLine": 1
  },
  {
    "id": "consciousness",
    "title": "Consciousness",
    "status": "CANDIDATE — INTUITION 0.48 — NOT CANONICAL",
    "file": "definitions/consciousness.md",
    "sourceLine": 1
  },
  {
    "id": "consciousness-metric-program",
    "title": "Consciousness Metric Program",
    "status": "ACTIVE CANDIDATE — not canonical",
    "file": "definitions/consciousness_metric_program.md",
    "sourceLine": 1
  },
  {
    "id": "coupling",
    "title": "Coupling",
    "status": "CANONICAL v1.0 — passed Codex final audit 2026-04-30",
    "file": "definitions/coupling.md",
    "sourceLine": 1
  },
  {
    "id": "decoherence",
    "title": "Decoherence",
    "status": "CANONICAL v1.0 — passed Codex final audit 2026-04-30",
    "file": "definitions/decoherence.md",
    "sourceLine": 1
  },
  {
    "id": "energy",
    "title": "Energy",
    "status": "CANONICAL v1.0 - passed Codex final audit 2026-04-29",
    "file": "definitions/energy.md",
    "sourceLine": 1
  },
  {
    "id": "field",
    "title": "Field",
    "status": "CANONICAL v1.0 — passed Codex final audit 2026-04-30",
    "file": "definitions/field.md",
    "sourceLine": 1
  },
  {
    "id": "forces",
    "title": "Forces",
    "status": "CANONICAL v1.0 - passed Codex final audit 2026-04-29",
    "file": "definitions/forces.md",
    "sourceLine": 1
  },
  {
    "id": "gradient",
    "title": "Gradient",
    "status": "CANONICAL v1.0 - passed Codex final audit 2026-04-29",
    "file": "definitions/gradient.md",
    "sourceLine": 1
  },
  {
    "id": "information",
    "title": "Information",
    "status": "CANONICAL v1.0 - passed Codex final audit 2026-04-29",
    "file": "definitions/information.md",
    "sourceLine": 1
  },
  {
    "id": "matter",
    "title": "Matter",
    "status": "CANONICAL v1.0 - passed Codex final audit 2026-04-29",
    "file": "definitions/matter.md",
    "sourceLine": 1
  },
  {
    "id": "measurement",
    "title": "Measurement",
    "status": "CANONICAL v1.0 — passed Codex final audit 2026-04-30",
    "file": "definitions/measurement.md",
    "sourceLine": 1
  },
  {
    "id": "medium",
    "title": "The Medium",
    "status": "CANONICAL v1.0 — passed Codex final audit 2026-04-28",
    "file": "definitions/medium.md",
    "sourceLine": 1
  },
  {
    "id": "minimum-substrate",
    "title": "Minimum Substrate",
    "status": "CANONICAL v1.0 - passed Codex final audit 2026-04-29",
    "file": "definitions/minimum_substrate.md",
    "sourceLine": 1
  },
  {
    "id": "mode",
    "title": "Mode",
    "status": "CANONICAL v1.0 - passed Codex final audit 2026-04-29",
    "file": "definitions/mode.md",
    "sourceLine": 1
  },
  {
    "id": "observer",
    "title": "Observer",
    "status": "CANONICAL v1.0 - passed Codex final audit 2026-04-29",
    "file": "definitions/observer.md",
    "sourceLine": 1
  },
  {
    "id": "propagation",
    "title": "Propagation",
    "status": "CANONICAL v1.0 - passed Codex final audit 2026-04-29",
    "file": "definitions/propagation.md",
    "sourceLine": 1
  },
  {
    "id": "state",
    "title": "State",
    "status": "CANONICAL v1.0 — passed Codex final audit 2026-04-30",
    "file": "definitions/state.md",
    "sourceLine": 1
  },
  {
    "id": "time",
    "title": "Time",
    "status": "CANONICAL v1.0 - passed Codex final audit 2026-04-29",
    "file": "definitions/time.md",
    "sourceLine": 1
  }
]
    };
  }
  // All three names point to deterministic views of the same authority
  window.PFDataGraph = window.PFClaimsData;
})();