// AUTO-GENERATED by generate_claims_data_v2.py — DO NOT EDIT MANUALLY
// Source: CLAIMS.md
// This file is a thin alias. The canonical generated data is in data.claims.js.
// data.graph.js exists only for backward compatibility with code that reads
// window.PFDataGraph. It must NOT contain independent claim data.
//
// The dual-source split (PFDataGraph vs PFClaimsData) has been eliminated.
// Both names now point to the same generated object.

// PFDataGraph is set to PFClaimsData after data.claims.js loads.
// This stub ensures the name exists for any code that checks it before
// data.claims.js has loaded.
window.PFDataGraph = window.PFClaimsData || { claims: [], definitions: [] };
